### PR TITLE
Add support for setting vxlan flood vtep

### PR DESCRIPTION
**Pull request by quulah**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Documentation content changes
- [ ] Other (please describe):

## Related Issue(s)

Related to #979

## Component(s) name

`arista.avd.eos_cli_config_gen`

## Proposed changes

- Add supports for specifying `flood vtep` parameters on Vxlan1

## Checklist:

- [X] My code has been rebased from devel before I start
- [X] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contributing/) document.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly
- [X] All new and existing tests passed ([`pre-commit`](https://www.avd.sh/docs/installation/development/#python-virtual-environment), `make linting` and `make sanity-lint`).

### CODE REVIEW

**Comment by carlbuchmann** [comment]
@quulah Thank you for your contributions - the list of PRs you have submitted is fantastic!
Note, that we plan to support media fabric use cases in eos_designs, and your input would be greatly appreciated!

Please also update the molecule test case for eos_cli_config_gen for all PRs have submitted. Here's the guide -> https://avd.sh/en/latest/molecule/#if-you-are-updating-eos_cli_config_gen

If you have any questions please feel free to reach out!
#Arista channel on NTC Slack: http://slack.networktocode.com/

**Comment by quulah** [comment]
@carlbuchmann Fixed a small problem in the template, rebased to current devel and added the Molecule tests.

Could you verify that it looks correct? I could then handle the rest. :)

**Review by onurgashi — APPROVED** [review]
LGTM! Nice PR @quulah

**Comment by carlbuchmann** [comment]
@quulah - Thank you again for this PR, and you have updated the molecule tests accordingly! However, after taking a closer review of the suggested data model, I noticed it didn't follow our standards for `eos_cli_config_gen`, including the current data model!

The proposed data model will need to be reviewed and accepted by another maintainer before we proceed further on this PR. Note this PR has been assigned to milestone 3.0.0 and can only be merged after release 2.2.0 planned for June 11th. 
I have converted the PR to draft, until ready for review!

New suggested data model for `vxlan_tunnel_interface:`


```yaml
vxlan_tunnel_interface:
  Vxlan1:
    description: < description >
    vxlan:
      source_interface: < source_interface_name >
      udp_port: < udp_port >
      virtual_router_encapsulation_mac_address: < mlag-system-id | ethernet_address (H.H.H) >
      vlans:
        < vlan_id_1 >:
          vni: < vni_id_1 >
          flood_vteps:
            - < remote_1_ip_address >
            - < remote_2_ip_address >
        < vlan_id_2 >:
          vni: < vni_id_2 >
          flood_vteps:
            - < remote_1_ip_address >
            - < remote_2_ip_address >
      vrfs:
        < vrf_name >:
          vni: < vni_id_3 >
        < vrf_name >:
          vni: < vni_id_4 >
      flood_vteps:
        - < remote_1_ip_address >
        - < remote_2_ip_address >
      flood_vtep_learned_data_plate: < true | false >
```

Example input:

```yaml
vxlan_tunnel_interface:
  Vxlan1:
    description: DC1-LEAF2A_VTEP
    vxlan:
      source_interface: Loopback1
      upd_port: 4789
      virtual_router_encapsulation_mac_address: "mlag-system-id"
      vlans:
        110:
          vni: 10110
        111:
          vni: 10111
          flood_vteps:
            - 10.1.1.10
            - 10.1.1.11
      vrfs:
        Tenant_A_OP_Zone:
          vni: 10
        Tenant_A_WEB_Zone:
          vni: 11
      flood_vteps:
        - 10.1.0.10
        - 10.1.0.11
      flood_vtep_learned_data_plane: < true | false >
```

Example output:

```eos
!
interface Vxlan1
   vxlan source-interface Loopback1
   vxlan virtual-router encapsulation mac-address mlag-system-id
   vxlan udp-port 4789
   vxlan flood vtep learned data-plane
   vxlan vlan 110 vni 10110
   vxlan vlan 111 vni 10111
   vxlan vrf Tenant_A_OP_Zone vni 10
   vxlan vrf Tenant_A_WEB_Zone vni 11
   vxlan vlan 111 flood vtep 10.1.1.10 10.1.1.11
   vxlan flood vtep 10.1.0.10 10.1.0.11
```

Once approved, there two options on how to proceed with this feature request:
1. We can co-develop in your fork/branch and make the necessary modifications
    - We will help convert the current data models, and modification required to `eos_designs` role.
2. Take over this PR and complete both current and new suggested feature support.

@ClausHolbechArista @titom73 @aphillipps

**Comment by quulah** [comment]
Ah, okay. Didn't realize there was a set data model nor that a change was coming. :)

I have internally ran it as it was in my initial PR. But the usage is not extensive yet, so it's easy enough to do a change and then change the parts that are setting the variables currently.

For the `flood vtep` itself it is a straightforward change, just dropping the `remotes` from in-between essentially.

But I see there are other changes proposed too, such as the VNI mapping changing quite a bit from a separate key to `vlans` having the VNI information.

Hence, I'd say that it's better to make the data model change somewhere else to avoid overloading this PR with other changes.

**Comment by carlbuchmann** [comment]
> Ah, okay. Didn't realize there was a set data model nor that a change was coming. :)
> 
> I have internally ran it as it was in my initial PR. But the usage is not extensive yet, so it's easy enough to do a change and then change the parts that are setting the variables currently.
> 
> For the `flood vtep` itself it is a straightforward change, just dropping the `remotes` from in-between essentially.
> 
> But I see there are other changes proposed too, such as the VNI mapping changing quite a bit from a separate key to `vlans` having the VNI information.
> 
> Hence, I'd say that it's better to make the data model change somewhere else to avoid overloading this PR with other changes.

Thank you for your understanding...Me neither, it's only after a review of your PR that I realized the current data model didn't follow our own guidelines! And we are about to release AVD 3.0.0, so it's a perfect time to make these modifications!

Very good to know how you are leveraging AVD, and thank you for "upstreaming" your modifications - we really appreciate contributions from the external community!

So I will take over your changes in my fork, and create a new branch. I will keep this PR open until a new PR is created.

**Comment by carlbuchmann** [comment]
@quulah - just a quick update that we will continue to work on this after PR #1000 has been merged!

**Comment by carlbuchmann** [comment]
replaced by PR #1121

**Pull request closed without merging**
