### PR TITLE
Feat(eos_designs): Relax requirement of node-specific configuration

### PR DESCRIPTION
**Pull request by ClausHolbechArista**
## Change Summary

Relax requirement of node-specific configuration

## Component(s) name

`arista.avd.eos_designs`

## Proposed changes

Currently all nodes must be defined under `nodes`. Ex for a l3leaf:
```
l3leaf:
  nodes:
    MY-L3LEAF-123:
      id: 123
      mgmt_ip: 10.20.30.40/24
```
or
```
l3leaf:
  node_groups:
    MY_NODE_GROUP:
      nodes:
        MY-L3LEAF-123:
          id: 123
          mgmt_ip: 10.20.30.40/24
```

With this PR we relax this requirement, so all the node vars can be set on any level. Ex.
```
l3leaf:
  defaults:
    id: 123
    mgmt_ip: 10.20.30.40/24
```

This is useful when the inventory is using in-line jinja or if the inventory is created from external scripts/roles setting host_vars per device.
Ex:
```
l3leaf:
  defaults:
    id: {{ inventory_hostname | split('-') | last }}
    mgmt_ip: {{ lookup('my_ipam', inventory_hostname, 'mgmt_ip') }}
```

## How to test

Moved topology vars defined in hostvars to `defaults` for one host. Failed before this change, but is accepted with no changes to output.

### User Checklist

- N/A

### Repository Checklist

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [x] My change requires a change to the documentation and documentation have been updated accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

### CODE REVIEW

**Review by gmuloc — COMMENTED** [review]
Probably need to change the documentation as well to reflect the new possibility:

https://github.com/aristanetworks/ansible-avd/blob/devel/ansible_collections/arista/avd/roles/eos_designs/doc/fabric-topology.md?plain=1#L126

Also we could end up with multiple devices with the same `id` which could lead to some similar IPs being generated down the line -not sure if we could raise an error in that case though.

**Comment by ClausHolbechArista** [comment]
> Probably need to change the documentation as well to reflect the new possibility:
> 
> https://github.com/aristanetworks/ansible-avd/blob/devel/ansible_collections/arista/avd/roles/eos_designs/doc/fabric-topology.md?plain=1#L126
> 
> Also we could end up with multiple devices with the same `id` which could lead to some similar IPs being generated down the line -not sure if we could raise an error in that case though.

Most users would still use it per device, and above the section we state:
```
All node types have the same structure based on `defaults`, `node_group`, `node` and all variables can be defined in any section and support inheritance like this:
```

**Review by gmuloc — APPROVED** [review]
LGTM

**Review by emilarista — APPROVED** [review]
LGTM

**Pull request merged**
