### PR TITLE
Feat(dhcp_provisioner): Adding support for automatic dict_to_list conversion in ztp_configuration template

### LINKED ISSUE #3002: Please support list-of-dicts node_groups and node lists in dhcp_provisioner
### Enhancement summary

From previous dict-of-dicts inputs, manually converting node_groups and/or nodes into a list results in them being omitted from ztp_configuration.yml, empty clients list then triggers an iteration error in arista.cvp.dhcp_configuration due to empty clients

### Which component of AVD is impacted

dhcp_provisioner

### Use case example

Function parity between using dict-of-dicts and list-of-dicts for input data in avd v4.x

### Describe the solution you would like

After going through the process of converting our input data to the new data model in AVD, we'd like to be able to use the provisioner to generate our ZTP configuration on avd v4.x

### Describe alternatives you have considered
We tested a quick modification of the jinja template to work only for lists, and we were able to generate an identical ztp_configuration and dhcpd.conf to before. We've decided to revert our changes to l3leaf and spine node_types for now to work with the available dhcp_provisioner
```
diff --git a/ansible_collections/arista/avd/roles/dhcp_provisioner/templates/ztp_configuration.j2 b/ansible_collections/arista/avd/roles/dhcp_provisioner/templates/ztp_configuration.j2
index 4a281d533..1b85a4651 100644
--- a/ansible_collections/arista/avd/roles/dhcp_provisioner/templates/ztp_configuration.j2
+++ b/ansible_collections/arista/avd/roles/dhcp_provisioner/templates/ztp_configuration.j2
@@ -63,20 +63,20 @@ ztp:
     # {{ node_type }}
 {# For NODE GROUPS entries #}
 {%     for node_group in node_types[node_type]['node_groups'] | arista.avd.natural_sort %}
-{%         for node in node_types[node_type]['node_groups'][node_group]['nodes'] | arista.avd.natural_sort %}
-{%             if node_types[node_type]['node_groups'][node_group]['nodes'][node].mac_address is arista.avd.defined %}
-    - name: {{ node }}
-      mac: '{{ node_types[node_type]['node_groups'][node_group]['nodes'][node].mac_address }}'
-      ip4: {{ node_types[node_type]['node_groups'][node_group]['nodes'][node].mgmt_ip | ansible.utils.ipaddr('address') }}
+{%         for node in node_group.nodes | arista.avd.natural_sort %}
+{%             if node.mac_address is arista.avd.defined %}
+    - name: {{ node.name }}
+      mac: '{{ node.mac_address }}'
+      ip4: {{ node.mgmt_ip | ansible.utils.ipaddr('address') }}
 {%             endif %}
 {%         endfor %}
 {%     endfor %}
 {# For NODES List #}
 {%     for node in node_types[node_type]['nodes'] | arista.avd.natural_sort %}
-{%         if node_types[node_type]['nodes'][node].mac_address is arista.avd.defined %}
-    - name: {{ node }}
-      mac: '{{ node_types[node_type]['nodes'][node].mac_address }}'
-      ip4: {{ node_types[node_type]['nodes'][node].mgmt_ip | ansible.utils.ipaddr('address') }}
+{%         if node.mac_address is arista.avd.defined %}
+    - name: {{ node.name }}
+      mac: '{{ node.mac_address }}'
+      ip4: {{ node.mgmt_ip | ansible.utils.ipaddr('address') }}
 {%         endif %}
 {%     endfor %}
 {% endfor %}
 ```

### Additional context

ztp_configuration.yml with list-of-dicts node_groups/nodes
```
---
ztp:
  default:
    registration: http://10.x.x.x/ztp/bootstrap
    gateway: 10.x.x.x
    nameservers:
      - 10.x.x.x
      - 10.x.x.x
    use_system_mac: true
  general:
    subnets:
      - network: 10.x.x.x
        netmask: 255.255.255.0
        gateway: 10.x.x.x
        nameservers:
          - 10.x.x.x
          - 10.x.x.x
        lease_time: 100
  clients:
    # l3leaf
    # spine
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by ghost**
## Change Summary

Adding support for automatic dict_to_list conversion in ztp_configuration template

## Related Issue(s)

Fixes #3002 

## Component(s) name

`arista.avd.dhcp_provisioner`

### User Checklist

- N/A

### Repository Checklist

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [x] My change requires a change to the documentation and documentation have been updated accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

### CODE REVIEW

**Review by tgodaA — APPROVED** [review]
LGTM

**Review by gmuloc — COMMENTED** [review]
@Shivani-chourasiya - any chance we can add a test to make sure this does not break in either case

**Comment by Shivani-chourasiya** [comment]
> @Shivani-chourasiya - any chance we can add a test to make sure this does not break in either case

Sure

**Comment by Shivani-chourasiya** [comment]
> @Shivani-chourasiya - any chance we can add a test to make sure this does not break in either case

Added!

**Review by carlbuchmann — APPROVED** [review]
LGTM

**Review by ClausHolbechArista — APPROVED** [review]

**Pull request merged**
