### PR TITLE
Removes unneeded neighbours in IPv4 and EVPN AFs

### LINKED ISSUE #373: MPBGP remove AVD default of no neighbor for peers/peer groups in AF
**Issue Type**

- Template enhancement

**Is your feature request related to a problem? Please describe.**
Checking the EOS CLI standard behaviour and AVD there is redundant knobs for MPBGP where we explicitly disable peers/peer groups that are not meant to be part of the particular address-family.

By default with MPBGP we will not negotiate capability for any address-family that the peer is not defined, thus there is no need for us to explicitly do this so.

AVD

```
   address-family evpn
      neighbor EVPN-OVERLAY-PEERS activate
      no neighbor IPv4-UNDERLAY-PEERS activate
      no neighbor MLAG-IPv4-UNDERLAY-PEER activate
   !
   address-family ipv4
      no neighbor EVPN-OVERLAY-PEERS activate
      neighbor IPv4-UNDERLAY-PEERS activate
      neighbor MLAG-IPv4-UNDERLAY-PEER activate

```
**Describe the solution you'd like**

The following  provides the exact same result

```
PE1(config)#show run sec bgp
router bgp 1
   no bgp default ipv4-unicast
   neighbor EVPN peer group
   neighbor EVPN remote-as 2
   neighbor EVPN send-community
   neighbor EVPN maximum-routes 12000
   neighbor IP peer group
   neighbor IP remote-as 2
   neighbor IP update-source Loopback0
   neighbor IP ebgp-multihop 2
   neighbor IP maximum-routes 12000
   neighbor 2.2.2.2 peer group IP
   neighbor 10.0.0.1 peer group EVPN
   !
   address-family evpn
      bgp next-hop-unchanged
      neighbor EVPN activate
   !
   address-family ipv4
      bgp next-hop-unchanged
      neighbor IP activate
```
```
PE1(config)#show ip bgp summ
BGP summary information for VRF default
Router identifier 10.0.0.0, local AS number 1
Neighbor Status Codes: m - Under maintenance
  Neighbor         V  AS           MsgRcvd   MsgSent  InQ OutQ  Up/Down State   PfxRcd PfxAcc
  2.2.2.2          4  2                  7         7    0    0 00:02:43 Estab   0      0
```
```
PE1(config)#show bgp evpn summ
BGP summary information for VRF default
Router identifier 10.0.0.0, local AS number 1
Neighbor Status Codes: m - Under maintenance
  Neighbor         V  AS           MsgRcvd   MsgSent  InQ OutQ  Up/Down State   PfxRcd PfxAcc
  10.0.0.1         4  2                 24        23    0    0 00:05:52 Estab   0      0
```
```
IPv4Neighbor Capabilities:
    Multiprotocol IPv4 Unicast: advertised and received and negotiated
    Four Octet ASN: advertised and received and negotiated
    Route Refresh: advertised and received and negotiated
    Enhanced route refresh: advertised and received and negotiated
    Send End-of-RIB messages: advertised and received and negotiated
    Additional-paths recv capability:
      IPv4 Unicast: advertised
    Additional-paths send capability:
      IPv4 Unicast: received
```
```
EVPNNeighbor Capabilities:
    Multiprotocol IPv4 Unicast: advertised and received and negotiated
    Four Octet ASN: advertised and received and negotiated
    Route Refresh: advertised and received and negotiated
    Enhanced route refresh: advertised and received and negotiated
    Send End-of-RIB messages: advertised and received and negotiated
    Additional-paths recv capability:
      IPv4 Unicast: advertised
    Additional-paths send capability:
      IPv4 Unicast: received
```

**Describe alternatives you've considered**

It's liveable but the more address-families we have the more no neighbours we will have which in the end the result is simpler with the above.

**Additional context**

### PR DESCRIPTION
**Pull request by onurgashi**
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes)
- [ ] Documentation content changes
- [ ] Other (please describe):

## Related Issue(s)

Fixes #373 

## How to test

Tested in the lab with configuration generated from AVD.

```
Leaf#router bgp
   !
   address-family evpn
      neighbor EVPN-OVERLAY-PEERS activate
   !
   address-family ipv4
      neighbor IPv4-UNDERLAY-PEERS activate
      neighbor MLAG-IPv4-UNDERLAY-PEER activate

Spine#router bgp
   !
   address-family evpn
      neighbor EVPN-OVERLAY-PEERS activate
   !
   address-family ipv4
      neighbor IPv4-UNDERLAY-PEERS activate
```

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://www.avd.sh/docs/contributing/) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed ([`pre-commit`](https://www.avd.sh/docs/installation/development/#python-virtual-environment), `make linting` and `make sanity-lint`).
- [ ] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly

### CODE REVIEW

**Comment by onurgashi** [comment]
I can rewrite this using the latest devel i required.

**Comment by onurgashi** [comment]
Can you guys weigh in on this, so shall we keep this as it is or remove the explicit no neighbor commands?

@ClausHolbechArista @ankudinov

**Comment by ClausHolbechArista** [comment]
> Can you guys weigh in on this, so shall we keep this as it is or remove the explicit no neighbor commands?
> 
> @ClausHolbechArista @ankudinov
@carlbuchmann 
I actually like the current behavior with the few extra lines. It is very clear which peer-group is used for what.

**Comment by ClausHolbechArista** [comment]
We will keep the extra peer-groups under IPv4 and EVPN AFs for now. Closing this PR.

**Pull request closed without merging**
