### PR TITLE
CI: Fix incorrect key in eos_cli_config_gen/ip-routing-fib scenario

### PR DESCRIPTION
**Pull request by ghost**
## Change Summary

Fix incorrect key in eos_cli_config_gen/ip-routing-fib scenario.

`ipv6_routing` -> `ipv6_unicast_routing`

## How to test

See new molecule scenario output.

### Repository Checklist

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [x] My change requires a change to the documentation and documentation have been updated accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

### CODE REVIEW

**Review by ClausHolbechArista — APPROVED** [review]

**Review by ClausHolbechArista — DISMISSED** [review]

**Review by gmuloc — DISMISSED** [review]
LGTM

**Review by carlbuchmann — CHANGES_REQUESTED** [review]
ipv6_routing is not a root key.
This PR needs to change to remove incorrect key in Molecule scenarios

**Review by carlbuchmann — APPROVED** [review]
LGTM!
I scanned all molecule scenarios and only found this incorrect key in the one scenario changed.

**Comment by Shivani-chourasiya** [comment]
> LGTM! I scanned all molecule scenarios and only found this incorrect key in the one scenario changed.

Thanks @carlbuchmann

**Review by ClausHolbechArista — APPROVED** [review]

**Pull request merged**
