### PR TITLE
fixes development docker volume mounting issue on Centos8

### LINKED ISSUE #341: Development docker container does not start correctly on Centos8
## Issue Type

- Bug Report

## Summary

After installing the environment from the one liner the docker container will not start on Centos8 as it states it is unable to mount the webdoc cvp/avd volumes due "volume name is too short, names must be at least two alphanumeric characters"

## Role or Module Name

docker-compose.yml

## OS / Environment
```shell
[miles@wsc8miless arista-ansible]$ docker --version
Docker version 19.03.13, build 4484c46d9d
[miles@wsc8miless arista-ansible]$ docker-compose --version
docker-compose version 1.27.4, build 40524192
[miles@wsc8miless arista-ansible]$ 
```

## Steps to reproduce

Run the avd one liner and then run container on a fresh install CentOS 8 after installing docker+docker-compose.

### Expected results

```shell
docker-compose -f ansible-avd/development/docker-compose.yml up -d
WARNING: The PWD variable is not set. Defaulting to a blank string.
ansible_avd is up-to-date
Creating webdoc_cvp ... done
Creating webdoc_avd ... done
---------------
 INFORMATION
---------------
 * Webserver for AVD: http://127.0.0.1:8000
 * Webserver for CVP: http://127.0.0.1:8001
 * Ansible shell: make dev-run
---------------
docker-compose -f ansible-avd/development/docker-compose.yml exec ansible zsh
Agent pid 57
➜  /projects 
```

### Actual results

```shell
docker-compose -f ansible-avd/development/docker-compose.yml up -d
WARNING: The PWD variable is not set. Defaulting to a blank string.
Creating webdoc_avd ... 
Creating webdoc_cvp ... 
Creating webdoc_cvp ... error
Creating webdoc_avd ... error
ERROR: for webdoc_cvp  Cannot create container for service webdoc_cvp: create .: volume name is too short, names should be at least two alphanumeric characters

ERROR: for webdoc_avd  Cannot create container for service webdoc_avd: create .: volume name is too short, names should be at least two alphanumeric characters

ERROR: for webdoc_cvp  Cannot create container for service webdoc_cvp: create .: volume name is too short, names should be at least two alphanumeric characters

ERROR: for webdoc_avd  Cannot create container for service webdoc_avd: create .: volume name is too short, names should be at least two alphanumeric characters
```

### Fix

Within the docker-compose.yml file edit the volumes to include a trailing slash after ${PWD}

```yaml
volumes:
      - ${PWD}/:/docs
```

### PR DESCRIPTION
**Pull request by MilesTails**
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Documentation content changes
- [ ] Other (please describe):

## Related Issue(s)

Fixes #341 

## Proposed changes

Applied trailing slash to volume paths in docker-compose.yml

## How to test

Run docker container on Centos8

## Checklist:

- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly
- [x] I have read the [**CONTRIBUTING**](https://www.avd.sh/docs/contributing/) document.
- [x] All new and existing tests passed ([`pre-commit`](https://www.avd.sh/docs/installation/development/#python-virtual-environment), `make linting` and `make sanity-lint`).

### CODE REVIEW

**Review by carlbuchmann — APPROVED** [review]
LGTM - Tested on Centos 7.

**Comment by carlbuchmann** [comment]
@MilesTails thanks for this PR and adding support for Centos 8!
@titom73 , please test with your dev workflow!

**Comment by titom73** [comment]
@MilesTails : Thanks for your issue and PR about this one.
@carlbuchmann : Will bring up a Centos 8 VM to validate shortly.

**Review by titom73 — APPROVED** [review]
Looks good to me

Tested sucessfully:

```shell
diff --git a/development/docker-compose.yml b/development/docker-compose.yml
index 0cd2eec..b6155ca 100644
--- a/development/docker-compose.yml
+++ b/development/docker-compose.yml
@@ -11,7 +11,7 @@ services:
     image: titom73/mkdocs:latest
     container_name: webdoc_cvp
     volumes:
-      - ${PWD}:/docs
+      - ${PWD}/:/docs
     ports:
       - 8001:8000
     entrypoint: ""
@@ -21,7 +21,7 @@ services:
     image: titom73/mkdocs:latest
     container_name: webdoc_avd
     volumes:
-      - ${PWD}:/docs
+      - ${PWD}/:/docs
     ports:
       - 8000:8000
     entrypoint: ""
[tom@centos8 ansible-avd]$ cd ../
[tom@centos8 arista-ansible]$ make start
docker-compose -f ansible-avd/development/docker-compose.yml up -d
Starting webdoc_cvp ...
Starting webdoc_cvp ... done
Starting webdoc_avd ... done
---------------
 INFORMATION
---------------
 * Webserver for AVD: http://127.0.0.1:8000
 * Webserver for CVP: http://127.0.0.1:8001
 * Ansible shell: make dev-run
---------------
docker-compose -f ansible-avd/development/docker-compose.yml exec ansible zsh
Agent pid 84
➜  /projects
```

**Pull request merged**
