### PR TITLE
Implement list support for device_filter in eos_config_deploy_cvp

### LINKED ISSUE #506: device_filter list for arista.avd.eos_config_deploy_cvp
## Issue Type

- Bug Report

## Summary

The device_filter for arista.avd.eos_config_deploy_cvp is just accepting one string but not multiple values to filter more exactly.

## Role or Module Name
arista.avd.eos_config_deploy_cvp

## Steps to reproduce

```yaml
---
- name: Build Switch configuration
  hosts: DC1_FABRIC
  connection: local
  gather_facts: no

  tasks:

    - name: include global_vars
      tags: [build, provision]
      include_vars: "{{ item }}"
      with_items:
        - "../global_vars/DC_LAB.yml"
        - "../global_vars/EOS.yml"

    - name: generate intented variables
      tags: [build]
      import_role:
         name: arista.avd.eos_l3ls_evpn

    - name: generate intented DCI variables
      tags: [build, provision]
      import_role:
         name: eos_dci

    - name: generate device intended config and documention
      tags: [build]
      import_role:
         name: arista.avd.eos_cli_config_gen

- name: Configuration deployment with CVP
  hosts: CVP-1
  connection: local
  gather_facts: no

  tasks:

#    - name: upload cvp configlets
#      import_role:
#          name: arista.avd.cvp_configlet_upload
#      vars:
#        configlets_cvp_prefix: 'RS'
#        configlet_directory: "{{inventory_dir}}/configlets"

    - name: run CVP provisioning
      import_role:
         name: arista.avd.eos_config_deploy_cvp
      vars:
        container_root: 'DC_FABRIC'
        configlets_prefix: 'DC1'
        device_filter: 
           -  '-2'
           - '-11E'
           - '-11F2-002'
        state: present
```

### Expected results

```shell
$
```

### Actual results

```shell
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: 'in <string>' requires string as left operand, not list
fatal: [CVP-1]: FAILED! => changed=false
  module_stderr: |-
    Traceback (most recent call last):
      File "/root/.ansible/tmp/ansible-local-8240ng56gaxc/ansible-tmp-1608200817.7264671-215226164940173/AnsiballZ_inventory_to_container.py", line 102, in <module>
        _ansiballz_main()
      File "/root/.ansible/tmp/ansible-local-8240ng56gaxc/ansible-tmp-1608200817.7264671-215226164940173/AnsiballZ_inventory_to_container.py", line 94, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "/root/.ansible/tmp/ansible-local-8240ng56gaxc/ansible-tmp-1608200817.7264671-215226164940173/AnsiballZ_inventory_to_container.py", line 40, in invoke_module
        runpy.run_module(mod_name='ansible_collections.arista.avd.plugins.modules.inventory_to_container', init_globals=None, run_name='__main__', alter_sys=True)
      File "/usr/local/lib/python3.6/runpy.py", line 205, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
      File "/usr/local/lib/python3.6/runpy.py", line 96, in _run_module_code
        mod_name, mod_spec, pkg_name, script_name)
      File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "/tmp/ansible_arista.avd.inventory_to_container_payload_pue9y6rf/ansible_arista.avd.inventory_to_container_payload.zip/ansible_collections/arista/avd/plugins/modules/inventory_to_container.py", line 421, in <module>
      File "/tmp/ansible_arista.avd.inventory_to_container_payload_pue9y6rf/ansible_arista.avd.inventory_to_container_payload.zip/ansible_collections/arista/avd/plugins/modules/inventory_to_container.py", line 404, in main
      File "/tmp/ansible_arista.avd.inventory_to_container_payload_pue9y6rf/ansible_arista.avd.inventory_to_container_payload.zip/ansible_collections/arista/avd/plugins/modules/inventory_to_container.py", line 367, in get_containers
      File "/tmp/ansible_arista.avd.inventory_to_container_payload_pue9y6rf/ansible_arista.avd.inventory_to_container_payload.zip/ansible_collections/arista/avd/plugins/modules/inventory_to_container.py", line 320, in get_devices
      File "/tmp/ansible_arista.avd.inventory_to_container_payload_pue9y6rf/ansible_arista.avd.inventory_to_container_payload.zip/ansible_collections/arista/avd/plugins/modules/inventory_to_container.py", line 320, in get_devices
      File "/tmp/ansible_arista.avd.inventory_to_container_payload_pue9y6rf/ansible_arista.avd.inventory_to_container_payload.zip/ansible_collections/arista/avd/plugins/modules/inventory_to_container.py", line 320, in get_devices
      [Previous line repeated 2 more times]
     File "/tmp/ansible_arista.avd.inventory_to_container_payload_pue9y6rf/ansible_arista.avd.inventory_to_container_payload.zip/ansible_collections/arista/avd/plugins/modules/inventory_to_container.py", line 311, in get_devices
      File "/tmp/ansible_arista.avd.inventory_to_container_payload_pue9y6rf/ansible_arista.avd.inventory_to_container_payload.zip/ansible_collections/arista/avd/plugins/modules/inventory_to_container.py", line 145, in is_in_filter
      File "/tmp/ansible_arista.avd.inventory_to_container_payload_pue9y6rf/ansible_arista.avd.inventory_to_container_payload.zip/ansible_collections/arista/avd/plugins/modules/inventory_to_container.py", line 145, in <genexpr>
    TypeError: 'in <string>' requires string as left operand, not list
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1

<!--- Paste verbatim command output between quotes below -->
```

### PR DESCRIPTION
**Pull request by titom73**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Documentation content changes
- [ ] Other (please describe):

## Related Issue(s)

Fixes issue #506

## Component(s) name

`arista.avd.eos_config_deploy_cvp`

## Proposed changes

- Create a conditional execution to run inventory_to_container using
either a string or a list of string.
- Update CV configuration template to support both type of device_filter

Role now supports following options:

- device_filter using a string

```yaml
tasks:
  - name: run CVP provisioning
    import_role:
        name: eos_config_deploy_cvp
    vars:
      container_root: 'DC1_FABRIC'
      configlets_prefix: 'DC1-AVD'
      device_filter: 'DC1'
      state: present
      execute_tasks: false
```

- device_filter using a list of string:

```yaml
tasks:
  - name: run CVP provisioning
    import_role:
        name: eos_config_deploy_cvp
    vars:
      container_root: 'DC1_FABRIC'
      configlets_prefix: 'DC1-AVD'
      device_filter:
        - 'DC1'
        - 'DC2'
      state: present
      execute_tasks: false
```

## Checklist:

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://www.avd.sh/docs/contributing/) document.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly
- [x] All new and existing tests passed ([`pre-commit`](https://www.avd.sh/docs/installation/development/#python-virtual-environment), `make linting` and `make sanity-lint`).

### CODE REVIEW

**Comment by kmueller68** [comment]
Hello @titom73 

I have tested this right now in my lab environment and it is exactly doing what I have been looking for. :-)

Thank you very much.

**Comment by guillaumeVilar** [comment]
Hello, I tested this PR and I get an error from the ansible-cvp side: 
```
TASK [eos_config_deploy_cvp : Refreshing facts from CVP cv_server.] ******************************************************************************************************************************************************
ok: [cv_server]

TASK [eos_config_deploy_cvp : Configure devices on cv_server] ************************************************************************************************************************************************************
fatal: [cv_server]: FAILED! => changed=false 
  module_stderr: |-
    /Users/guillaumevilar/Documents/avd-test/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host '10.83.12.71'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
      warnings.warn(
    Traceback (most recent call last):
      File "/Users/guillaumevilar/.ansible/tmp/ansible-local-71731b69vz4sz/ansible-tmp-1611998887.894351-108528069341386/AnsiballZ_cv_device.py", line 102, in <module>
        _ansiballz_main()
      File "/Users/guillaumevilar/.ansible/tmp/ansible-local-71731b69vz4sz/ansible-tmp-1611998887.894351-108528069341386/AnsiballZ_cv_device.py", line 94, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "/Users/guillaumevilar/.ansible/tmp/ansible-local-71731b69vz4sz/ansible-tmp-1611998887.894351-108528069341386/AnsiballZ_cv_device.py", line 40, in invoke_module
        runpy.run_module(mod_name='ansible_collections.arista.cvp.plugins.modules.cv_device', init_globals=None, run_name='__main__', alter_sys=True)
      File "/usr/local/Cellar/python@3.9/3.9.1_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 210, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
      File "/usr/local/Cellar/python@3.9/3.9.1_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 97, in _run_module_code
        _run_code(code, mod_globals, init_globals,
      File "/usr/local/Cellar/python@3.9/3.9.1_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "/var/folders/hd/3g0v07bx6vd9n3tn3ztkc5900000gn/T/ansible_arista.cvp.cv_device_payload_hkvparwt/ansible_arista.cvp.cv_device_payload.zip/ansible_collections/arista/cvp/plugins/modules/cv_device.py", line 1185, in <module>
      File "/var/folders/hd/3g0v07bx6vd9n3tn3ztkc5900000gn/T/ansible_arista.cvp.cv_device_payload_hkvparwt/ansible_arista.cvp.cv_device_payload.zip/ansible_collections/arista/cvp/plugins/modules/cv_device.py", line 1180, in main
      File "/var/folders/hd/3g0v07bx6vd9n3tn3ztkc5900000gn/T/ansible_arista.cvp.cv_device_payload_hkvparwt/ansible_arista.cvp.cv_device_payload.zip/ansible_collections/arista/cvp/plugins/modules/cv_device.py", line 1103, in devices_action
      File "/var/folders/hd/3g0v07bx6vd9n3tn3ztkc5900000gn/T/ansible_arista.cvp.cv_device_payload_hkvparwt/ansible_arista.cvp.cv_device_payload.zip/ansible_collections/arista/cvp/plugins/modules/cv_device.py", line 566, in devices_new
      File "/var/folders/hd/3g0v07bx6vd9n3tn3ztkc5900000gn/T/ansible_arista.cvp.cv_device_payload_hkvparwt/ansible_arista.cvp.cv_device_payload.zip/ansible_collections/arista/cvp/plugins/modules/cv_device.py", line 458, in build_new_devices_list
      File "/var/folders/hd/3g0v07bx6vd9n3tn3ztkc5900000gn/T/ansible_arista.cvp.cv_device_payload_hkvparwt/ansible_arista.cvp.cv_device_payload.zip/ansible_collections/arista/cvp/plugins/module_utils/tools.py", line 191, in is_in_filter
      File "/var/folders/hd/3g0v07bx6vd9n3tn3ztkc5900000gn/T/ansible_arista.cvp.cv_device_payload_hkvparwt/ansible_arista.cvp.cv_device_payload.zip/ansible_collections/arista/cvp/plugins/module_utils/tools.py", line 191, in <genexpr>
    TypeError: 'in <string>' requires string as left operand, not list
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1
```

Indeed, the filter variables looks like this: 
```
2021-01-30 09:28:09,337 - arista.cvp.tools: DEBUG - func: is_in_filter (L:182) -  * is_in_filter - filter is [['DC1', 'DC2']]
2021-01-30 09:28:09,337 - arista.cvp.tools: DEBUG - func: is_in_filter (L:183) -  * is_in_filter - hostname is DC1-SPINE1

```
And the tool function (ansible_collections/arista/cvp/plugins/module_utils/tools.py) looks like this: 
```
   LOGGER.debug(" * is_in_filter - filter is %s", str(hostname_filter))
    LOGGER.debug(" * is_in_filter - hostname is %s", str(hostname))

    # W102 Workaround to avoid list as default value.
    if hostname_filter is None:
        hostname_filter = ["all"]

    if "all" in hostname_filter:
        return True
    elif any(element in hostname for element in hostname_filter):       <<<<<<<<<<<< error comes from here
        return True
    LOGGER.debug(" * is_in_filter - NOT matched")
    return False
```

So I guess we would need to update as well this function in the ansible-cvp side. 

Should we open an issue on the ansible-cvp side in order to support this as well?

**Comment by titom73** [comment]
> Hello, I tested this PR and I get an error from the ansible-cvp side:
> 
> ```
> TASK [eos_config_deploy_cvp : Refreshing facts from CVP cv_server.] ******************************************************************************************************************************************************
> ok: [cv_server]
> 
> TASK [eos_config_deploy_cvp : Configure devices on cv_server] ************************************************************************************************************************************************************
> fatal: [cv_server]: FAILED! => changed=false 
>   module_stderr: |-
>     /Users/guillaumevilar/Documents/avd-test/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host '10.83.12.71'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
>       warnings.warn(
>     Traceback (most recent call last):
>       File "/Users/guillaumevilar/.ansible/tmp/ansible-local-71731b69vz4sz/ansible-tmp-1611998887.894351-108528069341386/AnsiballZ_cv_device.py", line 102, in <module>
>         _ansiballz_main()
>       File "/Users/guillaumevilar/.ansible/tmp/ansible-local-71731b69vz4sz/ansible-tmp-1611998887.894351-108528069341386/AnsiballZ_cv_device.py", line 94, in _ansiballz_main
>         invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
>       File "/Users/guillaumevilar/.ansible/tmp/ansible-local-71731b69vz4sz/ansible-tmp-1611998887.894351-108528069341386/AnsiballZ_cv_device.py", line 40, in invoke_module
>         runpy.run_module(mod_name='ansible_collections.arista.cvp.plugins.modules.cv_device', init_globals=None, run_name='__main__', alter_sys=True)
>       File "/usr/local/Cellar/python@3.9/3.9.1_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 210, in run_module
>         return _run_module_code(code, init_globals, run_name, mod_spec)
>       File "/usr/local/Cellar/python@3.9/3.9.1_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 97, in _run_module_code
>         _run_code(code, mod_globals, init_globals,
>       File "/usr/local/Cellar/python@3.9/3.9.1_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
>         exec(code, run_globals)
>       File "/var/folders/hd/3g0v07bx6vd9n3tn3ztkc5900000gn/T/ansible_arista.cvp.cv_device_payload_hkvparwt/ansible_arista.cvp.cv_device_payload.zip/ansible_collections/arista/cvp/plugins/modules/cv_device.py", line 1185, in <module>
>       File "/var/folders/hd/3g0v07bx6vd9n3tn3ztkc5900000gn/T/ansible_arista.cvp.cv_device_payload_hkvparwt/ansible_arista.cvp.cv_device_payload.zip/ansible_collections/arista/cvp/plugins/modules/cv_device.py", line 1180, in main
>       File "/var/folders/hd/3g0v07bx6vd9n3tn3ztkc5900000gn/T/ansible_arista.cvp.cv_device_payload_hkvparwt/ansible_arista.cvp.cv_device_payload.zip/ansible_collections/arista/cvp/plugins/modules/cv_device.py", line 1103, in devices_action
>       File "/var/folders/hd/3g0v07bx6vd9n3tn3ztkc5900000gn/T/ansible_arista.cvp.cv_device_payload_hkvparwt/ansible_arista.cvp.cv_device_payload.zip/ansible_collections/arista/cvp/plugins/modules/cv_device.py", line 566, in devices_new
>       File "/var/folders/hd/3g0v07bx6vd9n3tn3ztkc5900000gn/T/ansible_arista.cvp.cv_device_payload_hkvparwt/ansible_arista.cvp.cv_device_payload.zip/ansible_collections/arista/cvp/plugins/modules/cv_device.py", line 458, in build_new_devices_list
>       File "/var/folders/hd/3g0v07bx6vd9n3tn3ztkc5900000gn/T/ansible_arista.cvp.cv_device_payload_hkvparwt/ansible_arista.cvp.cv_device_payload.zip/ansible_collections/arista/cvp/plugins/module_utils/tools.py", line 191, in is_in_filter
>       File "/var/folders/hd/3g0v07bx6vd9n3tn3ztkc5900000gn/T/ansible_arista.cvp.cv_device_payload_hkvparwt/ansible_arista.cvp.cv_device_payload.zip/ansible_collections/arista/cvp/plugins/module_utils/tools.py", line 191, in <genexpr>
>     TypeError: 'in <string>' requires string as left operand, not list
>   module_stdout: ''
>   msg: |-
>     MODULE FAILURE
>     See stdout/stderr for the exact error
>   rc: 1
> ```
> 
> Indeed, the filter variables looks like this:
> 
> ```
> 2021-01-30 09:28:09,337 - arista.cvp.tools: DEBUG - func: is_in_filter (L:182) -  * is_in_filter - filter is [['DC1', 'DC2']]
> 2021-01-30 09:28:09,337 - arista.cvp.tools: DEBUG - func: is_in_filter (L:183) -  * is_in_filter - hostname is DC1-SPINE1
> ```
> 
> And the tool function (ansible_collections/arista/cvp/plugins/module_utils/tools.py) looks like this:
> 
> ```
>    LOGGER.debug(" * is_in_filter - filter is %s", str(hostname_filter))
>     LOGGER.debug(" * is_in_filter - hostname is %s", str(hostname))
> 
>     # W102 Workaround to avoid list as default value.
>     if hostname_filter is None:
>         hostname_filter = ["all"]
> 
>     if "all" in hostname_filter:
>         return True
>     elif any(element in hostname for element in hostname_filter):       <<<<<<<<<<<< error comes from here
>         return True
>     LOGGER.debug(" * is_in_filter - NOT matched")
>     return False
> ```
> 
> So I guess we would need to update as well this function in the ansible-cvp side.
> 
> Should we open an issue on the ansible-cvp side in order to support this as well?

Could you please retry with latest version of that branch ?
I have fixed cv_device execution to use either `string` or `list` as device_fitler and for both state `present` and `absent`

**Comment by guillaumeVilar** [comment]
Hello, 

I just tested it and it works like a charm! 
Thank you! 

Just a small thing, I saw that in the Molecule scenario **eos_config_deploy_cvp_list**, the converge playbook is using the format like: device_filter: ['DC1', 'DC2']. 
Shouldn't we use the following format in this scenario? 
```
device_filter: 
  - 'DC1'
  - 'DC2'
 ```

Full converge file: 
```
---
- name: Configure local folders
  hosts: DC1_FABRIC
  gather_facts: false
  connection: local
  vars:
    root_dir: '{{playbook_dir}}'
  tasks:
    - name: generate intented variables
      import_role:
        name: arista.avd.eos_l3ls_evpn
    - name: generate device intended config and documention
      import_role:
        name: arista.avd.eos_cli_config_gen

- name: Converge
  hosts: cv_server
  gather_facts: false
  connection: local
  vars:
    root_dir: '{{playbook_dir}}'
  tasks:
    - name: run CVP provisioning
      tags: generate
      import_role:
        name: arista.avd.eos_config_deploy_cvp
      vars:
        container_root: 'DC1_FABRIC'
        configlets_prefix: 'AVD'
        device_filter: ['DC1', 'DC2']
        execute_tasks: false
        state: present
       ```
 
Thanks

**Comment by titom73** [comment]
Well, it is actually the same, just a matter of how to represent list: https://docs.ansible.com/ansible/latest/reference_appendices/YAMLSyntax.html

Thanks for the report

**Comment by guillaumeVilar** [comment]
Got it, thanks.

**Review by noredistribution — COMMENTED** [review]
Tested this on both CVaaS and CV on-prem and worked fine!

**Pull request merged**
