### PR TITLE
Use directory vars in all tasks

### LINKED ISSUE #814: Provide capability to leverage eos_cli_config_gen to generate simple configlets
**Issue Type**

- [x] Template enhancement
- [ ] Role enhancement
- [ ] Documentation enhancement (avd.sh)

Currently, when leveraging eos_cli_config_gen, some default data is generated, which prevents you from using the role in the case of generating simple configlets.  There should be knobs to enable/disable this data from being generated.

```eos
!RANCID-CONTENT-TYPE: arista
!
transceiver qsfp default-mode 4x10G
!
hostname {{ inventory_hostname }}
```

Additionally, knobs should be provided to:
- Set the intended configuration path.
- Set documentation generation path.
- Knob to enable/disable documentation generation.

### LINKED ISSUE #991: fabric documentation directory mismatch (build_output_folders vs eos_designs roles)
## Issue Type

- [x] Bug Report

## Summary

fabric documentation directory mismatch (`build_output_folders` vs `eos_designs roles`)

- build_output_folders uses: 
```
# Fabric documentation
fabric_dir_name: 'fabric'
fabric_dir: '{{ documentation_dir }}/{{ fabric_dir_name }}'
```

- eos_designs uses: 
```
    - name: Generate fabric documentation in Markdown Format.
      template:
        src: fabric-documentation.j2
        dest: "{{ root_dir }}/documentation/fabric/{{ fabric_name }}-documentation.md"
        mode: 0664
      changed_when: false
```

By default, it works (both roles will use the same dir .i.e `documentation/fabric`)  

But if you change the value of the variable `fabric_dir_name` then the directory `documentation/fabric/` wont be created by the role `build_output_folders` and  the task `Generate fabric documentation in Markdown Format` of `eos_designs` role will fail

## Component Name

build_output_folders  and eos_designs roles

## Steps to reproduce

But if you change the value of the variable `fabric_dir_name` if a playbook or in a variable file, then the directory `documentation/fabric/` wont be created by the role `build_output_folders` and  the task `Generate fabric documentation in Markdown Format` of `eos_designs` role will fail

### Expected results

both build_output_folders  and eos_designs roles should use the same directory   
we will use `documentation/fabric/`

### PR DESCRIPTION
**Pull request by ClausHolbechArista**
## Change Summary
Use directory vars in all tasks

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes)
- [ ] Documentation content changes
- [ ] Other (please describe):

## Related Issue(s)

Fixes #991 
Part of fix for #814

## Component(s) name

`arista.avd`

## Proposed changes

Replaced static directory names with variables and added default values to each role.

Data model change:
From
```yaml
# Output for structured YAML files for CVP:
structured_cvp_name: 'cvp'
structured_cvp: '{{ structured_dir }}/{{ structured_cvp_name }}'
```

To
```yaml
# Output for structured YAML files for CVP:
structured_cvp_dir_name: 'cvp'
structured_cvp_dir: '{{ structured_dir }}/{{ structured_cvp_dir_name }}'
```

## How to test

No changes in molecule. Hope CI also works :)

## Checklist:

- [ ] My code has been rebased from devel before I start
- [ ] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contributing/) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly
- [ ] All new and existing tests passed ([`pre-commit`](https://www.avd.sh/docs/installation/development/#python-virtual-environment), `make linting` and `make sanity-lint`).

### CODE REVIEW

**Comment by ClausHolbechArista** [comment]
@ksator @carlbuchmann please review this one.

**Comment by emilotep** [comment]
Looks good to me. LGTM!

**Review by titom73 — APPROVED** [review]
LGTM!

We should state that some variables are not used anymore and can change customer's logic until new variables are used.

**Comment by ClausHolbechArista** [comment]
Thank @titom73 , the only change is this, so I added to PR description, so we can use it in release-notes.
Should we postpone this one to 3.0 since it has this change?

Data model change:
From

```yaml
# Output for structured YAML files for CVP:
structured_cvp_name: 'cvp'
structured_cvp: '{{ structured_dir }}/{{ structured_cvp_name }}'
```
To

```yaml
# Output for structured YAML files for CVP:
structured_cvp_dir_name: 'cvp'
structured_cvp_dir: '{{ structured_dir }}/{{ structured_cvp_dir_name }}'
```

**Pull request merged**
