### PR TITLE
feauture(eos_designs/eos_cli_config_gen):RFC5549

### PR DESCRIPTION
**Pull request by carlbuchmann**
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes)
- [x] Documentation content changes
- [ ] Other (please describe):

## Component(s) name

`arista.avd.eos_designs`
`eos_cli_config_gen`

## Proposed changes

- Add support for rfc5549.
- Refactor eos_cli_config_gen router_bgp documentation template.
- Fix issue with router_general leak routes.
- Add description to bgp peers in eos_designs.

## How to test

See molecule scenario `evpn_underlay_rfc5549_overlay_ebgp` and testing performed by @mpergament .

## Checklist:

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://www.avd.sh/docs/contributing/) document.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly
- [x] All new and existing tests passed ([`pre-commit`](https://www.avd.sh/docs/installation/development/#python-virtual-environment), `make linting` and `make sanity-lint`).

### CODE REVIEW

**Review by mpergament — APPROVED** [review]
Tested on ATD as well. LGTM

**Review by titom73 — APPROVED** [review]
LGTM!

**Review by mpergament — APPROVED** [review]
LGTM

**Comment by titom73** [comment]
Waiting for a commit to fix `ip routing ipv6 interfaces` documentation

**Pull request merged**
