### PR TITLE
Add EVPN ESI Support for Active/Active server connections

### LINKED ISSUE #215: Add ESI support eos_l3ls_evpn role
**Issue Type**

- [x] Template enhancement
- [x] Role enhancement

**Describe the solution you'd like**

At the moment MLAG peers are configured automatically via AVD - Are there any plans for a workflow to configure BGP EVPN based standard multihoming as well? At the moment I am using a kind of workaround where I configure these Peers as standalone peers via AVD and add the EVPN Ethernet identifier later on via a Configlet. I am just interested in whether you are working on an AVD based automation for this use case also?

**Configuration Example**

```
interface Port-Channel100   
   switchport trunk allowed vlan 10, 20
   switchport mode trunk   
   !   
    evpn ethernet-segment      
      identifier 0000:0000:0001:0411:1111      
      route-target import 00:00:00:00:01:04   
    lacp system-id 0000.0001.0411
```

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

### PR DESCRIPTION
**Pull request by titom73**
## Description

Add initial support for EVPN ESI support for port configuration. This PR covers following actions:

- Capture inputs from SERVERS.YML
- Generate a structured_configuration for LEAF devices.
- Generate CLI configuration

### EOS L3LS EVPN

Input for `eos_l3ls_evpn`

```yaml
servers:
  server01_ESI:
    rack: RackA
    adapters:
      - type: nic
        server_ports: [Eth0, Eth1]
        switch_ports: [Ethernet7, Ethernet7]
        switches: [DC1-LEAF1A, DC1-LEAF1B]
        port_channel:
          state: present
          description: data
          mode: active
          esi: 0303:0202:0101
        profile: ALL
```

### EOS CLI Config GEN

Input for `eos_cli_config_gen`

```yaml
### Port-Channel Interfaces ###
port_channel_interfaces:
  Port-Channel7:
    description: server01_ESI_data
    vlans: 1-4093
    mode: trunk
    esi: 000:000:0303:0202:0101
    rt: 03:03:02:02:01:01
    lacp_id: 0303.0202.0101
```

### Generated EOS configuration

```
interface Port-Channel100   
   switchport trunk allowed vlan 10, 20
   switchport mode trunk   
   !   
    evpn ethernet-segment      
      identifier 000:000:0303:0202:0101     
      route-target import 03:03:02:02:01:01
    lacp system-id 0303.0202.0101
```

## Question in progress

- [x] Define a mechanism to generate RT for ESI.
- [x] Add support to generate automatically LACP `system-id`

```
- Input ESI: `0303:0202:0101`
- Final ESI format: `000:000:0303:0202:0101`
- LACP-ID: `0303.0202.0101`
- RT: `03:03:02:02:01:01`
```

## Todo List

- [x] Update eos_l3ls_evpn.
- [x] Update eos_cli_config_gen.
- [x] Update Roles documentation.
- [x] Update CI to add ESI in testing.

### CODE REVIEW

**Comment by titom73** [comment]
Add logics to generate RT and LACP-ID

While ESI needs 3 different IDs to run, this commit implements logic to
generate LACP ID and RT based on ESI

Example:

- Input ESI: `0303:0202:0101`
- Final ESI format: `000:000:0303:0202:0101`
- LACP-ID: `0303.0202.0101`
- RT: `03:03:02:02:01:01`

**Comment by titom73** [comment]
Known caveat: ESI configured on MLAG devices seems to not work with vEOS-LAB 4.24.0F

Ready for internal review and testing.

**Comment by titom73** [comment]
PR Review Todo list:
---------------------

- [x] Rename input ESI to `short_esi` (update documentation as well)
- [x] Apply a custom filter to transform short_esi to lacp_id

**Comment by titom73** [comment]
Problem spotted:

- short_esi: 0303:0202:0101
- rt: 03:03::0:20:2::01:01

**Review by carlbuchmann — APPROVED** [review]
LGTM - reviewed with @titom73 and tested with validation lab

**Pull request merged**
