### PR TITLE
Feat(eos_designs, eos_cli_config_gen): Add "disabled" option to "local_users"

### LINKED ISSUE #2254: Disable username admin
### Enhancement summary

It is common to disable the admin username. In my case I create and use other default admin accounts.

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

Need to render the following command:

`no username admin `

### Describe the solution you would like

A way to do this in the users data model:

```yaml
local_users:
  < user_1 >:
    disabled: true
``` 

### Describe alternatives you have considered

I currently use the eos_cli key to do it and it gets rendered at the end of the config. For some reason CVP doesn't like it in some cases.

### Additional context

_No response_

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by ClausHolbechArista**
## Change Summary

Add "disabled" option to "local_users"

## Related Issue(s)

Fixes #2254

## Component(s) name

`arista.avd.eos_designs`
`arista.avd.eos_cli_config_gen`

## Proposed changes

```
local_users:
  < user_1 >:
    <...>
    # If "disabled" is true, the user will be removed and all other settings are ignored.
    # Useful for removing the default "admin" user.
    disabled: < true | false >
```

## How to test

Added test to molecule for both roles..

### User Checklist

- N/A

### Repository Checklist

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [x] My change requires a change to the documentation and documentation have been updated accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

### CODE REVIEW

**Comment by gusmb** [comment]
I also opened PR for this #2257 
I was considering using a more standard key status=present|absent to determine the status of the user.
For the moment I added present=true|false -> default -> true... Maybe just easier to keep it as "disabled" key

**Comment by ClausHolbechArista** [comment]
> I also opened PR for this #2257 I was considering using a more standard key status=present|absent to determine the status of the user. For the moment I added present=true|false -> default -> true... Maybe just easier to keep it as "disabled" key

Ah I did not know if you would implement it yourself. I would prefer to keep either an `enabled` or `disabled` key to be more consistent with AVD data models. I am aware it is not the same as Ansible's `state: <absent | present>` but those are also more used directly as role arguments.
I can be convinced either way to `enabled` with default `true` or `disabled`. Please note that we need to add this to `eos_designs` as well and also add to the new schemas.

I will let you decide if you want to continue with #2257 or otherwise feel free to adjust #2256.

**Comment by gusmb** [comment]
> > I also opened PR for this #2257 I was considering using a more standard key status=present|absent to determine the status of the user. For the moment I added present=true|false -> default -> true... Maybe just easier to keep it as "disabled" key
> 
> Ah I did not know if you would implement it yourself. I would prefer to keep either an `enabled` or `disabled` key to be more consistent with AVD data models. I am aware it is not the same as Ansible's `state: <absent | present>` but those are also more used directly as role arguments. I can be convinced either way to `enabled` with default `true` or `disabled`. Please note that we need to add this to `eos_designs` as well and also add to the new schemas.
> 
> I will let you decide if you want to continue with #2257 or otherwise feel free to adjust #2256.

I'm fine to keep #2257 , should be ready now (using disabled key). Also adjusted documentation to show this information on the table of users.

PR checks are failing but not sure why

**Review by tgodaA — APPROVED** [review]
LGTM

**Comment by ClausHolbechArista** [comment]
duplicate of 2257

**Pull request closed without merging**
