### PR TITLE
Fix(eos_cli_config_gen): Fix typo in router-bgp.j2

### LINKED ISSUE #2752: Unable to disable bfd for BGP neighbor
### Issue Summary

When attempting to disable BFD for a BGP neighbor, the playbook failed to generate a config:

```
fatal: [DC-BL-01A -> localhost]: FAILED! => 
  msg: '''neighbo'' is undefined'
fatal: [DC-BL-01B -> localhost]: FAILED! => 
  msg: '''neighbo'' is undefined'
```

I found the typo in the router-bgp.j2 template when the value for bfd is defined as false. 

### Which component(s) of AVD impacted

eos_designs, eos_cli_config_gen

### How do you run AVD ?

Ansible CLI with AVD Runner

### Steps to reproduce

```shell
Create the following configuration under bgp_peers:

bgp_peers:
          172.17.0.254:
             remote_as: 4207000200
             description: Firewall
             nodes: ['DC-BL-01A', 'DC-BL-01B']
             bfd: false
             peer_group: TENANT-IPv4-PEER
```

Run the arista-avd ansible-playbook.
```


### Relevant log output


fatal: [DC-BL-01A -> localhost]: FAILED! => 
  msg: '''neighbo'' is undefined'
fatal: [DC-BL-01B -> localhost]: FAILED! => 
  msg: '''neighbo'' is undefined'



### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by adietrich-ussignal**
## Change Summary

Fixes a typo in the router-bgp.j2 template of eos_cli_config_gen to resolve issues when bfd is set to False under the neighbor configuration. 

## Related Issue(s)

Fixes #2752 

## Component(s) name

`arista.avd.eos_cli_config_gen`

## Proposed changes
Revise {{ neighbo.ip_address }} to {{ neighbor.ip_address }} 

## How to test
Added both BFD True and False use cases to test tenant configurations in the 'evpn_underlay_ebgp_overlay_ebgp' molecule  within the bgp_peers configuration section. 

### User Checklist

- N/A

### Repository Checklist

- [X] My code has been rebased from devel before I start
- [X] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [X] My change requires a change to the documentation and documentation have been updated accordingly.
- [X] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

### CODE REVIEW

**Review by gmuloc — COMMENTED** [review]
Thanks a lot @adietrich-ussignal for catching this and submitting a PR to fix it!

Could you please add the test for `bfd: false` in the `eos_designs_unit_test` scenario - if you have a look in TenantA, `bfd: true` is being tested already: https://github.com/aristanetworks/ansible-avd/blob/devel/ansible_collections/arista/avd/molecule/eos_designs_unit_tests/inventory/group_vars/DC1_TENANTS_NETWORKS/Tenant_A.yml#L179

Thanks in advance!

**Comment by gmuloc** [comment]
@carlbuchmann - we will need to cherry-pick this for 3.8.x

**Comment by adietrich-ussignal** [comment]
@gmuloc I've added the additional test as requested.

**Comment by gmuloc** [comment]
> @gmuloc I've added the additional test as requested.

Thanks @adietrich-ussignal - my apologies for not being more clear in my comment - my intention was to move the test to `eos_designs_unit_tests` and remove it from the other scenario. Let me know if you want to remove it or I can take care of it.

thanks!

**Comment by adietrich-ussignal** [comment]
@gmuloc  I believe I cleaned the right tests up this time. Thanks for the clarification!

**Review by gmuloc — APPROVED** [review]
LGTM - thanks for the contribution

**Comment by carlbuchmann** [comment]
@adietrich-ussignal - while reviewing with @gmuloc we noticed another behavior at the cli that required fixing:

- `no neighbor {{ neighbor.ip_address }} bfd` should only be generated when that device is also defined in a peer_group. This was verified at the CLI with EOS version 4.29.3M.
- This needed fixing in both the vrf and within the default context.

We also moved all testing to `eos_cli_config_gen` unit tests.

**Review by carlbuchmann — APPROVED** [review]
LGTM

**Pull request merged**
