### PR TITLE
eos_designs(feature): Add support for custom `structured_config` on various `eos_designs` objects

### PR DESCRIPTION
**Pull request by ClausHolbechArista**
## Change Summary

Add support for custom `structured_config` on various `eos_designs` objects.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes)
- [x] Documentation content changes
- [ ] Other (please describe):

## Related Issue(s)

Fixes #<ISSUE ID>

## Component(s) name

`arista.avd.eos_designs`

## Proposed changes

These changes enables the user to supply `structured_config` on various levels in the `eos_designs` data model.
The user can override builtin functionality or add extra knobs to be picked up by `eos_cli_config_gen`.

### Connected Endpoints (a.k.a. "servers")
All relevant `structured_config` sections will be merged.
```yaml
< connected_endpoints_keys.key >:
  < endpoint_1 >:
    adapters:
      - <...>
        # Custom structured config added under ethernet_interfaces.<interface> for eos_cli_config_gen
        structured_config: < dictionary >
        port_channel:
          # Custom structured config added under port_channel_interfaces.<interface> for eos_cli_config_gen
          structured_config: < dictionary >
```

### Fabric Topology
Only the most specific `structured_config` key will be used
```yaml
< spine | super-spine | overlay_controller >:
  defaults:
    # Custom structured config for eos_cli_config_gen
    structured_config: < dictionary >
  nodes:
      # Custom structured config for eos_cli_config_gen
      structured_config: < dictionary >

< l3leaf | l2leaf >:
  defaults:
    # Custom structured config for eos_cli_config_gen
    structured_config: < dictionary >
  node_groups:
      # Custom structured config for eos_cli_config_gen
      structured_config: < dictionary >
      nodes:
        < node >:
          # Custom structured config for eos_cli_config_gen
          # Overrides the setting on node_group level.
          structured_config: < dictionary >
```

### Network Services (a.k.a. "tenants")
All relevant `structured_config` sections will be merged. Note that setting `structured_config` under `svi.nodes` will override the setting on `svi`.
```yaml
tenants:
  vrfs:
    < vrf >:
        # Custom structured config for eos_cli_config_gen
        structured_config: < dictionary >
        bgp:
          # Custom structured config added under router_bgp.vrfs.<vrf> for eos_cli_config_gen
          structured_config: < dictionary >
        svis:
          < vlan >:
            # Custom structured config added under vlan_interfaces.<interface> for eos_cli_config_gen
            structured_config: < dictionary >
            nodes:
              < node >:
                # Custom structured config added under vlan_interfaces.<interface> for eos_cli_config_gen
                # Overrides the setting on SVI level.
                structured_config: < dictionary >
```

Existing `custom_structured_configuration_` behavior is maintained but the templates have been refactored a bit.

All `structured_config` knobs honor the `list_merge` strategy set in `custom_structured_configuration_list_merge`

## How to test

Added molecule tests for all variants.

## Checklist:

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://www.avd.sh/docs/contributing/) document.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly
- [x] All new and existing tests passed ([`pre-commit`](https://www.avd.sh/docs/installation/development/#python-virtual-environment), `make linting` and `make sanity-lint`).

### CODE REVIEW

**Comment by ryanmerolle** [comment]
@ClausHolbechArista I currently set group_vars for config items not set by eos_designs (for example multicast specific) and I add new dictionaries using custom_structured_config to append to eos_design defined items like route-maps, vlans, SVIs, and etc.  

But this model seems to only work well when appending new dictionaries and not when updating existing dictionaries.  Example take an existing `peer_type: spine` interface defined under ethernet_interfaces and only adding pim to it.

Does your PR address this sort of limitation in extending an defined eos_design model?

**Comment by ClausHolbechArista** [comment]
I am not sure i follow the issue. I have been patching existing dicts as well as creating new in several customer deployments without a problem.
Can you please try to reproduce with minimal config and submit an issue? Thanks

**Comment by ryanmerolle** [comment]
Only because you inquired, an example variable / use is documented in #1002. It uses a single variable where I want to add pim to spine & l3leaf peer uplinks.  I can discuss on the network to code slack if you like also.  All other config vars can use the test from molecule for a 5 stage clos.

I'm not try to pull you into this as @titom73 and @carlbuchmann are already engaged.  I was just asking because again it was not clear to me how this changed the current approach.

**Comment by shabazz-abdulrahman1** [comment]
Hi @ClausHolbechArista , I have been engaging with @titom73  and @carlbuchmann on a similar feature / issue closely linked with this PR https://github.com/aristanetworks/ansible-avd/issues/942  and @titom73  suggested I add my comment here for your review.

I want to add VLAN access list to the VLANs defined below:
```yaml
---
# PARIS-LAB Tenants Networks
# Documentation of Tenant specific information - Vlans/VRFs
tenants:
  # Tenant QH Specific Information - VRFs / VLANs
  Tenant_QH:
    mac_vrf_vni_base: 10000
    vrfs:
      QH-PARIS-LAB-FEEDOS-OVERLAY:
        vrf_vni: 18
        svis:
          727:
            vni_override: 10727
            name: PARIS-LAB-FEEDOS-OVERLAY
            tags: [ FEEDOS-OVERLAY ]
            enabled: true
            ip_address_virtual: 10.1.31.1/24

```
 such that I can get something like this generated in the  **intended/config**  :
```
!
interface Ethernet1
 description CUC
!
ip access-list acl-client-vlan727-in
permit icmp any any
permit tcp any any
permit udp any any
!
interface Vlan727
ip access-group acl-client-vlan727-in in
!
```
at the moment it seems **ip access-group** is not yet supported according to @titom73  and he suggested to add my comment here and also advised I could do something like this in our **fabric vars**  to implement 'standard IP Access_list:
```
custom_structured_configuration_standard_access_lists:
  < access_list_name_1 >:
    sequence_numbers:
      < sequence_id_1 >:
        action: "< action as string >"
      < sequence_id_2 >:
        action: "< action as string >"
  < access_list_name_2 >:
    sequence_numbers:
      < sequence_id_1 >:
        action: "< action as string >"

```
I have a yml implementation of a sample access list added to the **TENANTS_NETWORKS.yml**  thus:

```yaml
---
# PARIS-LAB Tenants Networks
# Documentation of Tenant specific information - Vlans/VRFs
tenants:
  # Tenant QH Specific Information - VRFs / VLANs
  Tenant_QH:
    mac_vrf_vni_base: 10000
    vrfs:
      QH-PARIS-LAB-FEEDOS-OVERLAY:
        vrf_vni: 18
        svis:
          727:
            vni_override: 10727
            name: PARIS-LAB-FEEDOS-OVERLAY
            tags: [ FEEDOS-OVERLAY ]
            enabled: true
            ip_address_virtual: 10.1.31.1/24
            ip-access-list-vlan727-in:
              sequence_numbers:
                10:
                  action: "remark ACL to restrict access to switch int 727 to CVP and Ansible"
                20:
                  action: "permit host 10.10.10.10"
                30:
                  action: "permit host 10.10.10.11"
                40:
                  action: "permit host 10.10.10.12"
```
but when I ran this in container (our dev env) with tags -- build to generate the **intended config**, I don't see the changes in the device  **intended configs** generated.

will be nice to have this feature (**ip access-group**)  supported so that we can apply the access lists created. 

Also please advise , if there is something that I am missing why I can't see the effects of the  yaml configs I made  in the **intended/config**
I actually shared my example yaml  with @titom73  last week and he said "you're implementation seems logic" and he further adviced that I put my comments here for @ClausHolbechArista  and @carlbuchmann  to review.
I would like to know:
* if the ip access-group support will be added in this PR
* where to place the yaml configuration for implementing the Standard Ip Access_list.
Thanks

**Comment by ClausHolbechArista** [comment]
@shabazz-abdulrahman1 I tested out your usecase using this branch:
In my tenants I added this:
image

And the resulting config got changed as expected:
image
image

BUT it created the ACL on all devices even if they don't have an SVI (l2leaf) or if they don't have _this_ SVI, since the ACL is created on VRF level. So it is not optimal, but maybe it can still be used if you combine with `custom_structured_configuration` to create the ACL on the relevant leafs and apply them on SVI using this.

That said, you are still welcome to submitting an issue (feature request) describing what you would like. I like the idea you have with the ACL being defined directly under the SVI from an abstraction standpoint, but it will not scale well with larger ACLs. We normally recommend to reuse the same ACLs to optimize usage of platform TCAM resources.

**Review by carlbuchmann — APPROVED** [review]
LGTM!

**Pull request merged**
