### PR TITLE
Feat(eos_cli_config_gen,eos_designs): Add support for setting multiple secondary virtual IP addresses for vlans

### LINKED ISSUE #1170: Support for ip address virtual secondary addresses
### Issue Summary

Documentation suggests this can be configured via svi_profiles:
https://avd.sh/en/releases-v3.x.x/roles/eos_designs/doc/l3ls-evpn/network-services.html

However the following did not work:
```
svi_profiles:
  45secondary:
    ip_address_virtual_secondary: 10.10.40.1/24  

          svis:
            45:
              name: V45-T-UTIL-IDMZ-HSBC-APP-BACK-FW
              tags: [VH_UTIL_IDMZ]
              enabled: true
              ip_address_virtual: 10.10.30.1/24
              profile: 45secondary   

```
structured_configs file looks good:
```
  Vlan45:
    tenant: T_UTIL_USVHI3W6
    tags:
    - VH_UTIL_IDMZ
    description: V45-T-UTIL-IDMZ-HSBC-APP-BACK-FW
    shutdown: false
    vrf: VRF-UTIL-IDMZ-USVHI3W6
    ip_address_virtual: 10.10.30.1/24
    ip_address_virtual_secondary: 10.10.40.1/24
```

But config generated misses the secondary address:
```
	interface Vlan45
	   description V45-T-UTIL-IDMZ-HSBC-APP-BACK-FW
	   no shutdown
	   vrf VRF-UTIL-IDMZ-USVHI3W6
	   ip address virtual 10.10.30.1/24

```

In addition to this, it would be better if we support directly configuring the ip address virtual secondary under the SVI instead.

### Which component(s) of AVD impacted

eos_designs

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Steps to reproduce

```shell
Define an SVI profile with an ip address virtual secondary and apply it to an SVI.
```

### Relevant log output

_No response_

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by tgodaA**
The ”ip address virtual” command is specific to a VXLAN routing deployment and is used to conserve IP address space. Only one secondary virtual address is being supported by AVD which could have been multiple secondary IPs.

- Changes made: Under tenants.vrfs[vrf].svis[svi], ip_address_virtual_secondary is modified to ip_address_virtual_secondaries which is a list.
- This key can be used either in svi_profiles or in the above mentioned path.

## Change Summary

`arista.avd.eos_designs, arista.avd.eos_cli_config_gen`
- Affected roles: eos_designs, eos_cli_config_gen. The vlan-interfaces.j2 is modified in both of the roles.
- eos_designs template path: ansible-avd/ansible_collections/arista/avd/roles/eos_designs/templates/designs/l3ls-evpn/tenants/vlan-interfaces.j2. Existing snippet is modified.
- eos_cli_config_gen template path: ansible-avd/ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/eos/vlan-interfaces.j2. New snippet is added.

Support for multiple secondary virtual IPs for the SVIs.
## Related Issue(s)

Fixes #1170

## Component(s) name
arista.avd.eos_designs, arista.avd.eos_cli_config_gen

## Proposed changes

tenants.vrfs[<vrf>].svis[<svi>].ip_address_virtual_secondary is modified to tenants.vrfs[<vrf>].svis[<svi>].ip_address_virtual_secondaries which is a list.

- eos_designs: ip_address_virtual_secondary can hold only 1 virtual secondary IP and this variable is changed to ip_address_virtual_secondaries and it's value is a list of IPv4 IPs to support multiple IPs.
- eos_cli_config_gen: There is no configuration to generate ip_address_virtual_secondaries, which is added.
- Data model changed: ip_address_virtual_secondary : <ipv4>     changed to ip_address_virtual_secondaries : [ <list of ipv4 IPs> ]

## How to test

group_vars/DC1_TENANTS_NETWORKS.yml:

```
tenants:
  # Tenant A Specific Information - VRFs / VLANs
  Tenant_A:
    vrfs:
      Tenant_A_OP_Zone:
        vrf_vni: 10
        vtep_diagnostic:
          loopback: 100
          loopback_ip_range: 10.254.1.0/24
        svis:
          12:
            name: Tenant_A_OP_Zone_Test
            tags: [opzone]
            enabled: true
            ip_address_virtual: <ipv4/mask>
            ip_address_virtual_secondaries: [<ipv4/mask>, <ipv4/mask>] 
```

Used docker environment (downloaded as suggested in avd.sh docs and then updated avd to latest), python version = 3.6.14.
I created an example and then tested the modified AVD. Then checked the intended configuration, which actually generated the configuration as required. 

### User Checklist

- N/A

### Repository Checklist

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [ ] My change requires a change to the documentation and documentation have been updated accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

### CODE REVIEW

**Review by carlbuchmann — CHANGES_REQUESTED** [review]
@tgodaA Thanks for this PR, please also add test to `ansible-avd/ansible_collections/arista/avd/molecule/eos_designs_unit_tests`

**Comment by ClausHolbechArista** [comment]
@tgodaA Looking good. Please remember to update `README.md` for `eos_cli_config_gen` role and `network-services.md` for `eos_designs`. Also add test coverage (molecule) for `eos_cli_config_gen`. Reach out if you need assistance.

**Review by titom73 — APPROVED** [review]
LGTM! Thanks for contributing

- [x] Unit tests updated
- [x] Documentation updated

**Review by ClausHolbechArista — COMMENTED** [review]
This is a breaking change since we remove the old knob. We should add it to the `eos_designs` upgrade role.

**Review by carlbuchmann — DISMISSED** [review]
Since there is a data model change we also need to update the release notes:
`/docs/release-notes/3.x.x.md`

**Comment by tgodaA** [comment]
Should I make changes to upgrade_tools role as well as this is labelled "data model change"?

**Comment by ClausHolbechArista** [comment]
> Should I make changes to upgrade_tools role as well as this is labelled "data model change"?

It seems like this was never implemented properly in `eos_cli_config_gen`, so even though it was setting the variable in `eos_designs`, no config was rendered by `eos_cli_config_gen`.
Because it is not in a working state today, I will remove the data model change again, and you don't have to include in upgrade role. @carlbuchmann agree?

**Review by ClausHolbechArista — APPROVED** [review]
LGTM! Thank you for this contribution.

**Review by titom73 — APPROVED** [review]
LGTM!

**Pull request merged**
