### PR TITLE
Feat(eos_cli_config_gen): EOS feature parity for queue_monitor_streaming

### LINKED ISSUE #1286: Feature request: queue-monitor streaming missing features in eos_cli_config_gen
### Enhancement summary

queue-monitor streaming is missing features:

- ip access-group <access list>
- ipv6 access-group <access list>
- max-connections <1-100>

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

EOS feature parity

### Describe the solution you would like

Build out the functions.

### Describe alternatives you have considered

Do not enable EOS feature parity

### Additional context

_No response_

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by ryanmerolle**
## Change Summary

queue-monitor streaming missing features in eos_cli_config_gen

## Related Issue(s)

Fixes #1286

## Component(s) name

`arista.avd.eos_cli_config_gen`

## Proposed changes

Added:
- ip access-group <access list>
- ipv6 access-group <access list>
- max-connections <1-100>

Added/updated Molecule Tests (never had a test)

## How to test

See README & molecule test

### User Checklist

- N/A

### Repository Checklist

- [X] My code has been rebased from devel before I start
- [X] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [X] My change requires a change to the documentation and documentation have been updated accordingly.
- [X] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

### CODE REVIEW

**Comment by tgodaA** [comment]
Please modify the PR title. It should be one of the following: Feat, Fix, Doc.

**Comment by ryanmerolle** [comment]
I am confused as to why the test is failing since it passes on my local development.

**Comment by tgodaA** [comment]
Can you add Feat(eos_cli_config_gen): xxx, in your commit message (instead of ==> EOS feature parity for queue_monitor_streaming)

**Comment by ClausHolbechArista** [comment]
> I am confused as to why the test is failing since it passes on my local development.

You had an extra file left over from renaming the molecule host name. I deleted it and I expect it to pass now.

Thank you for your continued contributions.

**Review by ClausHolbechArista — APPROVED** [review]
LGTM

**Comment by ryanmerolle** [comment]
> > I am confused as to why the test is failing since it passes on my local development.
> 
> You had an extra file left over from renaming the molecule host name. I deleted it and I expect it to pass now.
> 
> Thank you for your continued contributions.

thanks for looking and addressing.

**Comment by tgodaA** [comment]
Because this is a Feat, I guess this should be added to release-notes/3.x.x.md. Any comments from other reviewers?

**Review by tgodaA — APPROVED** [review]
LGTM!

**Pull request merged**
