### PR TITLE
Feat(eos_designs): Add ntp_settings

### PR DESCRIPTION
**Pull request by ClausHolbechArista**
## Change Summary

Add ntp_settings

## Related Issue(s)

Fixes #

## Component(s) name

`arista.avd.eos_designs`

## Proposed changes

```
ntp_settings:
  server_vrf: <str>
  servers:
    - name: <str>
      burst: <bool>
      iburst: <bool>
      key: <int>
      maxpoll: <int>
      minpoll: <int>
      version: <int>
  authenticate: <bool>
  authenticate_servers_only: <bool>
  authentication_keys:
    - id: <int>
      hash_algorithm: <str>
      key: <str>
      key_type: <str>
  trusted_keys: <str>
```

## How to test

- Added molecule test
- Updated existing molecule scenarios and examples which were using the `eos_cli_config_gen` model.

### User Checklist

- N/A

### Repository Checklist

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [x] My change requires a change to the documentation and documentation have been updated accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

### CODE REVIEW

**Comment by pvinci-arista** [comment]
Should we add a key for something like `ntp_serve_all: <bool>`?

**Comment by ClausHolbechArista** [comment]
> Should we add a key for something like `ntp_serve_all: <bool>`?

This is for eos_designs, and I mapped everything from eos_cli_config_gen. Once we get more features in, we can add them here as well.

**Review by philippebureau — APPROVED** [review]
Tested
LGTM

**Review by carlbuchmann — APPROVED** [review]
LGTM

**Pull request merged**
