### PR TITLE
Feat(eos_designs): deprecate port_channel.short_esi under connected endpoints

### PR DESCRIPTION
**Pull request by mayurgs34**
## Related Issue(s)

Fixes #<ISSUE ID>

## Component(s) name

`arista.avd.<role-name>`

### User Checklist

- N/A

### Repository Checklist

- [ ] My code has been rebased from devel before I start
- [ ] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [ ] My change requires a change to the documentation and documentation have been updated accordingly.
- [ ] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

### CODE REVIEW

**Comment by gmuloc** [comment]
is it the same as https://github.com/aristanetworks/ansible-avd/pull/2443 ?

**Comment by mayurgs34** [comment]
> is it the same as #2443 ?

Hi, PR #2443 is used for eos_cli_config_gen adding deprecation warning and #2526 is for removing port_channel.short_esi in eos_designs. https://github.com/aristanetworks/avd-internal/issues/86

**Comment by gmuloc** [comment]
> > is it the same as #2443 ?
> 
> Hi, PR #2443 is used for eos_cli_config_gen adding deprecation warning and #2526 is for removing port_channel.short_esi in eos_designs. [aristanetworks/avd-internal#86](https://github.com/aristanetworks/avd-internal/issues/86)

Indeed! apologies read too fast the PR title!

**Comment by mayurgs34** [comment]
> Collaborator

no problem...

**Comment by ClausHolbechArista** [comment]
This should only be a deprecation and not a removal. It is probably simpler to start fresh since we have done a lot of changes in eos_designs.

**Pull request closed without merging**
