### PR TITLE
Feat(eos_designs)!: Update the default platform settings for R3-series to have TCAM profile "vxlan-routing"

### PR DESCRIPTION
**Pull request by ClausHolbechArista**
## Change Summary

Update the default platform settings for R3-series to have TCAM profile "vxlan-routing"

## Related Issue(s)

Replacing #3901

## Component(s) name

`arista.avd.eos_designs`

### The default platform settings for R3-series now have the TCAM profile "vxlan-routing"

Starting AVD 5.0.0, the default platform settings for `7280R3`, `7500R3` and `7800R3` platforms now contain `tcam_profile: vxlan-routing`
This change is based on a new Arista best practice for VXLAN deployments with the R3-series.
Not using this TCAM profile can lead to incorrect handling of VXLAN IPv6 NS packets.

!!! warning
    Since applying a TCAM profile will cause reprogramming of the forwarding processor, it can lead to disturbances to the network services.

    Please work with your Arista account team to decide if the new default is the right choice for your network, and how to apply it.

To retain the old configuration with no TCAM profile the default platform settings can be overridden with the new `custom_platform_settings` key:

```diff
+custom_platform_settings:
+  - platforms:
+      - 7280R3
+    reload_delay:
+      mlag: 900
+      non_mlag: 1020
+  - platforms:
+      - 7500R3
+      - 7800R3
+    management_interface: Management0
+    reload_delay:
+      mlag: 900
+      non_mlag: 1020
```

## How to test

- Existing molecule tests expose the change of defaults.
- Updated one of them to test the suggested roll-back from porting guide.

### User Checklist

- N/A

### Repository Checklist

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [x] My change requires a change to the documentation and documentation have been updated accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

### CODE REVIEW

**Comment by ClausHolbechArista** [comment]
@fhibler please take a look. Especially at the porting-guide section since we need to guide existing users.
https://ansible-avd--4387.org.readthedocs.build/en/4387/docs/porting-guides/5.x.x.html#the-default-platform-settings-for-r3-series-now-have-the-tcam-profile-vxlan-routing

**Review by gmuloc — APPROVED** [review]
PR looks good

**Review by JulioPDX — APPROVED** [review]
LGTM, Thank you

**Comment by pmprado** [comment]
The tech-library is recommending to use the `vxlan-v6-underlay` TCAM profile now. Should we review this?

**Pull request merged**
