### PR TITLE
Add explicit no shutdown and switchport config

### PR DESCRIPTION
**Pull request by ClausHolbechArista**
## Change Summary

In `eos_cli_config_gen`: Ensure that configurations for `no shutdown` and `switchport` are rendered explicitly
In `eos_l3ls_evpn`: Explicitly set `shutdown: false` and `type: switched` instead of relying on expected defaults

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Documentation content changes
- [ ] Other (please describe):

## Component(s) name
eos_cli_config_gen
eos_l3ls_evpn

### Shutdown
* If `shutdown: false` we _now_ render `no shutdown`
* If `shutdown: true` we _still_ render `shutdown`
* If `shutdown is not defined` we _still_ don't render anything.

This will enable future support for flipping the EOS default to shutdown, protecting unconfigured ports.

### Switchport
* If `type: routed` we _still_ render `no switchport`
* If `type: switched` we _now_ render `switchport`
* If `type is not defined` we _now_ render `switchport`

This will enable future support for flipping the EOS default to `no switchport`, protecting unconfigured ports.

## How to test

Tested port-channels, members, switchports, routed ports, shutdown, no shutdown combinations.

Test result here:
https://github.com/ClausHolbechArista/claus-l3ls-dev/commit/39f715e132639b775069c001dc04131b3225dbf5
and after updating l3ls with explicit `shutdown:false` and `type: switched` where applicable:
https://github.com/ClausHolbechArista/claus-l3ls-dev/commit/a4d8f5907a9348baf71dc75df4d5cca9e1a4c1ac

## Checklist:

- [ ] I have read the [**CONTRIBUTING**](https://www.avd.sh/docs/contributing/) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed ([`pre-commit`](https://www.avd.sh/docs/installation/development/#python-virtual-environment), `make linting` and `make sanity-lint`).
- [ ] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly

### CODE REVIEW

**Comment by ClausHolbechArista** [comment]
Working on new CI artifacts...

**Review by titom73 — APPROVED** [review]
Looks good to me.

Idempotency is still working even if `switchport` is not displayed in configuration running on EOS.

**Comment by ClausHolbechArista** [comment]
@titom73 I am updating CI again with the latest l3ls changes.

**Review by titom73 — APPROVED** [review]
Looks good and after running a full l3ls_evpn playbook, the configuration remains idempotent while the generated configuration is explicit.

**Pull request merged**
