### PR TITLE
Fix(eos_cli_config_gen): Prevent empty source and dest ports list for ip access lists

### LINKED ISSUE #4642: Documentation enhancement for ip-extended-access-lists schema
### Enhancement summary

The documentation for [ip-extended-access-lists](https://avd.arista.com/4.10/roles/eos_cli_config_gen/docs/input-variables.html#ip-extended-access-lists), specifically the source_ports_match and destination_ports_match fields should mention the dependency on source_ports and destination ports field respectively. 

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

In my use case I am generating these input variable schema from my model data. I then supply the input schema to [pyavd utility ](https://github.com/aristanetworks/avd/blob/devel/python-avd/pyavd/get_device_config.py)that helps me generate eos cli.

While I was implementing the mapping from my data to these structured configs I was providing all the fields that i had in my data model, eg: sequence number, action, protocol, source, destination and so forth. In this I was also providing source_ports/destination ports which were sometimes empty lists. But because I included the "source_ports" key and a respective empty value, avd while generating eos config added the source_ports_match with a default value of "eq" which is incorrect cause that results to a config like 

`80 permit udp any eq `

where eq is followed by no source ports.

I then corrected my logic to add "source_ports" key only when source ports exist so that source_ports_match does not get added by default.

### Describe the solution you would like

The documentation could explicitly mention that source_ports_match key gets added with a default value when source_ports key is found, and if you do not want that then do not add the source_ports key itself when source_ports are empty (cause technically adding empty source ports is not incorrect so users could do that and run into this issue). 

Alternatively in the logic over [here](https://github.com/aristanetworks/avd/blob/3cac535c16978abb099f159b0bd6839536a9108c/python-avd/pyavd/_eos_cli_config_gen/j2templates/eos/ip-access-lists.j2#L57) where avd adds the source_port_match by default when source_port key is found, change it to add the source_port_match when actual non none value of source port is found (instead of just depending on presence/absence of source port key).

### Describe alternatives you have considered

_No response_

### Additional context

_No response_

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by gmuloc**
## Change Summary

1/ cf issue description - without the limitation the key accepts empty list and render `eq <empty>` which is wrong CLI
2/ PR was then grown for monitor postcard telemetry and application-traffic-recognition

## Related Issue(s)

Fixes #4642

## Component(s) name

`arista.avd.eos_cli_config_gen`

## Proposed changes

`min_length: 1` for dest and source port lists and other places from review

## How to test

Verified schema in molecule by adding empty lists in the molecule test for ACL (not committed as this is only schema change)

```
TASK [arista.avd.eos_cli_config_gen : Generate eos intended configuration and device documentation] ***
ERROR! [ip-access-lists]: 'Validation Error: ip_access_lists[0].entries[3].source_ports': The value is shorter (0) than the allowed minimum of 1.
ERROR! [ip-access-lists]: 'Validation Error: ip_access_lists[0].entries[3].destination_ports': The value is shorter (0) than the allowed minimum of 1.

```

### Repository Checklist

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [x] My change requires a change to the documentation and documentation have been updated accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

### CODE REVIEW

**Review by MaheshGSLAB — APPROVED** [review]
LGTM

**Review by alexeygorbunov — COMMENTED** [review]
Same behavior is observed here:

- https://github.com/aristanetworks/avd/blob/da8a39d692785cba31ba4f2f33c22ee0c5745123/python-avd/pyavd/_eos_cli_config_gen/schema/schema_fragments/application_traffic_recognition.schema.yml#L55

```
# Results in empty line (OK)
   field-set l4-port src_port_set1
      
   !
```

- https://github.com/aristanetworks/avd/blob/da8a39d692785cba31ba4f2f33c22ee0c5745123/python-avd/pyavd/_eos_cli_config_gen/schema/schema_fragments/monitor_telemetry_postcard_policy.schema.yml#L126 and https://github.com/aristanetworks/avd/blob/da8a39d692785cba31ba4f2f33c22ee0c5745123/python-avd/pyavd/_eos_cli_config_gen/schema/schema_fragments/monitor_telemetry_postcard_policy.schema.yml#L137

```
# Producing incorrect EOS CLI commands
   sample policy samplepo1
      match rule1 ipv4
         source prefix 3.4.5.0/24
         destination prefix 10.3.3.0/24
         protocol tcp destination port 
         protocol udp source port  destination port 
```

```
avd-ci-leaf2(config-s-sc-postcard-sample-policy-match-samplepo1-rule1-ipv4)# protocol tcp destination port 
% Incomplete command
avd-ci-leaf2(config-s-sc-postcard-sample-policy-match-samplepo1-rule1-ipv4)#protocol udp source port  destination port
% Invalid input
avd-ci-leaf2(config-s-sc-postcard-sample-policy-match-samplepo1-rule1-ipv4)#
```

Should we tackle it here as well?

**Comment by gmuloc** [comment]
> Same behavior is observed here:
> 
> * https://github.com/aristanetworks/avd/blob/da8a39d692785cba31ba4f2f33c22ee0c5745123/python-avd/pyavd/_eos_cli_config_gen/schema/schema_fragments/application_traffic_recognition.schema.yml#L55
> 
> ```
> # Results in empty line (OK)
>    field-set l4-port src_port_set1
>       
>    !
> ```
> 
> * https://github.com/aristanetworks/avd/blob/da8a39d692785cba31ba4f2f33c22ee0c5745123/python-avd/pyavd/_eos_cli_config_gen/schema/schema_fragments/monitor_telemetry_postcard_policy.schema.yml#L126
>    and https://github.com/aristanetworks/avd/blob/da8a39d692785cba31ba4f2f33c22ee0c5745123/python-avd/pyavd/_eos_cli_config_gen/schema/schema_fragments/monitor_telemetry_postcard_policy.schema.yml#L137
> 
> ```
> # Producing incorrect EOS CLI commands
>    sample policy samplepo1
>       match rule1 ipv4
>          source prefix 3.4.5.0/24
>          destination prefix 10.3.3.0/24
>          protocol tcp destination port 
>          protocol udp source port  destination port 
> ```
> 
> ```
> avd-ci-leaf2(config-s-sc-postcard-sample-policy-match-samplepo1-rule1-ipv4)# protocol tcp destination port 
> % Incomplete command
> avd-ci-leaf2(config-s-sc-postcard-sample-policy-match-samplepo1-rule1-ipv4)#protocol udp source port  destination port
> % Invalid input
> avd-ci-leaf2(config-s-sc-postcard-sample-policy-match-samplepo1-rule1-ipv4)#
> ```
> 
> Should we tackle it here as well?

not really the scope of this PR to only fix the issue but that should be easy enough

**Review by alexeygorbunov — APPROVED** [review]
LGTM!

All invalid use cases with empty lists are now raising an error
```
ERROR! [application-traffic-recognition]: 'Validation Error: application_traffic_recognition.field_sets.l4_ports[0].port_values': The value is shorter (0) than the allowed minimum of 1.
ERROR! [application-traffic-recognition]: 'Validation Error: application_traffic_recognition.field_sets.ipv4_prefixes[0].prefix_values': The value is shorter (0) than the allowed minimum of 1.

ERROR! [ip-access-lists]: 'Validation Error: ip_access_lists[0].entries[4].source_ports': The value is shorter (0) than the allowed minimum of 1.
ERROR! [ip-access-lists]: 'Validation Error: ip_access_lists[0].entries[4].destination_ports': The value is shorter (0) than the allowed minimum of 1.

ERROR! [monitor-telemetry-postcard-policy]: 'Validation Error: monitor_telemetry_postcard_policy.sample_policies[0].match_rules[0].protocols[0].destination_ports': The value is shorter (0) than the allowed minimum of 1.
ERROR! [monitor-telemetry-postcard-policy]: 'Validation Error: monitor_telemetry_postcard_policy.sample_policies[0].match_rules[0].protocols[1].source_ports': The value is shorter (0) than the allowed minimum of 1.
```

**Pull request merged**
