### PR TITLE
Upgrade role to translate 1.0 data to 1.1 avd tools

### PR DESCRIPTION
**Pull request by titom73**
## Change Summary

The initial version of the upgrade role to translate 1.0 data to 1.1.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [x] Documentation content changes
- [ ] Other (please describe):

## Related Issue(s)

PR #132 

## Component(s) name

Data model for EOS L3LS EVPN role (`arista.avd.eos_l3ls_evpn`)

## Proposed changes

Role to support data model migration for v1.0.x to data model implemented in v1.1.x

## How to test

Please refer to the molecule scenario: `ansible_collections/arista/avd/molecule/v1.0_to_v1.1/converge.yml`

It is likely not covering all possible combinations yet. To fix that in the future we need better test data That is consistent and covers the entire data model.
The current version is based on netdevops-examples data.

## Checklist:

- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly
- [x] I have read the [**CONTRIBUTING**](https://www.avd.sh/docs/contributing/) document.
- [x] All new and existing tests passed ([`pre-commit`](https://www.avd.sh/docs/installation/development/#python-virtual-environment), `make linting` and `make sanity-lint`).

### CODE REVIEW

**Comment by titom73** [comment]
- [x] Idempotency must be supported to pass ansible validation
- [x] `l2vlans` section is missing from the conversion


```diff
       Tenant_A_WAN_Zone:
         vrf_vni: 14
         svis:
           150:
             name: Tenant_A_WAN_Zone_1
-            tags: [ wan ]
-            enabled: true
-            ip_subnet: 10.1.40.0/24
-    l2vlans:
-      160:
-        vni_override: 50160
-        name: Tenant_A_VMOTION
-        tags: [ vmotion ]
-      161:
-        name: Tenant_A_NFS
-        tags: [ nfs ]
-
-
-# Tenant B Specific Information - VRFs / VLANs
+            tags: ['wan']
+            enabled: True
+            ip_address_virtual: 10.1.40.1/24
+  # Tenant_B Specific Information - VRFs / VLANs
```

**Comment by titom73** [comment]
Ready for complete review and merge

For local testing:

```shell
# Go to collection folder
$ cd ansible_collections/arista/avd/

# Run Test for the migration process
$ molecule test --scenario-name v1.0_to_v1.1

# Cleanup local env:
$ molecule cleanup --scenario-name v1.0_to_v1.1
```

Molecule test sequences:
- `create`: Build output folders
- `converge`: conversion role (run and idempotency)
- `verify`: run AVD with the file generated by upgrade role

**Comment by carlbuchmann** [comment]
@titom73 
> * `verify`: run AVD with the file generated by upgrade role

What is the strategy to maintain this test going forward, if the data model changes in a future release the verify will break since the playbook runs on the latest commit, correct?

**Comment by titom73** [comment]
> @titom73
> 
> > * `verify`: run AVD with the file generated by upgrade role
> 
> What is the strategy to maintain this test going forward, if the data model changes in a future release the verify will break since the playbook runs on the latest commit, correct?

All playbooks in molecule are configured to consume the current AVD library and not a specific version.

```yaml
provisioner:
  name: ansible
  env:
    ANSIBLE_COLLECTIONS_PATHS: '../../../../../'
```

In this configuration, the verify means generated data are used with last commit of AVD and paybook fails if roles return errors. We do not check the idempotency of `eos_l3ls_evpn` `nor `eos_cli_config_gen` in this action. These roles must be and are checked in other molecule scenarios

**Review by carlbuchmann — APPROVED** [review]
Reviewed and tested with NetDevOps example @ release 1.0.2.

**Pull request merged**
