### PR TITLE
Feat(eos_designs): Add schema for queue_monitor_length

### LINKED ISSUE #2852: Add schema for `queue_monitor_length`
```yaml
queue_monitor_length:
  log: 5
  notifying: true
  # Note "notifying" should only be rendered on 7280R since default
  # platform_settings for default has queue_monitor_length_notify_support: false
```

### PR DESCRIPTION
**Pull request by ClausHolbechArista**
## Change Summary

Add schema for queue_monitor_length

## Related Issue(s)

Fixes #2852 

## Component(s) name

`arista.avd.eos_designs`

## Proposed changes

- Add schema for queue monitor length
- Enhance support through eos_designs by not parsing the inputs, but just relaying it (after filtering out `notifying` where needed)

## How to test

Covered by existing molecule scenario `evpn_underlay_ebgp_overlay_ebgp`

### User Checklist

- N/A

### Repository Checklist

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [x] My change requires a change to the documentation and documentation have been updated accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

### CODE REVIEW

**Comment by jrecchia1029** [comment]
LGTM.  Just curious as to why `notifying` has its own description in eos designs. Is it simply to indicate that this key will only be configured if it is supported on the platform for which config is being generated?

**Comment by xaviramon** [comment]
I see we can configure `notifying` and if we set it up as false in a device which is not supporting this feature, it will generate a broken config. Is this something we should cover here?
```
queue_monitor_length:
  enabled: true
  notifying: false
```
  For a platform `default` generates this command:
```
  queue-monitor length
  no queue-monitor length notifying
```
Which is not supported:
```
ptt013(config)#no queue-monitor length not
% Unavailable command (not supported on this hardware platform)
```

**Comment by ClausHolbechArista** [comment]
> I see we can configure `notifying` and if we set it up as false in a device which is not supporting this feature, it will generate a broken config. Is this something we should cover here?

Yes thank you for testing thoroughly. I will make sure not to have the key at all if not supported.

**Comment by ClausHolbechArista** [comment]
> LGTM. Just curious as to why `notifying` has its own description in eos designs. Is it simply to indicate that this key will only be configured if it is supported on the platform for which config is being generated?

In `eos_cli_config_gen` we render what is given to us, and we have no idea if the command is supported or not, so we cannot specify that in the description.
In `eos_designs` we reuse most of the schema, except for this specific key, where we can use our `platform_settings` to control whether the key is supported or not.

**Comment by ClausHolbechArista** [comment]
@xaviramon please test again. I have now removed the key completely when not supported. Thanks

**Review by xaviramon — APPROVED** [review]
LGTM!

**Review by carlbuchmann — APPROVED** [review]
LGTM!

**Pull request merged**
