### PR TITLE
Eos_cli_config_gen Doc Standardization

### PR DESCRIPTION
**Pull request by aphillipps**
## Change Summary

Eos_cli_config_gen Documentation Standardization
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [x] Documentation content changes
- [ ] Other (please describe):

## Component(s) name
Eos_cli_config_gen

## Proposed changes

Here is the list of items that have been standardized:
- All titles with upper case
- When item is not configured describe as follows in a table: '-'
- When located in the default vrf or global routing table use default
- When feature not defined use {{ feature }} not defined
- No *** in titles, use ### instead (number of # corresponds to the title level in the doc)
- For enabled/disabled entries use lower case in tables
- For true/false entries use lower case in tables

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://www.avd.sh/docs/contributing/) document.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] All new and existing tests passed ([`pre-commit`](https://www.avd.sh/docs/installation/development/#python-virtual-environment), `make linting` and `make sanity-lint`).
- [x] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly

### CODE REVIEW

**Comment by titom73** [comment]
Will review changes today.

**Review by titom73 — APPROVED** [review]
LGTM!

Please check updates I did earlier

**Review by carlbuchmann — APPROVED** [review]
LGTM

**Comment by carlbuchmann** [comment]
> LGTM!
> 
> Please check updates I did earlier

Looks good thank you @titom73 and @aphillipps

**Pull request merged**
