### PR TITLE
Add support for configuring interface_profiles and setting them on et…

### PR DESCRIPTION
**Pull request by quulah**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Documentation content changes
- [ ] Other (please describe):

## Related Issue(s)

Related to #979

Requires merge of PR #1008 first.

## Component(s) name

`arista.avd.eos_cli_config_gen`

## Proposed changes

- Add supports for specifying `interface profile` parameters as well as setting them on Ethernet interfaces

## Checklist:

- [X] My code has been rebased from devel before I start
- [X] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contributing/) document.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly
- [X] All new and existing tests passed ([`pre-commit`](https://www.avd.sh/docs/installation/development/#python-virtual-environment), `make linting` and `make sanity-lint`).

### CODE REVIEW

**Comment by quulah** [comment]
Rebased to current devel and added the Molecule test for the new `interface_profiles` variable.

Didn't expect the rest of the configs to change, but there was actually a `profile: ALL` in some of the older tests. Uploaded the changed file, but unsure how to continue with those.

**Comment by titom73** [comment]
Hello @quulah 

[`profile: ALL`](https://github.com/aristanetworks/ansible-avd/blob/devel/ansible_collections/arista/avd/molecule/eos_cli_config_gen/intended/configs/qos.cfg) was a key not rendered by eos_cli_config_gen. As each host in this test is considered as independent, you can just focus on your own test file (`interface-profiles`) for the configuration rendering.

I will go ahead and remove other references in `qos` and `ethernet-interfaces` hosts.

Besides that, all the PR is nice !

**Comment by titom73** [comment]
> Hello @quulah
> 
> [`profile: ALL`](https://github.com/aristanetworks/ansible-avd/blob/devel/ansible_collections/arista/avd/molecule/eos_cli_config_gen/intended/configs/qos.cfg) was a key not rendered by eos_cli_config_gen. As each host in this test is considered as independent, you can just focus on your own test file (`interface-profiles`) for the configuration rendering.
> 
> I will go ahead and remove other references in `qos` and `ethernet-interfaces` hosts.
> 
> Besides that, all the PR is nice !

Actually, I tried to push, but seems you have not enabled push from maintainers.

So, you can simply remove all references to `profile: ALL` in files listed above and update molecule.

**Comment by quulah** [comment]
👍  Did that, should be sorted out now.

**Review by titom73 — CHANGES_REQUESTED** [review]
All templates and CI definition look good. But interface-profile is missing from master templates for configuration and documentation.

Please add entry to cover your feature in global rendering. Indeed, output of CI is not rendering your unit test.

**Comment by quulah** [comment]
Good catch! Fixed now.

**Review by titom73 — APPROVED** [review]
LGTM!

Thanks

**Comment by titom73** [comment]
As per Molecule, it seems there is a conflict with a key ingested by `eos_designs` that set profile inherited for port-profile out of EOS configuration.

Will take it on hold, time to review and see how to fix that with @carlbuchmann and @ClausHolbechArista

**Comment by ClausHolbechArista** [comment]
@titom73 Not sure why, but for some reason we have always set the `profile: <avd port-profile>` in the generated structured config. It is not used, so I suggest that we remove it from `ethernet-interfaces.j2` and `port-channel-interfaces.j2` under `templates/connected-endpoints`. I can do it in a seperate PR?

**Comment by ClausHolbechArista** [comment]
For AVD3.0 we could consider renaming the AVD "profiles" to "templates" to avoid the naming conflict.

**Comment by ClausHolbechArista** [comment]
PR #1008 has merged which removed the unintentional profiles. Please rerun molecule and commit updated artifacts.

**Comment by quulah** [comment]
Rebased and pushed as per @ClausHolbechArista request.

Something funky going on in the pipelines though:

```
x509: certificate is valid for legacy.python.org, not svn.python.org	https://svn.python.org/projects/external/Jinja-2.1.1/docs/_build/html/extensions.html
```

**Comment by ClausHolbechArista** [comment]
Yeah we tried to fix it with #1023
Can you try to pull that in

**Comment by ClausHolbechArista** [comment]
nevermind. I found another link. Time for weekend! :)

**Review by ClausHolbechArista — APPROVED** [review]
LGTM

**Pull request merged**
