### PR TITLE
Add support for configuring router igmp ssm aware

### PR DESCRIPTION
**Pull request by quulah**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Documentation content changes
- [ ] Other (please describe):

## Related Issue(s)

Related to #979

## Component(s) name

`arista.avd.eos_cli_config_gen`

## Proposed changes

- Add supports for specifying `router igmp` with `ssm aware`

## Checklist:

- [X] My code has been rebased from devel before I start
- [X] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contributing/) document.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly
- [X] All new and existing tests passed ([`pre-commit`](https://www.avd.sh/docs/installation/development/#python-virtual-environment), `make linting` and `make sanity-lint`).

### CODE REVIEW

**Comment by quulah** [comment]
Rebased to current devel and added Molecule test.

**Review by titom73 — APPROVED** [review]
LGTM. Will be merged after conflict will be fixed

- Template: OK
- Documentation: OK
- Molecule: OK
- CI result: OK

**Review by ClausHolbechArista — CHANGES_REQUESTED** [review]
Missing automated documentation in `eos_cli_config_gen`. I have submitted a PR towards your branch to fix this. Please merge that one in first and then we can merge this one.

**Comment by quulah** [comment]
Done!

**Review by ClausHolbechArista — APPROVED** [review]
LGTM

**Pull request merged**
