### PR TITLE
Feat(eos_cli_config_gen): VRRP timer delay and IPv4 version options

### LINKED ISSUE #1705: Feat(eos_cli_config_gen): VRRP timer delay and IPv4 version CLI options
### Enhancement summary

Add support for VRRP timer delay reload command per VRID

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

Reload switch in VRRP switch which also consumes a BGP full routing table. As BGP still processes all the routes switch must be prevented to become VRRP master

### Describe the solution you would like

```yaml
   # New improved "vrrp" data model to support multiple IDs
    vrrp_ids:
      - id: < vrid >
        timers:
          delay:
            reload: < integer >
```

### Describe alternatives you have considered

_No response_

### Additional context

PR incoming

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by c-po**
## Change Summary

Add support for VRRP timer delay reload command per VRID

## Related Issue(s)

Fixes #1705 

## Component(s) name

`arista.avd.eos_cli_config_gen`

## Proposed changes

```yaml
# New improved "vrrp" data model to support multiple IDs
vrrp_ids:
  - id: < vrid >
    timers:
      delay:
        reload: < integer >
```

## How to test

Molecule

### User Checklist

- N/A

### Repository Checklist

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [x] My change requires a change to the documentation and documentation have been updated accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

### CODE REVIEW

**Comment by ClausHolbechArista** [comment]
I just merged PR 1637 which also includes documentation for VRRP groups. Please add documentation for the new knobs as applicable.

**Comment by c-po** [comment]
@ClausHolbechArista should I simply add a column to indicate if timers are configured like preempt?

**Comment by ClausHolbechArista** [comment]
> @ClausHolbechArista should I simply add a column to indicate if timers are configured like preempt?

To not overdo it, maybe just add the version to the table.

**Review by ClausHolbechArista — APPROVED** [review]
LGTM

**Review by emilarista — APPROVED** [review]
LGTM!

**Pull request merged**
