### PR TITLE
Refactor(eos_designs): Wildcard dict to list management-settings event_handlers

### PR DESCRIPTION
**Pull request by ghost**
## Data model key

`event_handlers`

### Contributor Checklist

- [x] Update `README_v4.0.md` with new data model
- [x] Update `templates/eos/< template >.j2` and `templates/documentation/< template >.j2`:
  - [x] Add `arista.avd.convert_dicts('<primary key>')` filter for loops previously using wildcard keys
  - [x] Update `arista.avd.natural_sort('<primary key>')` to sort on the primary key (if applicable)
- [x] Verify no changes to generated configs/docs

### Reviewer Checklist

- Reviewer 1: (Claus)
  - [x] Verify data model changes
  - [x] Verify no changes to configs/docs on any molecule scenario
  - [x] Verify that CI pass

- Reviewer 2: (Guillaume)
  - [x] Verify data model changes
  - [x] Verify no changes to configs/docs on any molecule scenario
  - [x] Verify that CI pass

### CODE REVIEW

**Review by gmuloc — COMMENTED** [review]
Should there not be a test for this to adapt / create in `eos_designs`? (I could not find one so maybe need to create it)

**Comment by Shivani-chourasiya** [comment]
> Should there not be a test for this to adapt / create in `eos_designs`? (I could not find one so maybe need to create it)

yes ,I also didn't find it.

**Review by ClausHolbechArista — APPROVED** [review]
LGTM

**Review by gmuloc — APPROVED** [review]
> > Should there not be a test for this to adapt / create in `eos_designs`? (I could not find one so maybe need to create it)
> 
> yes ,I also didn't find it.

I discussed it with @ClausHolbechArista  - I will add a PR with a test for this pre and post model change later

in the meantime LGTM!

**Pull request merged**
