### PR TITLE
Refactor(eos_cli_config_gen): Rearrange the eos-cli config for router-bgp to match with EOS

### PR DESCRIPTION
**Pull request by MaheshGSLAB**
## Change Summary

Rearrange the eos-cli config for router-bgp to match with EOS 

## Related Issue(s)

Fixes #<ISSUE ID>

## Component(s) name

`arista.avd.eos_cli_config_gen`

## Proposed changes
Rearrange the eos-cli config for router-bgp to match with EOS 

## How to test
Run molecule

### User Checklist

- N/A

### Repository Checklist

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [x] My change requires a change to the documentation and documentation have been updated accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

### CODE REVIEW

**Review by Shivani-gslab — COMMENTED** [review]
`router_bgp.vlans` should be sorted based on `id` 
Line- 501 in router-bgp.j2

**Comment by MaheshGSLAB** [comment]
> `router_bgp.vlans` should be sorted based on `id` Line- 501 in router-bgp.j2

updated the j2 logic

**Review by Shivani-gslab — APPROVED** [review]
LGTM, checked all the commands

**Review by gmuloc — APPROVED** [review]
Checked that there is no missing rendered CLI post reordering
Checked most of the templates (blocks moved in correct place and no missing block) - could have missed something but this looks pretty good to me.

**Pull request merged**
