### PR TITLE
New Features: aliases, banners, dns, VM tracer, sflow, ssh, console, logging, tacacs, aaa, snmp, standard IP ACL, ipv6 routing, ipv6 static routes, multicast, pim sparse mode, rp and anycast rp, router l2 vpn, BGP AF

### LINKED ISSUE #33: SNMP Support
- Add support for SNMP configuration

### LINKED ISSUE #82: Add capability to define static routes in tenant data model in eos_l3ls_evpn
Add the capability to define static routes in the tenant data model.

### LINKED ISSUE #110: Portfast configuration for access-ports
This is useful for fast convergence in L2 segments.

Should be a best practice.

### PR DESCRIPTION
**Pull request by aphillipps**
**Created EOS CLI templates for**
- Terminal Settings
- Aliases
- Banners
- Domain Lookup
- DNS Domain
- VM Tracer Sessions
- Sflow: generic config not per port
- Management Console
- Management SSH
- IPv6 Routing: enabling ipv6 for GRT and VRFs
- IPv6 Static Routes
- Standard IP ACL
- Tacacs+ Servers
- AAA Server Groups
- IP Tacacs+ Source Interface
- SNMP Settings: hosts, groups, users, views, location, contact, traps
- L2 Router VPN
- IGMP Snooping: vlan
- Router Multicast: ipv4
- PIM Sparse Mode
- Anycast RDV Point
- RDV Point

**Refactored**
- BGP to add new address-families

**Added features in**
- Logging: logging server, logging trap, logging buffer
- Management Interface: IPv6
- Management API HTTP: ACL
- SVI: ip helper, pim sparse-mode, IPv6 enable,IPv6, IPv6 link local, IPv6 router virtual, nd ra,spt portfast, spt bpdufilter, shutdown, multicast ipv4 source route export, pim local-interface 
- Static Routes: tags, administrative distance and description
- Queue Monitor Length : notifying
- Route-maps: set and descriptions
- Loopback Interfaces: IPv6, shutdown
- Port-channel Interfaces: IPv6 enable, IPv6, IPv6 link local, nd ra, spt portfast, spt bpdufilter, vmtracer, shutdown, qos trust
- Ethernet Interfaces: IPv6, IPv6 link local, IPv6 enable, IPv6 nd ra, pim, spt portfast, spt bpdufilter, vmtracer, shutdown, qos trust
- MLAG: disable dual-primary detection

**Notes**
eos-intended-config.j2 and README.md have been updated accordingly.
EOS documentation jinja templates are being updated, but it is not completed yet.

### CODE REVIEW

**Comment by titom73** [comment]
Is this PR covering issue #82 ?

**Comment by c-po** [comment]
Looking for this PR to get merged as I was missing SNMP and AAA in master

**Comment by carlbuchmann** [comment]
> Looking for this PR to get merged as I was missing SNMP and AAA in master

@c-po we are working on reviewing and merging this content over the next few weeks. If you have any questions please feel free to reach out to ansible@arista.com

**Comment by carlbuchmann** [comment]
Closing PR, moved to PR #133 due to rebasing from devel.

**Pull request closed without merging**
