### PR TITLE
Releases/v2.x.x

### LINKED ISSUE #1079: Add support for  'error-correction encoding' to the eos_cli_config_gen role for Ethernet interfaces
**Issue Type**

- [x] Template enhancement
- [ ] Role enhancement
- [ ] Documentation enhancement (avd.sh)

**Is your feature request related to a problem? Please describe.**
when interconnecting arista with cisco, we need to use the following command which is not available on the latest AVD release:
error-correction encoding fire-code

**Describe the solution you'd like**
What we would like, is a data model like the following under the ethernet_interfaces template:

```
error_correction:
  encording: 
  - fire-code
  - reed-solomon
```

**Describe alternatives you've considered**

None found so far.

**Additional context**

the eos_cli_config_gen role on the Ethernet_interfaces template needs to be updated for the changes.

### LINKED ISSUE #1105: add spanning tree bpduguard disable functionality
**Issue Type**

- [x] Template enhancement
- [ ] Role enhancement
- [ ] Documentation enhancement (avd.sh)

**Is your feature request related to a problem? Please describe.**

Currently, the ethernet template has the functionality `spanning_tree_bpduguard:  < true | false >` but in reality, it only supports the falue true which enables the spanning_tree_bpduguard, but disabling it doesn't work.

the template enhancement needed to add support for the `spanning tree bpduguard disable` would then be as the following described below.

**Describe the solution you'd like**

lines to add:

`{%         if ethernet_interfaces[ethernet_interface].spanning_tree_bpduguard is arista.avd.defined(true) %}`
`   spanning-tree bpduguard enable`
`{%         elif ethernet_interfaces[ethernet_interface].spanning_tree_bpduguard is arista.avd.defined(false) %}`
`   spanning-tree bpduguard disable`
`{%         endif %}`

**Describe alternatives you've considered**

None found.

**Additional context**

None.

### PR DESCRIPTION
**Pull request by ifoughal**
## Change Summary

add possibility to set `spanning_tree_bpduguard` to `false` 

1- Currently, the ethernet template has the functionality spanning_tree_bpduguard: < true | false > but in reality, it only supports the value true which enables the spanning_tree_bpduguard, but disabling it doesn't work.

2- The error-correction encoding command is currently not supported.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Documentation content changes
- [ ] Other (please describe):

## Related Issue(s)

Fixes #1105
Fixes #1079

## Component(s) name

`arista.avd.eos_cli_config_gen` 

### ethernet-interfaces.j2

`{% if ethernet_interfaces[ethernet_interface].spanning_tree_bpduguard is arista.avd.defined(true) %}`
`spanning-tree bpduguard enable`
`{% elif ethernet_interfaces[ethernet_interface].spanning_tree_bpduguard is arista.avd.defined(false) %}`
`spanning-tree bpduguard disable`
`{% endif %}`
...
`{%         if ethernet_interfaces[ethernet_interface].error_correction_encoding.enabled is arista.avd.defined(true) %}`
`{%                if ethernet_interfaces[ethernet_interface].error_correction_encoding.fire_code is arista.avd.defined(true) %}`
`   error-correction encoding fire-code`
`{%                elif ethernet_interfaces[ethernet_interface].error_correction_encoding.fire_code is arista.avd.defined(false) %}`
`   no error-correction encoding fire-code`
`{%                elif ethernet_interfaces[ethernet_interface].error_correction_encoding.fire_code is arista.avd.defined('default') %}`
`   default error-correction encoding fire-code`
`{%                endif %}`
`{%                if ethernet_interfaces[ethernet_interface].error_correction_encoding.reed_solomon is arista.avd.defined(true) %}`
`   error-correction encoding reed-solomon`
`{%                elif ethernet_interfaces[ethernet_interface].error_correction_encoding.reed_solomon is arista.avd.defined(false) %}`
`   no error-correction encoding reed-solomon`
`{%                elif ethernet_interfaces[ethernet_interface].error_correction_encoding.reed_solomon is arista.avd.defined('default')%}`
`   default error-correction encoding reed-solomon`
`{%                endif %}`
`{%         elif ethernet_interfaces[ethernet_interface].error_correction_encoding.enabled is arista.avd.defined(false) %}`
`   no error-correction encoding`
`{%         elif ethernet_interfaces[ethernet_interface].error_correction_encoding.enabled is arista.avd.defined('default') %}`
`   default error-correction encoding`
`{%         endif %}`

New Schema:

```yaml
error_correction_encoding:
    enabled: < true | false | default >
    fire_code: < true | false | default >
    reed_solomon: < true | false | default >
```

## How to test
generate sample using ansible with role, with the two scenarios (False/true)

## Checklist:
- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly
- [ ] All new and existing tests passed ([`pre-commit`](https://www.avd.sh/docs/installation/development/#python-virtual-environment), `make linting` and `make sanity-lint`).

### CODE REVIEW

**Comment by carlbuchmann** [comment]
@idrisFoughali - Thanks for submitting this PR! It looks like you didn't select the correct **from** branch - this should point to a branch on your fork!

Also in your PR comment, it is not necessary to add jinja2 code, we will see that in the diff in files changes tab!

**Comment by ifoughal** [comment]
> @idrisFoughali - Thanks for submitting this PR! It looks like you didn't select the correct **from** branch - this should point to a branch on your fork!
> 
> Also in your PR comment, it is not necessary to add jinja2 code, we will see that in the diff in files changes tab!

Hi again @carlbuchmann 

Apologies for the misunderstanding, I'll work on uploading my changes to a fork, as I have been using our internal git so far. I'll update you as soon as I can.

**Comment by titom73** [comment]
Hello @idrisFoughali 

Then could you confirm we can close this PR?

Thanks.

**Comment by ifoughal** [comment]
> Hello @idrisFoughali
> 
> Then could you confirm we can close this PR?
> 
> Thanks.

Hi Thomas,

I was too dumb, and actually created the pull request without actually forking and doing the changes on my github repo.

Please do find the new pull request with the actual changes here:
https://github.com/aristanetworks/ansible-avd/pull/1123

**Pull request closed without merging**
