### PR TITLE
Feat(eos_cli_config_gen): Add support for SSH connection-limit

### LINKED ISSUE #1150: Add support for SSH connection-limit
### Enhancement summary

Opening this to add support for the following command:

```
management ssh
   connection limit 10

CL-1-09:04:14(config-mgmt-ssh)#connection ?
  limit     Set maximum number of SSH sessions
  per-host  Set maximum number of SSH sessions from a single host

CL-1-09:04:14(config-mgmt-ssh)#connection limit ?
  <0-100>  Maximum number of SSH connections
```
This limits the number of SSH sessions and does not seem currently supported based on the doc:

https://avd.sh/en/releases-v3.x.x/roles/eos_cli_config_gen/index.html#management-ssh

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

Matching configurations already present not generated via AVD.

### Describe the solution you would like

Allow to configure SSH limit via AVD.

### Describe alternatives you have considered

_No response_

### Additional context

_No response_

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by tgodaA**
## Change Summary

New features:
     - management_ssh.connection.limit, which limits the total number of SSH sessions to that switch. Value must be in range < 1-100 >
     - management_ssh.connection.per_host, which limits the # SSH sessions from a host. Value must be in range < 1-20 >

## Related Issue(s)

Fixes #1150 

## Component(s) name

`arista.avd.eos_cli_config_gen`

## Proposed changes

- Added molecule tests for eos_cli_config_gen
- Added new feature in 3.x.x.md
- Updated the README.md in eos_cli_config_gen

- management_ssh.connection_limit should be an integer in range <1-100>
- Added the connection_limit to documentation templates

## How to test

```
# Management SSH
management_ssh:
  access_groups:
    - name: CVP-ACL
      vrf: MGMT 
  idle_timeout: 5
  enable: true
  connection:
    limit: 50
    per_host: 10
  vrfs:
     MGMT:
      enable: true
```

Scenario 1) Tested the above snippet and verified:
                - intended/configs
                - documentation/devices
                 
Scenario 2) Tested the same snippet but this time without specifying connection_limit variable to test if there are no errors and all documentation and configuration are generated properly.

### User Checklist

- N/A

### Repository Checklist

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [x] My change requires a change to the documentation and documentation have been updated accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

### CODE REVIEW

**Comment by titom73** [comment]
EOS cli supports 2 knobs under `connection` to limit number of connection globally or per host.

```
EAPI-LEAF2A(config-s-sess-2-mgmt-ssh)#connection ?
  limit     Set maximum number of SSH sessions
  per-host  Set maximum number of SSH sessions from a single host
```

So I would go with a data model like this

```
connection:
  limit: < ... >
  per_host: < ... >
```

Does it make sense for you ?

**Comment by tgodaA** [comment]
Sure, I will make the changes. Since the PR is only for connection limit, I thought I should only that feature and later open a new case for the other one. But I will add both of them now.

**Review by emilarista — APPROVED** [review]
LGTM!

**Review by titom73 — APPROVED** [review]
LGTM! Thanks for the PR

**Pull request merged**
