### PR TITLE
Feat(eos_cli_config_gen): Support of route-target route-map for BGP VRFs

### LINKED ISSUE #3127: Support of route-target route-map
### Enhancement summary

Under router_bgp/vrf stanza, the eos_cli_config_gen schema doesn't support route-target route-map:

"The route-target route-map command allows the user to export and import route target extended community lists from one VRF to another using route maps.

Syntax
route-target {import | export} [evpn | vpn-ipv4 | vpn-ipv6] route-map RM"

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

vrf STK-HUB-SMT80-001
      rd 10.64.4.18:42001
      route-target import evpn 42001:1
      route-target import evpn 42001:42001
      route-target export evpn 42001:2
      route-target export evpn 42001:42001
      route-target import evpn route-map RM_DENY-DEFAULT  <<<<<<<<<<<
     ...

### Describe the solution you would like

1/ In eos_cli_config_gen schema, under router_bgp/vrfs/route_targets/import or export, in addition to "address_family" and "route_targets" properties, we add a new property (key: "route_map", value: "string")

2/ In jinja2 template "router-bgp.j2", make the relevant changes

### Describe alternatives you have considered

_No response_

### Additional context

_No response_

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by mmaaloul**
## Change Summary

Adding the ability to configure, at BGP/VRF level, a route-map for import/export from/to VPN or EVPN table

## Related Issue(s)

Fixes #3127 

## Component(s) name

`arista.avd.eos_cli_config_gen`

## Proposed changes
1/ Changed the router-bgp schema fragment
2/ Changed the associated Jinja2 template
PS: No change to template documentation as there is no section for VRF route-targets

## How to test
1/ Modified molecule eos_cli_config_gen inventory host_vars "router-bgp-v4-v6-evpn.yml" by adding import + export route-map
2/ Confirmed the generated eos configuration is OK

### User Checklist

- N/A

### Repository Checklist

- [x ] My code has been rebased from devel before I start
- [ x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [ ] My change requires a change to the documentation and documentation have been updated accordingly.
- [ x] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

### CODE REVIEW

**Review by ClausHolbechArista — COMMENTED** [review]
Thank you for this long overdue enhancement. You only cover VRFs. If it is not too much to ask, could you please check if the same is supported on EOS for VLANs and vlan-aware-bundles. If so, we should add it now to be consistent.
Note that for vlans and vlan-aware-bundles you also need to update the device documentation template. Just add the route-map to the list of exported/imported RTs like `route-map <name>`

**Comment by mmaaloul** [comment]
As per my check, route-target route-map is only meant for VRFs, not for MAC-VRFs

**Comment by ClausHolbechArista** [comment]
> As per my check, route-target route-map is only meant for VRFs, not for MAC-VRFs

Thank you for checking.

**Review by ClausHolbechArista — APPROVED** [review]
LGTM. Thanks again for this contribution.

**Review by gmuloc — APPROVED** [review]

**Pull request merged**
