### PR TITLE
Optimize(molecule): Add ANSIBLE_OPTIONS to pass ansible options to molecule scenario

### PR DESCRIPTION
**Pull request by titom73**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes)
- [ ] Documentation content changes
- [x] Other (please describe): Molecule

## Related Issue(s)

N/A

## Component(s) name

molecule

## Proposed changes

Add option to limit molecule execution:

```bash
$ make converge ANSIBLE_OPTIONS='--limit router-ospf'
cd .. && \
        molecule converge --scenario-name eos_cli_config_gen -- --limit router-ospf
```

> Specifically designed for eos_cli_config_gen

## How to test

Run molecule

## Checklist:

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contributing/) document.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly
- [x] All new and existing tests passed ([`pre-commit`](https://www.avd.sh/docs/installation/development/#python-virtual-environment), `make linting` and `make sanity-lint`).

### CODE REVIEW

**Comment by ClausHolbechArista** [comment]
Instead of only passing LIMIT, could we make a knob for ansible-options or similar? So parse anything ? I often use it with tags etc.

**Comment by titom73** [comment]
Good idea.
Updated code to support generic ansible options. By default it is set to `--limit all` to avoid passing a unsupported `-- ` after molecule scenario

**Comment by ClausHolbechArista** [comment]
adding `--` with no option after works fine. So I think it would be cleaner to just set `""` as default.

**Review by carlbuchmann — APPROVED** [review]
LGMT!

**Pull request merged**
