### PR TITLE
Add support for setting router pim sparse-mode ssm range

### LINKED ISSUE #979: Additional parameter support for eos_cli_config_gen
**Issue Type**

- [X] Template enhancement
- [ ] Role enhancement
- [ ] Documentation enhancement (avd.sh)

**Additional context**

I have added support for multiple parameters in the `eos_cli_config_gen` role.

PRs for each logical part:

https://github.com/aristanetworks/ansible-avd/pull/980
https://github.com/aristanetworks/ansible-avd/pull/981
https://github.com/aristanetworks/ansible-avd/pull/982
https://github.com/aristanetworks/ansible-avd/pull/983
https://github.com/aristanetworks/ansible-avd/pull/984
https://github.com/aristanetworks/ansible-avd/pull/985

### PR DESCRIPTION
**Pull request by quulah**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Documentation content changes
- [ ] Other (please describe):

## Related Issue(s)

Related to #979

## Component(s) name

`arista.avd.eos_cli_config_gen`

## Proposed changes

- Add supports for specifying `ssm range` parameter on `router pim`

## Checklist:

- [ ] My code has been rebased from devel before I start
- [X] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contributing/) document.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly
- [X] All new and existing tests passed ([`pre-commit`](https://www.avd.sh/docs/installation/development/#python-virtual-environment), `make linting` and `make sanity-lint`).

### CODE REVIEW

**Review by onurgashi — APPROVED** [review]
LGTM! To be honest looks simple not sure if we should have the molecule. I'll let @carlbuchmann decide on this.

**Comment by quulah** [comment]
I was going through all of my PRs and added the `ssm_range` to the test.

Rebased to current devel as well.

**Comment by carlbuchmann** [comment]
> LGTM! To be honest looks simple not sure if we should have the molecule. I'll let @carlbuchmann decide on this.

@onurgashi  - Yes, all PRs targeting `eos_cli_config_gen` requires a test - this allows us to refactor as required in time and insures the same outcome is preserved, it also eases the review process!

**Review by titom73 — APPROVED** [review]
LGTM!

- Template: OK
- Documentation: OK
- Molecule: OK
- CI result: OK

**Pull request merged**
