### PR TITLE
Create collection structure

### PR DESCRIPTION
**Pull request by titom73**
Create a collection structure as per [Ansible documentation](https://docs.ansible.com/ansible/devel/dev_guide/developing_collections.html#developing-collections)

Collection structure creation:

```
$ ansible-galaxy collection init arista.eos_avd
```

Collection build:

```
$ ansible-galaxy collection build arista/eos_avd
```

Local Installation for validation:

```
$ ansible-galaxy collection install arista-eos_avd-0.0.1.tar.gz -p collection/
$ tree collection -L 4
collection
└── ansible_collections
    └── arista
        └── eos_avd
            ├── FILES.json
            ├── MANIFEST.json
            ├── README.md
            ├── docs
            ├── plugins
            └── roles

6 directories, 3 files
```

Ansible version for build: __2.10.0__
Ansible version for run with `examples` content: 
- __2.8.3__
- __2.10.0__

### CODE REVIEW

**Comment by carlbuchmann** [comment]
resolve #21

**Comment by titom73** [comment]
As per Ansible issue tracker, moving to collection will require to use FQCN `namespace` and `collection` when calling any filter:

Issue [#58629](https://github.com/ansible/ansible/issues/58629)

__Not working:__
```
l3leafs.node_groups[l3leaf_node_group].nodes | natural_sort
```

__Working:__
```
l3leafs.node_groups[l3leaf_node_group].nodes | arista.eos_avd.natural_sort
```

So as it will impact all templates and probably break backward compatibility with ansible < `2.9`, it is to be validated before moving forward.

@carlbuchmann do you have opinion on that ?

**Comment by carlbuchmann** [comment]
@titom73, I believe we would want to have support for backward compatibility - I'll schedule a meeting so we can brainstorm potential approach/solutions!

**Comment by carlbuchmann** [comment]
@titom73 can you address these conflicts and merge in the new base branch feature-ansible-collection-structure, and we will continue the work from that branch, as this might a larger effort!

**Pull request closed without merging**
