### PR TITLE
Fix(eos_designs): Schema validation in eos_designs_facts

### PR DESCRIPTION
**Pull request by ClausHolbechArista**
## Change Summary

Fix Schema validation in `eos_designs_facts`

## Related Issue(s)

Input data conversion and validation based on schemas did not work in `eos_designs_facts`. This revealed itself as native Python errors raised when missing a required key.
All the code still has variable conversion built-in, so we did not see any differences there.

## Component(s) name

`arista.avd.eos_designs_facts` action plugin

## Proposed changes

- Wrap Ansible HostHostvars object as `dict` instead of `ChainMap`
- Add default variable handling for dynamic keys before schema validation
  - This required collapsing two functions in the code, to avoid carrying a lot of data around.

## How to test

- Tried inserting various errors in the data and saw it fail on the `eos_designs_facts` phase instead of `eos_designs_structured_config`.
- Tried running with conversion errors and saw it fail on the `eos_designs_facts` phase instead of `eos_designs_structured_config`.

### User Checklist

- N/A

### Repository Checklist

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [x] My change requires a change to the documentation and documentation have been updated accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

### CODE REVIEW

**Comment by carlbuchmann** [comment]
Need to add negative test cases, I will take care of that.

**Comment by xaviramon** [comment]
Work as expected!

**Comment by ClausHolbechArista** [comment]
Negative tests added

**Review by carlbuchmann — APPROVED** [review]
LGTM

**Pull request merged**
