### PR TITLE
Refactor(eos_designs, eos_cli_config_gen, eos_validate_state): structured_config file generation, json support

### PR DESCRIPTION
**Pull request by ClausHolbechArista**
## Related Issue(s)

Fixes #<ISSUE ID>

## Component(s) name

`arista.avd.eos_designs`
`arista.avd.eos_cli_config_gen`
`arista.avd.eos_validate_state`

## Proposed changes

- eos_designs
  - New default `avd_structured_config_file_format: "yml"`. Supported values are "yaml", "yml" and "json"
  - Move generation of `structured_config` files to `yaml_templates_to_facts` `dest` feature,
    -  Including support for JSON
    - Native python function for YAML creation - solves issue with line width differences between Ansible versions
    - Using "template_output" to trigger another templating of the output facts. Useful for custom_structured_configuration with inline jinja
    - Saving two tasks steps in the role.
  - The fact `structured_config` is no longer the full structured configuration, but instead the result facts from the task generating the structured configuration. The new content includes the `changed` flag which is set correctly depending on changes to the generated structured configuration files.

- eos_cli_config_gen and eos_validate_state
  - New default `avd_structured_config_file_format: "yml"`. Supported values are "yaml", "yml" and "json"
  - Refactor the import_var task to use `when` condition instead of having an extra task first.

## How to test

Molecule only shows changes to line width in the structured config files.

### User Checklist

- N/A

### Repository Checklist

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [x] My change requires a change to the documentation and documentation have been updated accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

### CODE REVIEW

**Comment by tgodaA** [comment]
LGTM. But I will test it today locally.

**Comment by tgodaA** [comment]
Tested it locally. It's working good without generating any changes.

**Review by carlbuchmann — APPROVED** [review]
LGTM!

**Review by tgodaA — APPROVED** [review]
LGTM

**Comment by tgodaA** [comment]
Does it have any documentation that needs to be updated?

avd/plugins/README.md -> line 460 needs to be updated.

**Pull request merged**
