### PR TITLE
Feat(eos_cli_config_gen): Add other valid_values for event-handler trigger 'on-boot'

### PR DESCRIPTION
**Pull request by gmuloc**
## Change Summary

Add additional valid_values for event-handler trigger 'on-boot'

## Component(s) name

`arista.avd.eos_cli_config_gen`

## Proposed changes

Uses the value from EOS:

```
ceos2(config-handler-TOTO)#trigger ?
  on-boot            Trigger condition occurs on system boot
  on-config          Trigger the event handler when it is configured
  on-counters        Trigger condition occurs on evaluating statistical counters
  on-intf            trigger condition occurs on specified interface changes
  on-logging         Trigger condition occurs when regex match any log message
  on-maintenance     Trigger condition occurs on maintenance operation
  on-startup-config  trigger condition occurs on startup config changes
  vm-tracer          Trigger condition occurs on VmTracer events
```

## How to test

molecule

### Repository Checklist

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [x] My change requires a change to the documentation and documentation have been updated accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

### CODE REVIEW

**Review by ClausHolbechArista — COMMENTED** [review]
I think each option supports/requires different options after the keyword on eos. So I think we may have to rewrite this model to a dict.

**Comment by gmuloc** [comment]
> I think each option supports/requires different options after the keyword on eos. So I think we may have to rewrite this model to a dict.

indeed - only `on-boot` seems to work like this. I only need on-boot for now so will remove the other and log an issue to revisit the model later.

Though it will be hard to model - you can configure an event-handler without a trigger in CLI (yeah that is useless probably but valid config) and then it would have to be a list for each option.

`on-counters` is actually a mode to get in..

```
event-handler trigger-on-boot
   trigger on-boot
   action bash echo "on-boot"
event-handler trigger-on-config
   trigger on-config disabled
   action bash echo "on-config"
event-handler trigger-on-counters
   action bash echo "on-counters"
   !
   trigger on-counters
event-handler trigger-on-intf
   trigger on-intf Ethernet1 ip
   action bash echo "on-intf"
event-handler trigger-on-maintenance
   trigger on-maintenance enter bgp BLAH after stage linkdown
   trigger on-config disabled
   action bash echo "on-maintenance"
event-handler trigger-vm-tracer
   trigger vm-tracer vm
   action bash echo "vm-tracer"
```

**Review by ClausHolbechArista — APPROVED** [review]

**Comment by ankudinov** [comment]
LGTM

**Review by ankudinov — APPROVED** [review]

**Review by carlbuchmann — APPROVED** [review]
Reviewed by Petr and Claus

**Pull request merged**
