### PR TITLE
Doc(eos_designs): ISIS-LDP IPVPN Topology Example

### PR DESCRIPTION
**Pull request by emilarista**
## Change Summary

Adds an example for configuring a simple MPLS network with ISIS, LDP and VPN-IPv4 overlay.

## Component(s) name

`arista.avd.eos_designs`

## How to test

Tested and verified topology and services are working using ACT.

### Repository Checklist

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [x] My change requires a change to the documentation and documentation have been updated accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

### CODE REVIEW

**Comment by JulioPDX** [comment]
Ill get this reviewed this week

**Comment by JulioPDX** [comment]
@emilarista I just pushed a bunch of updates. I updated the group vars for AVD 4.0, artifacts, readme, and molecule scenarios. Please let me know what you think.

**Review by JulioPDX — APPROVED** [review]
LGTM, pending any requested changes

**Comment by emilarista** [comment]
> @emilarista I just pushed a bunch of updates. I updated the group vars for AVD 4.0, artifacts, readme, and molecule scenarios. Please let me know what you think.

Updates look good to me, thanks for the good work and review!

**Review by ClausHolbechArista — APPROVED** [review]

**Pull request merged**
