### PR TITLE
Refactor fabric documentation

### LINKED ISSUE #475: Rename or sort out naming of fabric, dc, pod vs. documentation
## Issue Type

- Bug Report
- Documentation Report

## Summary
As part of super-spine implementation we added support for multiple PODs and introduced the DC notion. 

Current hierarchy is:
```
DC_Name
    Fabric_Name
```
We have been talking about changing the hierarchy of naming to:
```
Fabric_Name
    DC_Name
         POD_Name
```

## Role or Module Name
eos-l3ls-evpn

### LINKED ISSUE #552: Improve Jinja2 templates for super-spines to avoid error in case of unusual config
## Issue Type

- Bug Report

## Summary

Currently eos_l3ls_evpn is reporting error when documentation is generated for super-spines with L2 links.
While L2 links are not required on super-spines, Jinja2 template filters must be improved to verify if data is valid.

## Role or Module Name

eos_l3ls_evpn
for example: https://github.com/aristanetworks/ansible-avd/blob/devel/ansible_collections/arista/avd/roles/eos_l3ls_evpn/templates/documentation/dc-p2p-links.j2

### Expected results

Ignore invalid data to avoid the error or (preferred) report inconsistencies.

### PR DESCRIPTION
**Pull request by ClausHolbechArista**
## Change Summary
Complete rewrite of the fabric documentation for `eos_l3ls_evpn`

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to change)
- [X] Code style update (formatting, renaming)
- [X] Refactoring (no functional changes)
- [X] Documentation content changes
- [ ] Other (please describe):

## Related Issue(s)

Fixes issue #552 
Fixes issue #475 

## Component(s) name

`arista.avd.eos_l3ls_evpn`
`arista.avd.build_output_folders`

## Proposed changes

* Move fabric documentation to documentation/fabric/
* Change Markdown filename to <fabric_name>-documentation.md
* Change directory and documentation tasks to run_once
* Document fabric_name, dc_name and pod_name variables
* Include POD Name in fabric documentation
* Only include L3 links between inventory devices in p2p CSV files
* Include all links of all types in topology CSV files
* Support 5-stage CLOS and multiple PODs in single fabric documentation file
* Support for super-spine, overlay-controller device types
* Updated molecule folders
* Update molecule makefile to support cleanup (needed when changing folder structure)

## How to test

Tested with my repo as well as all the molecule test scenarios.
Works for both l3ls and multipod

## Checklist:

- [X] My code has been rebased from devel before I start
- [X] I have read the [**CONTRIBUTING**](https://www.avd.sh/docs/contributing/) document.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly
- [ ] All new and existing tests passed ([`pre-commit`](https://www.avd.sh/docs/installation/development/#python-virtual-environment), `make linting` and `make sanity-lint`).

### CODE REVIEW

**Review by titom73 — APPROVED** [review]
Looks good to me!
(Tested with an additional 3-stage clos fabric)

**Comment by ClausHolbechArista** [comment]
Hold on a second. Found a few issues I will fix

**Review by titom73 — COMMENTED** [review]
If we list mlag_peer in the topology, should not we also provide L3 interfaces for MLAG as well since these links are now listed in the documentation?

**Comment by ClausHolbechArista** [comment]
I did not want to delay this by adding too many new areas, but we should add (in another PR):
Summary of # devices of each type
List of other interfaces (excl server) (custom and comming dci)
Mlag peer and ibgp vlan and pools
L2leaf inband management

**Comment by titom73** [comment]
> I did not want to delay this by adding too many new areas, but we should add (in another PR):
> Summary of # devices of each type
> List of other interfaces (excl server) (custom and comming dci)
> Mlag peer and ibgp vlan and pools
> L2leaf inband management

Ok sounds like a good plan.

**Review by titom73 — APPROVED** [review]
Looks good to me!

**Pull request merged**
