### PR TITLE
Feat(eos_cli_config_gen): add sFlow sample output subinterface support

### PR DESCRIPTION
**Pull request by philippebureau**
## Change Summary

add sflow sample output subinterface to eos_cli_config_gen

## Related Issue(s)

N/A

## Component(s) name

`arista.avd.eos_cli_config_gen`

## Proposed changes
sflow:
  sample_output_subinterface: <bool>

## How to test
check molecule test update

### Repository Checklist

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [x] My change requires a change to the documentation and documentation have been updated accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

### CODE REVIEW

**Comment by ClausHolbechArista** [comment]
I merged the input variant. Please resolve all the conflicts.

**Review by emilarista — APPROVED** [review]
LGTM!

**Comment by ClausHolbechArista** [comment]
@philippebureau moving this one to draft. It needs some attention to rebase, resolve conflicts and rerun pre-commit.

**Comment by Shivani-gslab** [comment]
Need to rebase and resolve conflicts in this PR. 
Otherwise LGTM, tested it on ATD lab.

**Review by ClausHolbechArista — APPROVED** [review]

**Pull request merged**
