### PR TITLE
Doc: Fix typo in plugins README.md

### PR DESCRIPTION
**Pull request by pvinci-arista**
## Change Summary

Simple typo

## Related Issue(s)

Fixes #<ISSUE ID>

## Component(s) name

`arista.avd.encrypt`

### CODE REVIEW

**Review by gmuloc — APPROVED** [review]
Thanks for fixing this!

**Comment by ClausHolbechArista** [comment]
Please avoid creating branches in the main repo. You should *always* work from your own fork. We will try to change some permissions to avoid this going forward.

**Review by carlbuchmann — APPROVED** [review]

**Comment by pvinci-arista** [comment]
@ClausHolbechArista This contribution was from the edit page icon on avd.sh.  That workflow would need to create a fork, yes?

**Comment by ClausHolbechArista** [comment]
> @ClausHolbechArista This contribution was from the edit page icon on avd.sh. That workflow would need to create a fork, yes?

@JulioPDX can you look into this? We should not have to use the main repo for this

**Pull request merged**
