### PR TITLE
Fix(eos_designs): Documentation CSVs column headings

### PR DESCRIPTION
**Pull request by carlbuchmann**
## Change Summary

- Remove space in p2p-links.csv
- Update topology.csv heading `Peer` -> `Peer Node` to match p2p-links.csv

## Component(s) name

`arista.avd.designs`

## How to test

See Molecule Results

### Repository Checklist

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [x] My change requires a change to the documentation and documentation have been updated accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

### CODE REVIEW

**Comment by RyanM-Arista** [comment]
LGTM

**Review by RyanM-Arista — APPROVED** [review]
LGTM

**Comment by melkypie** [comment]
By the way this is a breaking change for people who use https://github.com/arista-netdevops-community/ansible-webinar-february-2020 as an example for batfish validation, specifically changing the `Peer` -> `Peer Node` key.

**Comment by ClausHolbechArista** [comment]
Sorry for the inconvenience. The webinar contents was written to AVD v1.0, so we didn't give that a thought.
We will avoid changing CSV headers outside of major versions in the future.

**Pull request merged**
