### PR TITLE
Fix(eos_designs): Configure evpn_ebgp_gateway_multihop for ipvpn_gateway EBGP peers

### LINKED ISSUE #3181: ebgp multihop not set for IPVPN
### Issue Summary

Im doing some testing on IPVPN gateway feature. When using the following:          
```
ipvpn_gateway:
            enabled: true
            evpn_domain_id: "65000:1"
            ipvpn_domain_id: "65000:2"
            enable_d_path: true
            address_families: [ vpn-ipv4 ]
            remote_peers:
              - hostname: fw1
                ip_address: 1.1.1.1
                bgp_as: 1
```
AVD generates:
```
neighbor IPVPN-GATEWAY-PEERS peer group
   neighbor IPVPN-GATEWAY-PEERS update-source Loopback0
   neighbor IPVPN-GATEWAY-PEERS bfd
   neighbor IPVPN-GATEWAY-PEERS send-community
   neighbor IPVPN-GATEWAY-PEERS maximum-routes 0
   
   address-family vpn-ipv4
      domain identifier 65000:2
      neighbor IPVPN-GATEWAY-PEERS activate
      neighbor default encapsulation mpls next-hop-self source-interface Loopback0
```
I had to add the following though so the bgp sessions are established between the loopbacks.
```
neighbor IPVPN-GATEWAY-PEERS ebgp-multihop 2
```

### Which component(s) of AVD impacted

eos_designs

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Steps to reproduce

```shell
Apply the previous configuration and check ebgp multihop is not set when using eBGP for IPVPN.
```

### Relevant log output

_No response_

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by ClausHolbechArista**
## Change Summary

Configure evpn_ebgp_gateway_multihop for ipvpn_gateway EBGP peers

## Related Issue(s)

Fixes #3181 

## Component(s) name

`arista.avd.eos_designs`

## Proposed changes

- Detect if an `ipvpn_gateway` peer is EBGP and set ebgp-multihop to value of `evpn_ebgp_gateway_multihop`.
- Remove invalid check for `ipvpn_gateway.local_as` from regular MPLS peerings.
- Remove wrongfully committed `test` file from molecule.
- Add test coverage for both IBGP and EBGP cases for ipvpn_gateway.

## How to test

Added new testcase and also validated updates to existing.

### User Checklist

- N/A

### Repository Checklist

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [x] My change requires a change to the documentation and documentation have been updated accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

### CODE REVIEW

**Comment by ClausHolbechArista** [comment]
@dgonzalez85 could you please test this one?

**Comment by dgonzalez-arista** [comment]
> @dgonzalez85 could you please test this one?

hey @ClausHolbechArista. I am having issues, just double checking in case im missing something:

Im using your branch and i see your commit:
```
commit 7683416f2635aeeaecc88dfd5a7058d37abf8f6f (HEAD -> fix/eos_designs/ebgp-multihop-for-ipvpn-gateway, origin/fix/eos_designs/ebgp-multihop-for-ipvpn-gateway)
Author: Claus Holbech <holbech@arista.com>
Date:   Thu Oct 5 10:18:06 2023 +0200

    Fix(eos_designs): Configure evpn_ebgp_gateway_multihop for ipvpn_gateway for ebgp peers.
```
In the fabric file i set this:
```
evpn_ebgp_gateway_multihop: 5
```
But i still do not see the multihop set:
```
   neighbor IPVPN-GATEWAY-PEERS peer group
   neighbor IPVPN-GATEWAY-PEERS update-source Loopback0
   neighbor IPVPN-GATEWAY-PEERS bfd
   neighbor IPVPN-GATEWAY-PEERS send-community
   neighbor IPVPN-GATEWAY-PEERS maximum-routes 0
```

**Comment by ClausHolbechArista** [comment]
> But i still do not see the multihop set:
> 
> ```
>    neighbor IPVPN-GATEWAY-PEERS peer group
>    neighbor IPVPN-GATEWAY-PEERS update-source Loopback0
>    neighbor IPVPN-GATEWAY-PEERS bfd
>    neighbor IPVPN-GATEWAY-PEERS send-community
>    neighbor IPVPN-GATEWAY-PEERS maximum-routes 0
> ```

Check under the neighbor. We cannot set it on the peer group, since you could have a mix of IBGP and EBGP.

**Review by emilarista — APPROVED** [review]
Tested feature and reviewed code, LGTM!

**Comment by dgonzalez-arista** [comment]
> > But i still do not see the multihop set:
> > ```
> >    neighbor IPVPN-GATEWAY-PEERS peer group
> >    neighbor IPVPN-GATEWAY-PEERS update-source Loopback0
> >    neighbor IPVPN-GATEWAY-PEERS bfd
> >    neighbor IPVPN-GATEWAY-PEERS send-community
> >    neighbor IPVPN-GATEWAY-PEERS maximum-routes 0
> > ```
> 
> Check under the neighbor. We cannot set it on the peer group, since you could have a mix of IBGP and EBGP.

no luck, i still do not see it there. happy to show you my example over a call if you have time. otherwise if other folks say its working, thats fine, might be something wrong in my example test!

**Review by dgonzalez-arista — APPROVED** [review]
Tested and looking good

**Pull request merged**
