### PR TITLE
Implement ip-helper for dhcp-relay

### LINKED ISSUE #312: DHCP relay (ip helper-address) in overlay with EVPN
**Issue Type**
- Role enhancement

**Is your feature request related to a problem? Please describe.**
There is a need to have DHCP Server residing in a VLAN, and hosts in different VLANs where we would need to enable DHCP relay functionality using ip helper address for overlay services, so they get network config.

**Describe the solution you'd like**
Under the SVI for tenant we can specify the ip helper config which is also defined in eos_cli_config_gen role

```
vlan_interfaces:
  < Vlan_id_1 >:
    description: < description >
    shutdown: < true | false >
    vrf: < vrf_name >
    ip_address: < IPv4_address/Mask >
    ip_address_secondary: < IPv4_address/Mask >
    ip_router_virtual_address: < IPv4_address >
    ip_router_virtual_address_secondary: < IPv4_address >
    ip_address_virtual: < IPv4_address/Mask >
    mtu: < mtu >
    ip_helpers:
      < ip_helper_address_1 >:
        source_interface: < source_interface_name >
        vrf: < vrf_name >
      < ip_helper_address_2 >:
        source_interface: < source_interface_name >
```

**Describe alternatives you've considered**
No solution, as static config has to be per tenant VLAN, which is difficult to scale.

### PR DESCRIPTION
**Pull request by titom73**
## Change Summary

Apply data model from eos_cli_config_gen in eos_l3ls_evpn

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Documentation content changes
- [ ] Other (please describe):

## Related Issue(s)

Fixes #312

## Component(s) name

`eos_l3ls_evpn`

## Proposed changes

Apply data model from `eos_cli_config_gen` in `eos_l3ls_evpn`

```yaml
tenants:
  # Tenant A Specific Information - VRFs / VLANs
  Tenant_A:
    mac_vrf_vni_base: 10000
    vrfs:
      TENANT_A_PROJECT01:
        vrf_vni: 11
        svis:
          311:
            name: 'PR01-TRUST-DHCP'
            tags: [POD01]
            enabled: true
            ip_address_virtual: 10.1.31.254/24
            ip_helpers:
              1.1.1.1:
                source_interface: lo100
  Tenant_B:
    mac_vrf_vni_base: 11000
    vrfs:
      ip_helpers:
        1.1.1.1:
          source_interface: lo100
      TENANT_B_PROJECT01:
        vrf_vni: 12
        svis:
          311:
            name: 'PR01-TRUST-DHCP'
            tags: [POD01]
            enabled: true
            ip_address_virtual: 10.2.31.254/24

```

## How to test

Rendering is as below for `eos_cli_config_gen`:

```yaml
  Vlan311:
    tenant: Tenant_A
    tags: ['POD01']
    description: PR01-TRUST-DHCP
    vrf: TENANT_A_PROJECT01
    ip_address_virtual: 10.1.31.254/24
    ip_helpers:
      1.1.1.1:
        source_interface: lo100
        vrf: TENANT_A_PROJECT01
```

And EOS configuration:

```eos
interface Vlan311
   description PR01-TRUST-DHCP
   vrf TENANT_A_PROJECT01
   ip address virtual 10.1.31.254/24
   ip helper-address 1.1.1.1 vrf TENANT_A_PROJECT01  source-interface lo100
```

## Checklist:

- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly
- [x] I have read the [**CONTRIBUTING**](https://www.avd.sh/docs/contributing/) document.
- [x] All new and existing tests passed ([`pre-commit`](https://www.avd.sh/docs/installation/development/#python-virtual-environment), `make linting` and `make sanity-lint`).

### CODE REVIEW

**Comment by carlbuchmann** [comment]
@titom73 - one of the ideas I had regarding the eos_lsls_evpn data model for SVIs, is to implement hierarchical profiles configuration as the configuration might be repetitive across many interfaces.

**Comment by titom73** [comment]
- [x] Add support for source_vrf outside of SVI vrf.

**Comment by titom73** [comment]
Ready for testing and review

**Review by carlbuchmann — APPROVED** [review]
LGTM

**Pull request merged**
