### PR TITLE
Doc: Update CSS to bring `code` to 100% size

### PR DESCRIPTION
**Pull request by ClausHolbechArista**
## Change Summary

Update CSS to bring `code` to 100% size

## Proposed changes

- Remove unused "ivory" CSS
  - [ ] @JulioPDX please confirm.
- Remove CSS override for code blocks to be 80% size.

## How to test

| Before | After |
| ------ | ----- |
| image | image |
| image | image |

### Repository Checklist

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [x] My change requires a change to the documentation and documentation have been updated accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

### CODE REVIEW

**Review by carlbuchmann — APPROVED** [review]
LGTM, docs look much better!

**Comment by JulioPDX** [comment]
I like it! LGTM

**Review by JulioPDX — APPROVED** [review]
LGTM

**Comment by JulioPDX** [comment]
In all fairness I believe it brings it to .85em after the change.

**Pull request merged**
