### PR TITLE
Doc: Pinned mkdocs-material version and updated make

### PR DESCRIPTION
**Pull request by JulioPDX**
## Change Summary

Pinned Mkdocs version to correct coloring.
Updated make file for documentation development with Docker.

## How to test

Checkout PR and run `make webdoc-up`

### Repository Checklist

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [x] My change requires a change to the documentation and documentation have been updated accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

### CODE REVIEW

**Review by carlbuchmann — APPROVED** [review]
LGTM!

**Review by ClausHolbechArista — APPROVED** [review]
LGTM - for a while - but I hope we are working on lifting this version dependency by solving the color issue?

**Comment by gmuloc** [comment]
@JulioPDX - could we add in this issue a link to why we are limiting mkdocs-material version to 9.0 rather than the latest 9.1 (maybe some github issue they have or whatever) so that it is easier to "get the context" when we need to change this?

**Comment by JulioPDX** [comment]
@gmuloc and @ClausHolbechArista it is most likely an issue with our custom css. I will open an issue and assign to myself. I don't believe this is an mkdocs material issue. Thank you

**Pull request merged**
