### PR TITLE
Feat(eos_cli_config_gen): Support for Interface Profiles on Port-channel interfaces

### LINKED ISSUE #4621: Support for Interface  Profiles in port-channel interfaces
### Enhancement summary

Port-channel interfaces in EOS support Interface Profiles just like normal Ethernet interfaces. However, AVD doesn't have that feature in [port-channel-interfaces.j2](https://github.com/aristanetworks/avd/blob/devel/python-avd/pyavd/_eos_cli_config_gen/j2templates/eos/port-channel-interfaces.j2). Let's add it.

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

Attach Interface Profile to port-channel interface.

### Describe the solution you would like

You should be able to refer to Interface Profiles under port-channel interface same way as with Ethernet interfaces: `profile: <str>`

Solution can be copied from [ethernet-interfaces.py](https://github.com/aristanetworks/avd/blob/b5251e9486db45ce5d4d64b8c2fc3e046f8c0ecc/python-avd/pyavd/_eos_cli_config_gen/j2templates/eos/ethernet-interfaces.j2#L11).

### Describe alternatives you have considered

_No response_

### Additional context

_No response_

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by JaakkoRautanen**
## Change Summary

Adds support for Interface Profiles on Port-channel interfaces

## Related Issue(s)

Fixes #4621

## Component(s) name

`arista.avd.eos_cli_config_gen`

## Proposed changes

- Added `profile` to `port_channel_interfaces.schema.yml`
- Added profile section to `port-channel-interfaces.j2`
- Added test 

### User Checklist

- N/A

### Repository Checklist

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [ ] My change requires a change to the documentation and documentation have been updated accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

### CODE REVIEW

**Review by gmuloc — COMMENTED** [review]
At first glance the PR looks good - I checked and we have no documentation for profile(s) applied for `ethernet_interfaces` though I would expect it could be quite valuable as a user what are your thoughts?

feel free to mark the PR as ready for review so other can review as well

**Comment by JaakkoRautanen** [comment]
Documentation would be useful for sure. What is correct place to add it?

**Comment by gmuloc** [comment]
> Documentation would be useful for sure. What is correct place to add it?

so the idea would be to add it in the pendant documentation templates for port-channels in this folder: https://github.com/aristanetworks/avd/tree/devel/python-avd/pyavd/_eos_cli_config_gen/j2templates/documentation

I have not gauged exactly what level of effort it would require and it could be quite convoluted so feel free to lets us know if you need some assist here.

**Comment by JaakkoRautanen** [comment]
I tried to look for example from `ethernet-interfaces.j2` in that folder. But could not find any reference for Interface Profile. I don't no what to do.

**Comment by gmuloc** [comment]
> I checked and we have no documentation for profile(s) applied for `ethernet_interfaces`

yeah that's what I was saying in a previous comment:

>  I checked and we have no documentation for profile(s) applied for `ethernet_interfaces` 

Let me give it a try for both

**Review by ClausHolbechArista — APPROVED** [review]

**Review by gmuloc — APPROVED** [review]
LGTM - lets merge as it is without further effort in documentaiton for now

**Pull request merged**
