### PR TITLE
bgp: vrf: support originating a default-route

### LINKED ISSUE #586: bgp: vrf: support originating a default-route and network
**Issue Type**

- [x] Template enhancement
- [x] Role enhancement
- [ ] Documentation enhancement (avd.sh)

**Is your feature request related to a problem? Please describe.**

Currently it is not possible to
- originate a default route by `default-originate` statement inside a VRF.
- announce a specific network inside a VRF.

This is an extension to #489

**Describe the solution you'd like**

Extend the Jinja2 template to support `bgp vrf neighbor default-originate` option

**Describe alternatives you've considered**

`custom_templates` could be used but this is not the desired way to go.

**Additional context**

https://github.com/aristanetworks/ansible-avd/pull/587

### PR DESCRIPTION
**Pull request by c-po**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [x] Documentation content changes
- [ ] Other (please describe):

## Related Issue(s)

#586 

## Component(s) name
eos_cli_config_gen

## Proposed changes

```
  vrfs:
    < vrf_name_1 >:
      networks:
        < prefix_ipv4 >:
          route_map: < route_map_name >
      neighbors:
        < neighbor_ip_address >:
          default_originate:
            always: < true | false >
            route_map: < route_map_name >
```

## How to test

```
router_bgp:
  as: 64512
  router_id: 172.16.7.192
  bgp_defaults:
    - bgp log-neighbor-changes
  vrfs:
    AristaFOO:
      rd: 64512:100
      networks:
        10.0.0.0/16:
      neighbors:
        192.168.72.4:
          remote_as: 64535
          timers: "10 30"
          description: MPLS_A
          default_originate:
            always: true
```

## Checklist:

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://www.avd.sh/docs/contributing/) document.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly
- [x] All new and existing tests passed ([`pre-commit`](https://www.avd.sh/docs/installation/development/#python-virtual-environment), `make linting` and `make sanity-lint`).

### CODE REVIEW

**Comment by c-po** [comment]
This is my first PR also updating the molecule tests. I hope I did everything in the manner it should be done @carlbuchmann @titom73 @aphillipps?

**Comment by titom73** [comment]
From Molecule stand point, it looks like all good and it is helpful to track deviation with result of `Molecule CLI CONFIG GEN` action.

`mkdoc_check` error can be ignored and will be resolved with PR https://github.com/aristanetworks/ansible-avd/pull/590 and seems to be related to runner issue.

We will shortly review your changes and proceed with a merge

Thanks again for all your contributions!

**Comment by c-po** [comment]
How to do this `Molecule CLI CONFIG GEN`?

**Comment by titom73** [comment]
It is a test action we have in CI like [this one](https://github.com/aristanetworks/ansible-avd/pull/587/checks?check_run_id=1663422305)

If you want to run the same kind of test, you can do:

```
$ cd ansible_collections/arista/avd/molecule

$ make run
```

But from what I see in changed files, I think you run this test before commit.

**Review by titom73 — APPROVED** [review]
Looks good to me. Thanks for your PR!

Besides that, we have released 2 plugins in the collection which could save time in your templates. Documentation is available in [the repo](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/plugins)

**Pull request merged**
