### PR TITLE
Feat(eos_cli_config_gen): Support encapsulation for EVPN peer groups

### LINKED ISSUE #2539: Support encapsulation for EVPN peer groups
### Enhancement summary

EVPN address family peers can set a specific encapsulation. At the moment only neighbor default is supported.

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

https://www.arista.com/en/support/toi/eos-4-28-2f/16100-multi-domain-evpn-vxlan-mpls

### Describe the solution you would like

`neighbor PEER_GROUP encapsulation vxlan` can be set.

### Describe alternatives you have considered

_No response_

### Additional context

_No response_

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by wnagele**
## Change Summary

Support encapsulation for EVPN peer groups.

## Related Issue(s)

Fixes #2539

## Component(s) name

`arista.avd.eos_cli_config_gen`

## Proposed changes
See PR.

## How to test
Local testing with our own needed config. Also added to Molecule test suite.

### User Checklist
None.

### Repository Checklist

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [x] My change requires a change to the documentation and documentation have been updated accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

### CODE REVIEW

**Comment by wnagele** [comment]
Did my best based on the knowledge of project layout. Would especially appreciate some eyes on the Molecule related bits. Not sure if this is proper.

**Comment by ClausHolbechArista** [comment]
> Did my best based on the knowledge of project layout. Would especially appreciate some eyes on the Molecule related bits. Not sure if this is proper.

Looks good so far. I will let the CI run to catch any issues. Maybe consider adding this encapsulation to the evpn address family documentation? There is a table with peer groups activated under the AF, which may be a good place to add a column for this.

**Comment by wnagele** [comment]
> Maybe consider adding this encapsulation to the evpn address family documentation? There is a table with peer groups activated under the AF, which may be a good place to add a column for this.

Do you maybe have a link to the relevant files for me?

**Comment by wnagele** [comment]
Any idea what the CI error is here? https://github.com/aristanetworks/ansible-avd/actions/runs/4174732054/jobs/7228975363

**Comment by wnagele** [comment]
> Any idea what the CI error is here? https://github.com/aristanetworks/ansible-avd/actions/runs/4174732054/jobs/7228975363

Might just need a re-run. Runs fine locally here. Transient network issue?

**Comment by ClausHolbechArista** [comment]
When I run `pre-commit run schemas --all` on your branch I get this diff:
```sh
holbech@holbech:~/ansible-avd$ git diff
diff --git a/ansible_collections/arista/avd/roles/eos_cli_config_gen/docs/data_model/Routing.md b/ansible_collections/arista/avd/roles/eos_cli_config_gen/docs/data_model/Routing.md
index 1bed30355..f6b23e0ed 100644
--- a/ansible_collections/arista/avd/roles/eos_cli_config_gen/docs/data_model/Routing.md
+++ b/ansible_collections/arista/avd/roles/eos_cli_config_gen/docs/data_model/Routing.md
@@ -385,7 +385,7 @@ MAC address (hh:hh:hh:hh:hh:hh)
     | [<samp>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;route_map_in</samp>](## "router_bgp.address_family_evpn.peer_groups.[].route_map_in") | String |  |  |  | Inbound route-map name |
     | [<samp>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;route_map_out</samp>](## "router_bgp.address_family_evpn.peer_groups.[].route_map_out") | String |  |  |  | Outbound route-map name |
     | [<samp>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;domain_remote</samp>](## "router_bgp.address_family_evpn.peer_groups.[].domain_remote") | Boolean |  |  |  |  |
-    | [<samp>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;encapsulation</samp>](## "router_bgp.address_family_evpn.peer_groups.[].encapsulation") | String |  |  |  |  |
+    | [<samp>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;encapsulation</samp>](## "router_bgp.address_family_evpn.peer_groups.[].encapsulation") | String |  |  | Valid Values:<br>- vxlan<br>- mpls |  |
     | [<samp>&nbsp;&nbsp;&nbsp;&nbsp;evpn_hostflap_detection</samp>](## "router_bgp.address_family_evpn.evpn_hostflap_detection") | Dictionary |  |  |  |  |
     | [<samp>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;enabled</samp>](## "router_bgp.address_family_evpn.evpn_hostflap_detection.enabled") | Boolean |  |  |  |  |
     | [<samp>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;window</samp>](## "router_bgp.address_family_evpn.evpn_hostflap_detection.window") | Integer |  |  | Min: 0<br>Max: 4294967295 | Time (in seconds) to detect a MAC duplication issue |

```

**Comment by ClausHolbechArista** [comment]
> > Maybe consider adding this encapsulation to the evpn address family documentation? There is a table with peer groups activated under the AF, which may be a good place to add a column for this.
> 
> Do you maybe have a link to the relevant files for me?

https://github.com/wnagele/ansible-avd/blob/evpn_peergroup_encap/ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/documentation/router-bgp.j2#L437

**Comment by wnagele** [comment]
Changes implemented. Ready for review and CI validation.

**Comment by wnagele** [comment]
Is there a way to re-generate those docs? Would like to avoid doing that by hand :)

**Comment by carlbuchmann** [comment]
> Is there a way to re-generate those docs? Would like to avoid doing that by hand :)
@wnagele
1st, thank you for this contribution!
And,  yes from `/ansible-avd/ansible_collections/arista/avd/molecule` run `make refresh-facts`. 
This will run and update all molecule scenarios.
 Alternatively you can run individual molecule from `/ansible-avd/ansible_collections/arista/avd/` with 
`molecule converge -s "name of the scenario"` where name of the scenario is the molecule folder name 
i.e `molecule converge -s eos_designs_unit_tests`

**Comment by wnagele** [comment]
Done and ready for review + CI run.

**Review by ClausHolbechArista — APPROVED** [review]

**Review by gmuloc — APPROVED** [review]
LGTM - thanks for this contribution!

**Comment by ClausHolbechArista** [comment]
@wnagele Thank you for your first contribution! It will be a while before we release 4.0 containing this feature, but we will release ~weekly `4.0.0-dev` releases.

**Comment by wnagele** [comment]
Thanks @ClausHolbechArista. We'll pin to my repo with the cherry-picked PR for now then.

**Pull request merged**
