### PR TITLE
Fix(eos_designs): PTP documentation not linked from mkdocs.yml

### LINKED ISSUE #2333: Bug: (eos_designs) PTP documentation not linked from mkdocs.yml
### Issue Summary

The documentation file (ptp.md) is not linked from mkdocs.yml, meaning there's no easy way to find the PTP documentation for eos_designs.

### Which component(s) of AVD impacted

eos_designs

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Steps to reproduce

_No response_

### Relevant log output

_No response_

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by nielsjlarsen**
## Change Summary

Fix mkdocs.yml to include ptp.md

## Related Issue(s)

Fixes #2333 

## Component(s) name

`arista.avd.eos_designs`

## Proposed changes
Added last line to mkdocs.yml:

  - Roles Documentation:
      - eos_designs:
          - Overview: roles/eos_designs/README.md
          - Connected Endpoints: roles/eos_designs/doc/connected-endpoints.md
          - DCI & L3 Edge: roles/eos_designs/doc/l3-edge.md
          - Fabric Topology: roles/eos_designs/doc/fabric-topology.md
          - Fabric Variables: roles/eos_designs/doc/fabric-variables.md
          - Management Settings: roles/eos_designs/doc/management-settings.md
          - Network Services: roles/eos_designs/doc/network-services.md
          - PTP: roles/eos_designs/doc/ptp.md

### User Checklist

- N/A

### Repository Checklist

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [x] My change requires a change to the documentation and documentation have been updated accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

### CODE REVIEW

**Review by tgodaA — APPROVED** [review]
LGTM

**Comment by ClausHolbechArista** [comment]
@JulioPDX please check on the placement of this doc. It is a detailed description of all the PTP configs available in the different configuration areas. It is also documented under each area.

**Review by gmuloc — APPROVED** [review]
LGTM

**Comment by JulioPDX** [comment]
> @JulioPDX please check on the placement of this doc. It is a detailed description of all the PTP configs available in the different configuration areas. It is also documented under each area.

Hey @ClausHolbechArista I'm a bit late but no issues here. Thanks

**Pull request merged**
