### PR TITLE
Fix(eos_validate_state): Ensure graceful handling of command errors from ANTA

### LINKED ISSUE #4384: ANTA Integration broken when a command fails
### Issue Summary

When an EOS command fails, the code does not handle the error correctly:

Related change in ANTA is: https://github.com/aristanetworks/anta/commit/3cb44eeff16188d3620ff8537b9366792b188ccc#diff-ae78f9c0592bc6494a730dab1ce8d5de1638e36deb3f59abc3e668fba689d30aL140

### Which component(s) of AVD impacted

eos_validate_state

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Steps to reproduce

```shell
Run eos_validate_state role with a command that returns an error.
```

### Relevant log output

```shell
2024-08-21 14:33:27,826 p=32166 u=mtache n=anta.tests.hardware.VerifyEnvironmentPower | [ANTA Debug Mode] Exception raised while collecting commands for test VerifyEnvironmentPower (on device campus-leaf3e)
Traceback (most recent call last):
  File "/home/mtache/.ansible/collections/ansible_collections/arista/avd/plugins/plugin_utils/eos_validate_state_utils/ansible_eos_device.py", line 135, in _collect
    response = await loop.run_in_executor(None, send_request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mtache/.ansible/collections/ansible_collections/arista/eos/plugins/httpapi/eos.py", line 97, in send_request
    results = handle_response(response_data)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mtache/.ansible/collections/ansible_collections/arista/eos/plugins/httpapi/eos.py", line 190, in handle_response
    raise ConnectionError(error_text, code=error["code"])
ansible.module_utils.connection.ConnectionError: There seem to be no power supplies connected.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mtache/.local/pipx/venvs/pyavd/lib/python3.12/site-packages/anta/models.py", line 530, in collect
    await self.device.collect_commands(self.instance_commands, collection_id=self.name)
  File "/home/mtache/.local/pipx/venvs/pyavd/lib/python3.12/site-packages/anta/device.py", line 178, in collect_commands
    await asyncio.gather(*(self.collect(command=command, collection_id=collection_id) for command in commands))
  File "/home/mtache/.local/pipx/venvs/pyavd/lib/python3.12/site-packages/anta/device.py", line 165, in collect
    await self._collect(command=command, collection_id=collection_id)
  File "/home/mtache/.ansible/collections/ansible_collections/arista/avd/plugins/plugin_utils/eos_validate_state_utils/ansible_eos_device.py", line 148, in _collect
    command.failed = e
    ^^^^^^^^^^^^^^
  File "/home/mtache/.local/pipx/venvs/pyavd/lib/python3.12/site-packages/pydantic/main.py", line 856, in __setattr__
    raise ValueError(f'"{self.__class__.__name__}" object has no field "{name}"')
ValueError: "AntaCommand" object has no field "failed"
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by ClausHolbechArista**
## Change Summary

Ensure graceful handling of command errors from ANTA

## Related Issue(s)

Fixes #4384

## Component(s) name

`arista.avd.<role-name>`

## Proposed changes

The ANTA API changed between the initial implementation and ANTA 1.0.0, but we missed updating `failed` -> `errors[]` when interacting with `AntaCommand` subclasses.

## How to test

Asking @mtache to test and confirm :)

### User Checklist

- N/A

### Repository Checklist

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [x] My change requires a change to the documentation and documentation have been updated accordingly.
- [X] I have updated [molecule CI](https://github.com/aristanetworks/avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

### CODE REVIEW

**Comment by mtache** [comment]
The Exception is re-raised in the except block, and this is not handled gracefully in ANTA as suggested by the function docstring:
```
2024-08-21 15:59:09,322 p=12088 u=mtache n=anta.tests.hardware.VerifyEnvironmentPower | [ANTA Debug Mode] Exception raised while collecting commands for test VerifyEnvironmentPower (on device campus-leaf3d)
Traceback (most recent call last):
  File "/mnt/lab/projects/avd/ansible_collections/arista/avd/plugins/plugin_utils/eos_validate_state_utils/ansible_eos_device.py", line 140, in _collect
    response = await loop.run_in_executor(None, send_request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mtache/.ansible/collections/ansible_collections/arista/eos/plugins/httpapi/eos.py", line 97, in send_request
    results = handle_response(response_data)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mtache/.ansible/collections/ansible_collections/arista/eos/plugins/httpapi/eos.py", line 190, in handle_response
    raise ConnectionError(error_text, code=error["code"])
ansible.module_utils.connection.ConnectionError: There seem to be no power supplies connected.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mtache/.local/pipx/venvs/pyavd/lib/python3.12/site-packages/anta/models.py", line 530, in collect
    await self.device.collect_commands(self.instance_commands, collection_id=self.name)
  File "/home/mtache/.local/pipx/venvs/pyavd/lib/python3.12/site-packages/anta/device.py", line 178, in collect_commands
    await asyncio.gather(*(self.collect(command=command, collection_id=collection_id) for command in commands))
  File "/home/mtache/.local/pipx/venvs/pyavd/lib/python3.12/site-packages/anta/device.py", line 165, in collect
    await self._collect(command=command, collection_id=collection_id)
  File "/mnt/lab/projects/avd/ansible_collections/arista/avd/plugins/plugin_utils/eos_validate_state_utils/ansible_eos_device.py", line 156, in _collect
    raise e.__class__(msg) from e
ansible.module_utils.connection.ConnectionError: Command 'show system environment power' failed: There seem to be no power supplies connected.
```

I am pushing suggested changes, please review.
Having an ERROR log allows to have the failure reported in the play.

The long term solution is to use the AsyncEOSDevice implementation in ANTA to benefit from the error handling of the `_collect()` function maintained there:
https://github.com/aristanetworks/anta/blob/main/anta/device.py#L309C15-L309C23

**Comment by carl-baillargeon** [comment]
> The Exception is re-raised in the except block, and this is not handled gracefully in ANTA as suggested by the function docstring:
> 
> ```
> 2024-08-21 15:59:09,322 p=12088 u=mtache n=anta.tests.hardware.VerifyEnvironmentPower | [ANTA Debug Mode] Exception raised while collecting commands for test VerifyEnvironmentPower (on device campus-leaf3d)
> Traceback (most recent call last):
>   File "/mnt/lab/projects/avd/ansible_collections/arista/avd/plugins/plugin_utils/eos_validate_state_utils/ansible_eos_device.py", line 140, in _collect
>     response = await loop.run_in_executor(None, send_request)
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.12/concurrent/futures/thread.py", line 58, in run
>     result = self.fn(*self.args, **self.kwargs)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/mtache/.ansible/collections/ansible_collections/arista/eos/plugins/httpapi/eos.py", line 97, in send_request
>     results = handle_response(response_data)
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/mtache/.ansible/collections/ansible_collections/arista/eos/plugins/httpapi/eos.py", line 190, in handle_response
>     raise ConnectionError(error_text, code=error["code"])
> ansible.module_utils.connection.ConnectionError: There seem to be no power supplies connected.
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/home/mtache/.local/pipx/venvs/pyavd/lib/python3.12/site-packages/anta/models.py", line 530, in collect
>     await self.device.collect_commands(self.instance_commands, collection_id=self.name)
>   File "/home/mtache/.local/pipx/venvs/pyavd/lib/python3.12/site-packages/anta/device.py", line 178, in collect_commands
>     await asyncio.gather(*(self.collect(command=command, collection_id=collection_id) for command in commands))
>   File "/home/mtache/.local/pipx/venvs/pyavd/lib/python3.12/site-packages/anta/device.py", line 165, in collect
>     await self._collect(command=command, collection_id=collection_id)
>   File "/mnt/lab/projects/avd/ansible_collections/arista/avd/plugins/plugin_utils/eos_validate_state_utils/ansible_eos_device.py", line 156, in _collect
>     raise e.__class__(msg) from e
> ansible.module_utils.connection.ConnectionError: Command 'show system environment power' failed: There seem to be no power supplies connected.
> ```
> 
> I am pushing suggested changes, please review. Having an ERROR log allows to have the failure reported in the play.
> 
> The long term solution is to use the AsyncEOSDevice implementation in ANTA to benefit from the error handling of the `_collect()` function maintained there: https://github.com/aristanetworks/anta/blob/main/anta/device.py#L309C15-L309C23

@mtache When initially working on this implementation, we agreed that we would NOT fail the play for a device if a command fails, but rather let ANTA handle the exception. Once we get the results from ANTA we "translate" the errored tests into failed tests for the report. Your suggestion changes that behavior (play fails) and I don't think we want to change that for now. @ClausHolbechArista Thoughts?

Like you pointed out we will be using the native `AsyncEOSDevice` client in the future implementation :)

**Comment by mtache** [comment]
There are 2 points here:
1) how to handle an exception related to command collection
2) should we fail the play in Ansible if that happens

Regarding (1), it needs to be done in the _collect() function as exception handling is dependent on the underlying libraries. We do not have ANTA Exception to raise so the ANTA framework could distinguish errors and do proper handling as this is currently done in AsyncEOSDevice._collect().

For (2), I don't have any opinion. I've juste noticed that if you issue an ERROR log using the logger instance, the play reports a failure (but all the tests are still run).

**Comment by carl-baillargeon** [comment]
> There are 2 points here:
> 
> 1. how to handle an exception related to command collection
> 2. should we fail the play in Ansible if that happens
> 
> Regarding (1), it needs to be done in the _collect() function as exception handling is dependent on the underlying libraries. We do not have ANTA Exception to raise so the ANTA framework could distinguish errors and do proper handling as this is currently done in AsyncEOSDevice._collect().
> 
> For (2), I don't have any opinion. I've juste noticed that if you issue an ERROR log using the logger instance, the play reports a failure (but all the tests are still run).

If we want to keep the existing behavior (play doesn't fail), we can either use `logger.warning` and have a beautiful (or not) Ansible warning message, or we re-raise to ANTA and use ANTA loggers (like we do today). Unless I am missing something I don't see another option if we don't want to fail the play.

**Comment by ClausHolbechArista** [comment]
So this fix was supposed to address the issue you raised about using the wrong field. It was not supposed to change the way we do error handling. If we wish to change the strategy for error handling it should be done in a refactor or feature PR.

**Comment by ClausHolbechArista** [comment]
The updates breaks CI because imports from anta must be done inside try/except (welcome to Ansible plugins...). I will try to update it.

**Comment by ClausHolbechArista** [comment]
@mtache @carl-baillargeon please test this again. Thanks!

**Comment by mtache** [comment]
So I've changed the log level from error to warning to keep existing behaviour.
@carl-baillargeon, when this will be refactored to use the implementation at https://github.com/aristanetworks/anta/blob/main/anta/device.py#L309, the behaviour will change as the code issues error logs when an error occurs during an eAPI request.

Tested and working.

**Review by mtache — APPROVED** [review]

**Review by carl-baillargeon — APPROVED** [review]
LGTM.

**Pull request merged**
