### PR TITLE
Fix(eos_cli_config_gen): Maintenance shutdown max-delay update

### LINKED ISSUE #1155: eos_cli_conf_gen: maintenance: interface profiles option shutdown not rendered to cli
### Issue Summary

Maintenance interface profiles offer two options: rate-monitoring and shutdown

```
maintenance:
  interface_profiles:
    < interface_profile_1 >:
      rate_monitoring:
        load_interval: < seconds >
        threshold: < kbps >
      shutdown:
        max_delay: < seconds >
```

When using the following yaml config the ```shutdown```option is not rendered into cli.

```
maintenance:
  interface_profiles:
    MM_Prof_Downlinks:
      shutdown:
        max_delay: 3
 ```
 
I cannot find any part for ```shutdown```in the J2 file ```https://github.com/aristanetworks/ansible-avd/blob/devel/ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/eos/maintenance.j2```

 

### Which component(s) of AVD impacted

eos_cli_config_gen

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Steps to reproduce

```shell

maintenance:
  interface_profiles:
    MM_Prof_Downlinks:
      shutdown:
        max_delay: 3
```

### Relevant log output

_No response_

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by daanvdsanden**
## Change Summary

Makes sure that the shutdown delay is rendered in cli and docu,emtation

## Related Issue(s)

Fixes #1155 

## Component(s) name

`arista.avd.eos_cli_config_gen

## Proposed changes
Added missing forced shutdown delay

### User Checklist
- N/A

### Repository Checklist

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [ ] My change requires a change to the documentation and documentation have been updated accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

### CODE REVIEW

**Comment by titom73** [comment]
As CI was broken yesterday, I have pushed Molecule's output update to reactivate CI in your branch.

**Review by titom73 — CHANGES_REQUESTED** [review]
Thank you for this PR. Still some work to do on documentation. Please update and we will review again.

**Review by ClausHolbechArista — APPROVED** [review]
LGTM!

**Comment by ClausHolbechArista** [comment]
> Thank you for this PR. Still some work to do on documentation. Please update and we will review again.

@titom73 documentation was already there. It was just not implemented :)

**Review by titom73 — APPROVED** [review]
LGTM!

**Pull request merged**
