### PR TITLE
Feat(eos_cli_config_gen,eos_designs): Add support for 'l2 mru'

### PR DESCRIPTION
**Pull request by ghost**
## Change Summary

add support for setting the "l2 mru" on interfaces and port-channels

## Related Issue(s)

none

## Component(s) name

`arista.avd.eos_cli_config_gen`

## Proposed changes
I duplicated all "l2_mtu" assets and replaced "mtu" with mru"

## How to test
did a config generation and deployment with the branch:
```
r2-lab2-de#show int eth14 | grep MRU
  IP MTU 1500 bytes (default), Ethernet MRU 10240 bytes, BW 10000000 kbit
```
ansible run:
```
ok: [r2-lab2-de] => 
  msg:
  - |-
    --- system:/running-config
    +++ session:/1481195311-session-config
    interface Ethernet14
    +   l2 mru 9000
```
```
r2-lab2-de#show int eth14 | grep MRU
  IP MTU 1500 bytes (default), Ethernet MRU 9000 bytes, BW 10000000 kbit
```

### User Checklist
```
ansible_collections/arista/avd/roles/eos_cli_config_gen](support-l2-mru) $ grep -r "l2_mtu\|l2_mru"
```
then eyeballed if every l2_mtu has a l2_mru equivalent (actually good that I did :) )

### Repository Checklist

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [x] My change requires a change to the documentation and documentation have been updated accordingly.
- [ ] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

### CODE REVIEW

**Comment by carlbuchmann** [comment]
@m-rhode thank you for this contribution, I converted it back to draft as you also need to include molecule unit tests for eos_designs and eos_cli_config_gen.
I see you are a first-time contributor to the project, and can assist on a zoom if required. Please contact me @ carl.buchmann@arista.com.

**Comment by carlbuchmann** [comment]
Also, you need to generate documentation. This is done by running pre-commit locally. [Install pre-commit](https://avd.arista.com/4.3/docs/contribution/development.html#pre-commit-hook) and then run:
 `pre-commit run shemas --all`

**Comment by ghost** [comment]
> @m-rhode thank you for this contribution, I converted it back to draft as you also need to include molecule unit tests for eos_designs and eos_cli_config_gen. I see you are a first-time contributor to the project, and can assist on a zoom if required. Please contact me @ [carl.buchmann@arista.com](mailto:carl.buchmann@arista.com).

Hello @carlbuchmann, thanks for the zoom offer, much appreciated!
Let's first try without. I assume it's basically reproducing the `l2_mtu` config under "ansible_collections/arista/avd/molecule" for the molecule stuff. And as this is not tested on real-life hardware I could simply use the same ports as they are used for the `l2_mtu`  - I suppose?

Is there anything to do in "ansible_collections/arista/avd/roles/eos_designs"... as l2_mru` is not part of a design I suppose not?

> Also, you need to generate documentation. This is done by running pre-commit locally. [Install pre-commit](https://avd.arista.com/4.3/docs/contribution/development.html#pre-commit-hook) and then run:
pre-commit run shemas --all

thanks for pointing this out...

**Comment by gmuloc** [comment]
Hello @m-rhode 

Answering some of the questions here as @carlbuchmann is in another timezone

So in general we try to avoid introducing some new knobs in `eos_cli_config_gen` and `eos_designs` in one go to make things clearer. Usually, we just recommend one PR to add the low-level CLI in `eos_cli_config_gen` and then a new one on top to do the `eos_designs` bit. Thus I will structure a list of tasks based on this assumed separation and tick the steps you have followed already.

Make sure to install the `requirements-dev.txt` to be able to complete the process (I believe you have already but mentioning it just in case)

## `eos_cli_config_gen`

This part of the change is aimed at adding some new knobs. The following tasks are required:
- [x] Adding the knob to the appropriate schema fragments file in the `roles/eos_cli_config_gen/schema/schema_fragments` directory (or create a new file if adding a top-level feature)
- [ ] Editing the Jinja2 templates in `roles/eos_cli_config_gen/templates/eos` and `roles/eos_cli_config_gen/templates/documentation` (or adding new template if adding a top-level feature, in that case, you should also modify the `roles/eos_cli_config_gen/templates/eos-device-documentation.j2` and ``roles/eos_cli_config_gen/templates/eos-intended-config.j2 to add these new templates, trying to respect the order in the EOS CLI)
  * __NOTE__: This one is partially done in your PR as you have modified only the `ethernet-interface.j2` template for config and not the `port-channel.j2` one where you have added the `l2mru` knob in the schema. Also for now you have not added anything to the documentation templates (it may or may not be necessary)
- [x] Run `pre-commit run shemas --all` to re-generate the eos_cli_config_gen schema with your modifications  (you need to do this every time you change the schema, even if this is just a description changed). This is also used to add the new options to our documentation.
- [ ] Add some molecule test in n the `molecule/eos_cli_config_gen` scenario exercising your new knob configuration
  * __NOTE__: In your case you would need to add to both `molecule/eos_cli_config_gen/inventory/host_vars/ethernet-interfaces.yml` and `molecule/eos_cli_config_gen/inventory/host_vars/port-channel-interfaces.yml` (re-using existing interfaces is fine as this is only for testing purposes)
 - [ ] Run the molecule test locally to generate the new expected configuration and documentation for these two hosts (we recommend running the full scenario using from `ansible_collections/arista/avd/molecule` folder the command `make  converge MOLECULE=eos_cli_config_gen`
 - [ ] Run all pre-commit checks `pre-commit run  --all`  to make sure that all files you have added are correct and won't be rejected by CI (this command will take ~1min)
 - [ ] Review that everything added looks correct and push to Github!

## `eos_designs`

> Is there anything to do in "ansible_collections/arista/avd/roles/eos_designs"... as l2_mru` is not part of a design I suppose not?

I just would like to point out that if you don't need the `l2_mru` in `eos_designs` you should remove the changes you have made to the python code there. Otherwise, there is a bit more work to do indeed. This can be done only after the `eos_cli_config_gen` part has been completed (hence why we usually recommend 2 PRs)

The process is very similar (for simple changes like yours) except for the jinja2 template part where you need to edit some Python code

- [ ] Adding the knob to the appropriate schema fragments file in the `roles/eos_designs/schema/schema_fragments` directory
  * __NOTE__:  For you it would be `eos_designs/schemas/schema_fragments/defs_adapter_config.schema.yml` - something like https://github.com/aristanetworks/ansible-avd/blob/devel/ansible_collections/arista/avd/roles/eos_designs/schemas/schema_fragments/defs_adapter_config.schema.yml#L44 .
- [x] Editing the relevant python_modules
  * __NOTE__:  This has been done for you but you now need to add the knob to the `eos_designs` schema for adapters or it will never be possible to use it
- [ ] Run `pre-commit run shemas --all`  to re-generate the eos_designs schema with your modifications  (you need to do this every time you change the schema, even if this is just a description changed). This is also used to add the new options to our documentation.
- [ ] Add some molecule test in n the `molecule/eos_designs_unit_tests` scenario exercising your new knob configuration
  * __NOTE__: In your case you would need to add the `l2mru` knob to some adapters, one for port-channel and one for ethertnet-interfaces. It may be simpler in your case to add to the `molecule/eos_designs_unit_tests/inventory/host_vars/connected_endpoints.yml` file
 - [ ] Run the molecule test locally to generate the new expected configuration and documentation for this two hosts (we recommend running the full scenario using from `ansible_collections/arista/avd/molecule` folder the command `make  converge MOLECULE=eos_designs_unit_tests`
 - [ ] Run all pre-commit checks `pre-commit run  --all`  to make sure that all files you have added are correct and won't be rejected by CI (this command will take ~1min)
 - [ ] Review that everything added looks correct and push to Github!


Let us know if you need further help

**Review by carlbuchmann — DISMISSED** [review]

**Comment by ghost** [comment]
Dear @carlbuchmann and @gmuloc ,
thanks a lot for your explanations, really appreciated. I was on PTO and today is my first day back. I'd have taken care of working further on this but as it seems I was to slow. Sorry for that and thanks for implementing this!

**Comment by ClausHolbechArista** [comment]
@carlbuchmann @m-rhode I have adjusted the schema a bit for min/max. For l2_mtu the min is 68 on all the device types I could find. This was set to 64, so please let me know if you have a platform saying 64.

**Comment by ghost** [comment]
@ClausHolbechArista thanks for working on this. Min 68 is fine for us.

**Review by ClausHolbechArista — APPROVED** [review]

**Review by gmuloc — APPROVED** [review]
LGTM

**Pull request merged**
