### PR TITLE
Refactor(eos_cli_config_gen): Addressed missed comments for patch-panel

### PR DESCRIPTION
**Pull request by gmuloc**
## Change Summary

Fix comments that were added in  patch-panel PR #4063 

## Component(s) name

`arista.avd.eos_cli_config_gen`

## Proposed changes

Add max values and group together min and max delay in reco

## How to test

molecule

### Repository Checklist

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [x] My change requires a change to the documentation and documentation have been updated accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

### CODE REVIEW

**Comment by gmuloc** [comment]
@Shivani-gslab @ccsnw @ClausHolbechArista

**Comment by Shivani-gslab** [comment]
https://github.com/aristanetworks/avd/pull/4078/files#diff-04eafc9714c156e4b9d33497f8abe2ff613613dee60edb095bbea33afd8b7c76L23-R26
this part of schema can be reduced to - `recovery_review_delay`

```
recovery_review_delay:
    type: dict
    keys:
        min:
            type: int
        max:
             type: int

```

Not able to comment on that line :)

**Comment by gmuloc** [comment]
> https://github.com/aristanetworks/avd/pull/4078/files#diff-04eafc9714c156e4b9d33497f8abe2ff613613dee60edb095bbea33afd8b7c76L23-R26 this part of schema can be reduced to - `recovery_review_delay`
> 
> ```
> recovery_review_delay:
>     type: dict
>     keys:
>         min:
>             type: int
>         max:
>              type: int
> ```
> 
> Not able to comment on that line :)

thanks for this comment ! I think we will stick with the schema from the original PR except if more people disagree / want to see it change? @ClausHolbechArista

**Comment by Shivani-gslab** [comment]
> > https://github.com/aristanetworks/avd/pull/4078/files#diff-04eafc9714c156e4b9d33497f8abe2ff613613dee60edb095bbea33afd8b7c76L23-R26 this part of schema can be reduced to - `recovery_review_delay`
> > ```
> > recovery_review_delay:
> >     type: dict
> >     keys:
> >         min:
> >             type: int
> >         max:
> >              type: int
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Not able to comment on that line :)
> 
> thanks for this comment ! I think we will stick with the schema from the original PR except if more people disagree / want to see it change? @ClausHolbechArista

Other than this, LGTM

**Review by Shivani-gslab — APPROVED** [review]

**Review by ClausHolbechArista — APPROVED** [review]

**Pull request merged**
