### PR TITLE
Update interface vlan documentation with summary, ISIS, OSPF, IPv4 and  IPv6

### LINKED ISSUE #271: Vlan Interface Device Documentation Template to be completed
Complete and organize information in this template according to the associated eos template

### PR DESCRIPTION
**Pull request by ksator**
## Change Summary
update int vlan doc to add ospf isis ipv4 ipv6 summary tables. 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [x] Documentation content changes
- [ ] Other (please describe):

## Component(s) name

eos_cli_config_gen role 

## Proposed changes

created a template to generate device documentation for vlans interfaces 

## How to test

execute the role eos_cli_config_gen 

Example of input for a device (int vlans with ipv4 and ipv6 and ospf and isis, hence many tables will be generated): 
```
vlan_interfaces:
  Vlan4093:
    description: MLAG_PEER_L3_PEERING
    ip_address: 10.255.251.0/31
    isis_enable: EVPN_UNDERLAY
    isis_metric: 50
    isis_network_point_to_point: true
  Vlan4094:
    description: MLAG_PEER
    ip_address: 10.255.252.0/31
    no_autostate: true
    mtu: 1500
  Vlan224:
    description: description1
    shutdown: false
    ip_address_virtual: 10.124.192.1/24
    ipv6_access_group_in: v555
    ipv6_access_group_out: ces cescew cw
    ipv6_address: 2a00:4b00:11d:6::15/64
    ipv6_nd_managed_config_flag: true
    ipv6_nd_prefixes:
      2a00:4b00:11d:6::/64:
        valid_lifetime: infinite
        preferred_lifetime: infinite
        no_autoconfig_flag: true
    ipv6_virtual_router_address: 2a00:4b00:11d:6::1
  Vlan225:
    description: description2
    shutdown: true
    ip_address_virtual: 10.124.192.1/24
    ipv6_address: 2a00:4b00:11d:6::15/64
    ipv6_nd_managed_config_flag: true
    ipv6_nd_prefixes:
      2a00:4b00:11d:6::/64:
        valid_lifetime: infinite
        preferred_lifetime: infinite
        no_autoconfig_flag: true
    ipv6_virtual_router_address: 2a00:4b00:11d:6::1
  Vlan501:
    description: description3
    shutdown: false
    ip_address: 10.15.126.29/27
    ipv6_address: 2a00:4b00:11d:90::207/127
    ipv6_nd_ra_disabled: true
  Vlan502: 
    ospf_network_point_to_point: true 
    ospf_area: 1
    ospf_cost: 20
    ip_address: 10.15.121.29/27
  Vlan503: 
    ospf_area: 2
    ip_address: 10.15.122.29/27
  Vlan4093:
    description: MLAG_PEER_L3_PEERING
    ip_address: 10.255.151.0/31
    isis_enable: EVPN_UNDERLAY
    isis_metric: 50
    isis_network_point_to_point: true
    access_group_in: acl2
    access_group_out: acl1
  Vlan111:
    shutdown: false
    tenant: Tenant_A
    enabled: true
    vrf: Tenant_A
    ip_address_virtual: 10.1.11.254/24
```
another device (in that case no isis no ospf no ipv6 table will show up in the int vlan doc)
```
vlan_interfaces:
  Vlan4094:
    description: MLAG_PEER
    ip_address: 10.255.252.0/31
    no_autostate: true
    mtu: 1500
  Vlan111:
    shutdown: false
    tenant: Tenant_A
    enabled: true
    vrf: Tenant_A
    ip_address_virtual: 10.1.11.254/24
```

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://www.avd.sh/docs/contributing/) document.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] All new and existing tests passed ([`pre-commit`](https://www.avd.sh/docs/installation/development/#python-virtual-environment), `make linting` and `make sanity-lint`).
- [ ] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly

### CODE REVIEW

**Review by aphillipps — APPROVED** [review]
LGTM

**Review by titom73 — APPROVED** [review]
LGTM!

**Comment by titom73** [comment]
@ksator Could you resolve conflict before we merge ?

**Review by aphillipps — APPROVED** [review]
LGTM

**Pull request merged**
