### PR TITLE
bgp: vrf: enhance neighbor options

### PR DESCRIPTION
**Pull request by c-po**
Currently it is not possible to utilize an iBGP peering using BGP VRFs as
next-hop-self can not be specified. In addition timers can not be programmed
and a neighbor can not carry a description.

Extend the Jinja2 template to support
- bgp vrf neighbor description
- bgp vrf neighbor next-hop-self
- bgp vrf timers

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [x] Documentation content changes
- [ ] Other (please describe):

## Related Issue(s)

This implements https://github.com/aristanetworks/ansible-avd/issues/489

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://www.avd.sh/docs/contributing/) document.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed ([`pre-commit`](https://www.avd.sh/docs/installation/development/#python-virtual-environment), `make linting` and `make sanity-lint`).
- [ ] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly

### CODE REVIEW

**Review by titom73 — APPROVED** [review]
LGTM!
In addition if you can update molecule to add a test case in `eos_cli_config_gen` for your changes, it would be super helpful to track any change later

[Documentation](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule#if-you-are-updating-eos_cli_config_gen)

Thanks again for your contribution !

**Comment by c-po** [comment]
I will have a look to also supply molecule tests in future PRs. Makes definately sense. Will send one for this PR later on.

**Comment by titom73** [comment]
> I will have a look to also supply molecule tests in future PRs. Makes definately sense. Will send one for this PR later on.

Thanks a lot. If you need more details we can do a session together to go through our implementation. Feel free to reach out if required.

**Comment by carlbuchmann** [comment]
@c-po, we required these knobs + additional ones for another project, so changes are now being tracked in PR #518 - it will be merged shortly! Thanks again for all your contributions to this project!

**Pull request closed without merging**
