### PR TITLE
Feat(eos_designs): Make DPS1 interface MTU 9k

### LINKED ISSUE #3532: Feat(eos_designs): Make DPS1 interface MTU 9k
### Enhancement summary

Recommended practice

### Which component of AVD is impacted

eos_designs

### Use case example

Avoid double fragmentation in certain cases

### Describe the solution you would like

In `roles/eos_designs/python_module/overlay/dps_interfaces.py`auto generate some MTU (if not present in `eos_cli_config_gen` add it in the same PR)

### Describe alternatives you have considered

_No response_

### Additional context

_No response_

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by ayushmittal-arista**
## Change Summary

Set MTU value for dps_interfaces in eos_designs. Not providing a override setting in eos_designs.

## Related Issue(s)

Fixes #3532

## Component(s) name

`arista.avd.eos_designs`

## Proposed changes
Auto-generating mtu 9000 for dps_interfaces in eos_designs

## How to test
molecule

### User Checklist

- N/A

### Repository Checklist

- [ ] My code has been rebased from devel before I start
- [ ] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [ ] My change requires a change to the documentation and documentation have been updated accordingly.
- [ ] I have updated [molecule CI](https://github.com/aristanetworks/avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

### CODE REVIEW

**Review by ClausHolbechArista — COMMENTED** [review]
LGTM. Still holding back approval until we get confirmation on the value.

**Comment by gmuloc** [comment]
@ayushmittal-arista value of 9214 was confirmed ok in internal discussion, can you please update the PR?

**Comment by ayushmittal-arista** [comment]
> @ayushmittal-arista value of 9214 was confirmed ok in internal discussion, can you please update the PR?

Done.

**Review by gmuloc — APPROVED** [review]
LGTM thanks!

**Review by ClausHolbechArista — APPROVED** [review]

**Pull request merged**
