### PR TITLE
Support setting hardware specific speed-groups for SERDES links

### LINKED ISSUE #346: Platform related speed-groups can't be configured
**Issue Type**

- Role enhancement

**Is your feature request related to a problem? Please describe.**
Setting to operation a new DCS-7280SR2-48YC6-F system I've noticed that I need to explicitly configure either the port speed on my individual interfaces or use the global `hardware speed-group12 serdes` command.

**Describe the solution you'd like**
Extend the current ansible-avd templates to support the configuration of the platforms speed groups.

**Describe alternatives you've considered**
Configlet's can be used for this, but when the configlet is bound to a container all devices inside this container must support the speed-group setting, which is false when simulating with vEOS-lab units.

**Proposed Data-Model**
```
speed_group:
  - id: 1
    serdes: <10g | 25g>
```

Using the following YAML statement:
```
speed_group:
  - id: 1
    serdes: 10g
  - id: 2
    serdes: 10g
  - id: 3
    serdes: 25g
```

will render the EOS configuration:
```
hardware speed-group1 serdes 10g
hardware speed-group2 serdes 10g
hardware speed-group3 serdes 25g
```
Once the data model is accepted I can start with the implementation. This is a backwards compatible extension as the data model is only extended and not altered.

### PR DESCRIPTION
**Pull request by c-po**
## Change Summary
Setting to operation a new DCS-7280SR2-48YC6-F system I've noticed that I need to explicitly configure either the port speed on my individual interfaces or use the global `hardware speed-group12 serdes` command.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [x] Documentation content changes
- [ ] Other (please describe):

## Related Issue(s)

Fixes #346 

## Proposed changes
**Proposed Data-Model**
```
speed_group:
  - id: 1
    serdes: <10g | 25g>
```

Using the following YAML statement:
```
speed_group:
  - id: 1
    serdes: 10g
  - id: 2
    serdes: 10g
  - id: 3
    serdes: 25g
```

will render the EOS configuration:
```
hardware speed-group1 serdes 10g
hardware speed-group2 serdes 10g
hardware speed-group3 serdes 25g
```

## Checklist:

- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly
- [x] I have read the [**CONTRIBUTING**](https://www.avd.sh/docs/contributing/) document.
- [x] All new and existing tests passed ([`pre-commit`](https://www.avd.sh/docs/installation/development/#python-virtual-environment), `make linting` and `make sanity-lint`).

### CODE REVIEW

**Comment by carlbuchmann** [comment]
@aphillipps @c-po, after reviewing the hardware command, I would suggest implementing the following data model:

The speed group id is unique, therefore making it the key and pluralizing speed_groups.

```yaml
hardware: 
  speed_groups:
  1:
    serdes: <10g | 25g>
```

Also, note hardware tcam profile should also be refactored to follow the new standards. This should be done in a separate PR, since it will break the existing data model.

```yaml
hardware:
  tcam_profile: < tcam-profile >
```

What do you think?

**Comment by c-po** [comment]
I can go forward and change this to:

```
hardware: 
  speed_groups:
  1:
    serdes: <10g | 25g>
  2:
    serdes: <10g | 25g>
  ...
```

Placing it under hardware was my first idea but I did not wanted to interfere with other code.

**Comment by c-po** [comment]
Refactored as to your request

**Review by titom73 — APPROVED** [review]
Looks good to me. Thanks for the PR!

**Pull request merged**
