### PR TITLE
Bump(eos_config_deploy_cvp)!: Make v3 the default collection

### LINKED ISSUE #2380: eos_config_deploy_cvp: Missing documentation of apply_mode
image

There is no documentation for the apply_mode: strict/loose in the URL: https://avd.sh/en/devel/roles/eos_config_deploy_cvp/index.html

This is a new feature applicable only for the cv_collection: v3

### PR DESCRIPTION
**Pull request by JulioPDX**
## Change Summary

This PR includes updates to set `cv_collection` default to `v3`. It also includes setting `apply_mode` to `loose` or `strict`. Previously it was always set to `loose` in `v3`. 

## Related Issue(s)

Fixes #2380

## Component(s) name

`arista.avd.eos_config_deploy_cvp`

## Proposed changes

- Set cv_collection default to v3
- Set apply_mode default to loose (same as before)
- Updated documentation
- Set deprecation warning in docs as well

## How to test

- molecule converge -s eos_config_deploy_cvp

### Repository Checklist

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [x] My change requires a change to the documentation and documentation have been updated accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

### CODE REVIEW

**Comment by JulioPDX** [comment]
@tgodaA A review would be much appreciated!

**Comment by ClausHolbechArista** [comment]
Not sure this is a "fix", but anyway please add a section to draft release-notes for 4.0 describing the (potentially breaking) behavioral changes and how to retain the pre4.0 behavior.

**Comment by gmuloc** [comment]
> Not sure this is a "fix", but anyway please add a section to draft release-notes for 4.0 describing the (potentially breaking) behavioral changes and how to retain the pre4.0 behavior.

maybe let's call it a Breaking Change Bump: `Bump!` and describe the impact?

**Comment by tgodaA** [comment]
We have an open PR #1883 related to this PR.

**Comment by JulioPDX** [comment]
> Not sure this is a "fix", but anyway please add a section to draft release-notes for 4.0 describing the (potentially breaking) behavioral changes and how to retain the pre4.0 behavior.

Updated PR with Bump and set draft release notes.

**Comment by ClausHolbechArista** [comment]
> We have an open PR #1883 related to this PR.

Looking at both, I think this one is a good first step, since we change the default but still keep the ability to go back to the older version. There are no implementation changes here.

Since the removal of v1 is also breaking, we should get that in to 4.0 as well, but maybe just get this one in first, and then remove versioning a month later - while in the dev/rc phase.

**Comment by gmuloc** [comment]
Probably should change from `Bump(eos_config_deploy_cvp)` to Bump(eos_config_deploy_cvp)!` (exclamation mark) to make it clear it is a breaking change?

**Comment by JulioPDX** [comment]
> Probably should change from `Bump(eos_config_deploy_cvp)` to Bump(eos_config_deploy_cvp)!` (exclamation mark) to make it clear it is a breaking change?

I agree, thank you

**Comment by JulioPDX** [comment]
I didn't realize we already have a PR open for this (apologies). Please see #1883 for updates.

**Pull request closed without merging**
