### PR TITLE
Implement ansible molecule to run Unit tests

### LINKED ISSUE #187: Implement variable to allow user to define root directory for documentation and intended
**Issue Type**
- Role enhancement

**Is your feature request related to a problem? Please describe.**

When implementing molecule unit-test, script execution generates a large number of warnings related to all generated files part of inventory folder

```shell
[WARNING]: Skipping unexpected key (Ethernet8) in group (ethernet_interfaces),
only "vars", "children" and "hosts" are valid
[WARNING]: Unable to parse /Users/tgrimonet/.cache/molecule/avd/avd-
build/inventory/intended/structured_configs/cvp as an inventory source
```

It does not break CI process but make it hard to read.

Here is an example: [CI runs in fork](https://github.com/titom73/ansible-avd/runs/866782241?check_suite_focus=true#step:4:232)

**Describe the solution you'd like**

Roles might use a custom key to allow specific location for generated files and set to `{{inventory_dir}}` by default.

An example is already present in [__arista.avd.build_output_folders__](https://github.com/aristanetworks/ansible-avd/blob/devel/ansible_collections/arista/avd/roles/build_output_folders/defaults/main.yml#L5)

**Describe alternatives you've considered**

Tried to avoid warning from molecule with no success

**Additional context**

Only related to CI implementation.

### PR DESCRIPTION
**Pull request by titom73**
# AVD Unit test

This section provides a list of AVD scenario executed during Continuous Integration to validate AVD integration.

## Ansible molecule

Molecule provides support for testing with multiple instances, operating systems and distributions, virtualization providers, test frameworks and testing scenarios. Molecule encourages an approach that results in consistently developed roles that are well-written, easily understood and maintained.

## Scenario

Current molecule implementation provides following scenario:

- AVD-L3LS-EBGP
- AVD-L3LS-EBGP-JSON
- AVD-L3LS-ISIS

## Manual execution

To manually run molecule testing, follow commands:

```shell
# Install development requirements
$ pip install -r development/requirements-dev.txt

# Move to AVD collection
$ ansible-avd/ansible_collections/arista/avd

# Run molecule for a given test
$ molecule test -s <scenario-name>

# Run molecule for all test
$ molecule test --all
```

## Continuous Integration

These scenario are all included in github actions and executed on `push` and `pull_request` when a file under `roles` and/or `molecule` is updated.

```yaml
name: Ansible Molecule
on:
  push:
  pull_request:
    paths:
      - 'ansible_collections/arista/avd/roles/**'
      - 'ansible_collections/arista/avd/molecules/**'
      - 'requirements.txt'
jobs:
  molecule:
    runs-on: ubuntu-latest
    env:
      PY_COLORS: 1 # allows molecule colors to be passed to GitHub Actions
      ANSIBLE_FORCE_COLOR: 1 # allows ansible colors to be passed to GitHub Actions
    strategy:
      fail-fast: true
      matrix:
        avd_scenario:
          - 'avd-l3ls-ebgp'
          - 'avd-l3ls-ebgp-json'
          - 'avd-l3ls-isis'
          - 'eos-cli-config-gen'
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r development/requirements.txt
          pip install -r development/requirements-dev.txt

      - name: Execute molecule
        run: |
          cd ansible_collections/arista/avd
          molecule test --scenario-name ${{ matrix.avd_scenario }}

      - uses: actions/upload-artifact@v1
        with:
          name: molecule-results-${{ matrix.avd_scenario }}
          path: ansible_collections/arista/avd/molecule/${{ matrix.avd_scenario }}

```

### CODE REVIEW

**Comment by titom73** [comment]
When PR will be validated, we will be able to remove `testing` folder and `playbook_validation.yml` from CI as it will be replaced by molecule approach

**Comment by titom73** [comment]
- [x] Add scenario for `eos_cli_config_gen` in molecule
- [x] Export artifacts from any scenario when CI runs

**Comment by titom73** [comment]
After review and before merge, molecule action should be set to `pull_request` only and `Ansible Execution / Execute Local playbooks` should be removed as well

**Comment by titom73** [comment]
Molecule is pruning all generated files meaning that artifacts do not have generated files. 

```
Pruning extra files from scenario ephemeral directory
```

**Review by carlbuchmann — APPROVED** [review]
LGMT

**Pull request merged**
