### PR TITLE
Feat(eos_designs): Allow overlapping VLAN IDs under network services

### PR DESCRIPTION
**Pull request by carlbuchmann**
## Change Summary

Remove to need for svis and l2vlans to be unique in the schema.
When leveraging filters and tags you may have duplicate SVI ids.

Requires #3747 to be merged

## Component(s) name

`arista.avd.eos_designs`

## Proposed changes

Update schema and add  `allow_duplicate_primary_key: True`

## How to test

- Added tests to eos_designs_unit_tests with duplicate svis and l2vlans
- eos_designs_deprecated_vars should pass CI to test the conversation of a dictionary to list.

### CODE REVIEW

**Comment by ClausHolbechArista** [comment]
This is not possible to implement now, since it would break convert_dicts and merge on primary_key.

**Review by arista-matt — APPROVED** [review]
Successfully tested on a 224 node inventory. Works great. Nice work.

**Review by ClausHolbechArista — APPROVED** [review]
Notice I changed the title.

**Review by JulioPDX — APPROVED** [review]
LGTM, took me a sec to make sure I was using proper filters between pods. Tested with tags and combining with filter `only_vlans_in_use`, worked beautifully!

**Pull request merged**
