### PR TITLE
Add options to change MLAG vlan ids

### LINKED ISSUE #841: Configurable MLAG L3 peering and MLAG peer vlan id's
**Issue Type**

- [X] Template enhancement
- [ ] Role enhancement
- [ ] Documentation enhancement (avd.sh)

**Is your feature request related to a problem? Please describe.**

Allow us to change the vlans for MLAG L3 peering and MLAG peer. Currently they are hard coded as 4093 and 4094. Using configurable values will allow people with existing VXLAN setups to migrate more easily.

**Describe the solution you'd like**

Add new `mlag_l3_peer_vlan_id` and `mlag_peer_vlan_id` options to `eos_designs`

**Describe alternatives you've considered**

Editing the repository myself and keeping a local copy

**Additional context**

### PR DESCRIPTION
**Pull request by melkypie**
## Change Summary

Allows to set vlan ids for mlag

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Documentation content changes
- [ ] Other (please describe):

## Related Issue(s)

Fixes #841 

## Component(s) name

`arista.avd.eos_designs`

## Proposed changes

```yaml
l3leaf:
  defaults:
    mlag_peer_l3_vlan: < 0-4094 | default -> 4093 >
    mlag_peer_vlan: < 0-4094 | default -> 4094 >
```

## Checklist:

- [X] My code has been rebased from devel before I start
- [X] I have read the [**CONTRIBUTING**](https://www.avd.sh/docs/contributing/) document.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly
- [X] All new and existing tests passed ([`pre-commit`](https://www.avd.sh/docs/installation/development/#python-virtual-environment), `make linting` and `make sanity-lint`).

### CODE REVIEW

**Comment by melkypie** [comment]
Seems like the CI failure is completely unrelated as there was no change in any python files

**Comment by titom73** [comment]
Indeed, this CI issue is related to a change in ansible-test and will be resolved with PR #876

**Comment by ClausHolbechArista** [comment]
Hi @melkypie we have a large refactoring PR #876 incoming for`eos_designs` where we will move most of the templates around and change some of the behavior. Please take a look at it and we can adjust this one after we have merged 876. Thank you for your great contributions.

**Comment by ClausHolbechArista** [comment]
Sorry I was trying to fix as well. My bad. I will do some final adjustments and merge it. I will use our `list_compress` plugin to avoid changing existing output when `peer_vlan` and `peer_l3_vlan` are consecutive.

**Review by ClausHolbechArista — APPROVED** [review]
LGTM! Thank you for this contribution.

**Pull request merged**
