### PR TITLE
Doc(eos_cli_config_gen): Deprecate old keys under gNMI

### PR DESCRIPTION
**Pull request by ClausHolbechArista**
## Change Summary

Deprecate old keys under gNMI

## Component(s) name

`arista.avd.eos_cli_config_gen`

## Proposed changes

- deprecate keys "enable_vrfs" and "octa" in favor of new data models previously inplemented.
- Update docs to be consistent in writing gnmi with mixed case: "gNMI"
- Update molecule scenarios

## How to test

- Updated existing molecule scenario using the deprecated keys to instead use the new keys. No config change (except reordering)

### User Checklist

- N/A

### Repository Checklist

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [x] My change requires a change to the documentation and documentation have been updated accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

### CODE REVIEW

**Comment by pvinci-arista** [comment]
Do we need to create/update a porting-guide-5.x.x, or can it be caught from the schema data alone?

**Comment by ClausHolbechArista** [comment]
> Do we need to create/update a porting-guide-5.x.x, or can it be caught from the schema data alone?

These deprecations will not affect the result of existing projects, but are just warnings about future removals. So I don't think they have to go into the porting guide.

**Review by carlbuchmann — APPROVED** [review]
LGTM

**Review by carl-baillargeon — APPROVED** [review]
LGTM

**Pull request merged**
