### PR TITLE
Implementing SNMP server community

### LINKED ISSUE #201: Add snmp-server community to snmp-settings template in eos_cli_config_gen
**Issue Type**
- Template enhancement

**Is your feature request related to a problem? Please describe.**
The community option is missing from snmp-settings

**Describe the solution you'd like**
Update to the following:
```
snmp_server:
  contact: < contact_name >
  location: < location >
  local_interfaces:
    - name: < interface_name_1 >
      vrf: < vrf_name >
    - name: < interface_name_2 >
  views:
    - name: < view_name >
      MIB_family_name: < MIB_family_name >
      included: < true | false >
    - name: < view_name >
      MIB_family_name: < MIB_family_name >
      included: < true | false >
  communities:
    - < community_name_1 >:
       access: < ro | rw >
       access_list:
          type: < ipv4 | ipv6 >
          name: 
       view: <view_name >
     - < community_name_2 >:
       access: < ro | rw >
       access_list:
          type: < ipv4 | ipv6 >
          name: 
       view: <view_name >
  groups:
    - name: < group_name >
      version: < v1 | v2c | v3 >
      authentication: < auth | noauth | priv >
      read: < read_view >
      write: < write_view >
      notify: < notify_view >
    - name: < group_name >
      version: < v1 | v2c | v3 >
      authentication: < auth | noauth | priv >
      read: < read_view >
  users:
    - name: < username >
      group: < group_name >
      version: < v1 | v2c | v3 >
      auth: < hash_algorithm >
      auth_passphrase: < encrypted_auth_passphrase >
      priv: < encryption_algorithm >
      priv_passphrase: < encrypted_priv_passphrase >
    - name: < username >
      group: < group_name >
      version: < v1 | v2c | v3 >
  hosts:
    - host: < host IP address or name >
      vrf: < vrf_name >
      users:
        - username: < username >
          authentication_level: < auth | noauth | priv >
          version: < 1 | 2c | 3 >
    - host: < host IP address or name >
      vrf: < vrf_name >
      users:
        - username: < username >
          authentication_level: < auth | noauth | priv >
          version: < 1 | 2c | 3 >
  traps:
    enable: < true | false >
  vrfs:
    - name: < vrf_name >
      enable: < true | false >
    - name: < vrf_name >
      enable: < true | false >
```

**Describe alternatives you've considered**
N/A

**Additional context**
Open to adjusting the model as this data model is already quite long / complex compared to others.

### PR DESCRIPTION
**Pull request by xaviramon**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Documentation content changes
- [ ] Other (please describe):

## Related Issue(s)

Fixes #201 
## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly
- [ ] I have read the [**CONTRIBUTING**](https://www.avd.sh/docs/contributing/) document.
- [ ] All new and existing tests passed ([`pre-commit`](https://www.avd.sh/docs/installation/development/#python-virtual-environment), `make linting` and `make sanity-lint`).

### CODE REVIEW

**Comment by titom73** [comment]
Hi @xaviramon 

Thanks for the PR. After looking at this first commit, we should update data model like this:

```yaml
snmp_server:
  communities:
    < community_name_1 >:
      access: < ro | rw >
      access_list_ipv4:
        name: < acl_ipv4_name >
      access_list_ipv6:
        name: < acl_ipv6_name >
      view: <view_name >
    < community_name_2 >:
      access: < ro | rw >
      access_list_ipv4:
        name: < acl_ipv4_name >
      access_list_ipv6:
        name: < acl_ipv6_name >
      view: <view_name >
```

Then, in template, you might change the following:

- Loop management: `for community in snmp_server.communities | arista.avd.natural_sort`
- Test within your CLI: You should at least test if `var is defined`. We can then assume that if defined means the user has provided a value.

A potential fix is

```diff
diff --git a/ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/eos/snmp-settings.j2 b/ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/eos/snmp-settings.j2
index 9f9c44a4..5e6832df 100644
--- a/ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/eos/snmp-settings.j2
+++ b/ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/eos/snmp-settings.j2
@@ -19,8 +19,8 @@ snmp-server view {{ view['name'] }} {{ view['MIB_family_name'] }} {% if view['in
 {%          endfor %}
 {%    endif %}
 {%    if snmp_server.communities is defined and snmp_server.communities is not none %}
-{%      for community in communities | arista.avd.natural_sort %}
-snmp-server community {{ community }} {% if snmp_server.communities[community].view is not none %}view {{ snmp_server.communities[community].view }}  {% endif %}{% if snmp_server.communities[community].access is defined %} {{ snmp_server.communities[community].access }} {% else %} ro {% endif %} {% if snmp_server.communities[community].access_list_ipv6.name is not none %} ipv6 {{ snmp_server.communities[community].access_list_ipv6.name }} {% endif %}{% if snmp_server.communities[community].access_list_ipv4.name is not none %}{{ snmp_server.communities[community].access_list_ipv4.name }} {% endif %}
+{%      for community in snmp_server.communities | arista.avd.natural_sort %}
+snmp-server community {{ community }} {% if snmp_server.communities[community].view is defined %}view {{ snmp_server.communities[community].view }}  {% endif %}{% if snmp_server.communities[community].access is defined %} {{ snmp_server.communities[community].access }} {% else %} ro {% endif %} {% if snmp_server.communities[community].access_list_ipv6.name is defined %} ipv6 {{ snmp_server.communities[community].access_list_ipv6.name }} {% endif %}{% if snmp_server.communities[community].access_list_ipv4.name is defined %}{{ snmp_server.communities[community].access_list_ipv4.name }} {% endif %}
 {%      endfor %}
 {%     endif %}
 {%     if snmp_server.groups is defined and snmp_server.groups is not none %}
```

**Comment by onurgashi** [comment]
Is it possible to add access-list for snmp-server as well additionally to per community?

snmp-server ipv4 access-list ACL-SNMP vrf default

**Comment by xaviramon** [comment]
@titom73 Changes implemented and pushed.

**Comment by titom73** [comment]
Need to be investigated with https://github.com/aristanetworks/ansible-avd/pull/447 as both are covering more or less the same perimeter.

**Comment by onurgashi** [comment]
Please review it with @aphillipps and include the documentation of my change in https://github.com/aristanetworks/ansible-avd/issues/377

Thanks

**Comment by melkypie** [comment]
Is this PR abandoned or are there any other issues as to why it's not merged?

**Comment by carlbuchmann** [comment]
Closing as PR is stale, and data model changed for snmp.

**Pull request closed without merging**
