### PR TITLE
Feat(eos_cli_config_gen): Enhance vlan_interfaces commands (arp_*)

### PR DESCRIPTION
**Pull request by ccsnw**
## Change Summary

adding

```    
vlan_interfaces:
  <snip>
  arp_cache_dynamic_capacity: < 0-4294967295 >
  arp_gratuitous_accept: < true | false >
  arp_monitor_mac_address: < true | false >
 <snip>
```

## Related Issue(s)

N/A

Just noticed that arp_gratuitous_accept is not explicitly defined and though of adding it, because its not so uncommon to use.

## Component(s) name

`arista.avd.eos_cli_config_gen`

## Proposed changes
Added several arp related commands under vlan_interfaces.

## How to test
molecule run

### User Checklist

- N/A

### Repository Checklist

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [x] My change requires a change to the documentation and documentation have been updated accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

### CODE REVIEW

**Comment by ccsnw** [comment]
Does a section for the arp related commands  per interface make sense in the documentation, or would it be overhead?

Other option would be to add some key information, e.g. if gratuitious arp is accepted to the "VLAN Interfaces Summary" table?

**Comment by ClausHolbechArista** [comment]
> Does a section for the arp related commands per interface make sense in the documentation, or would it be overhead?
> 
> Other option would be to add some key information, e.g. if gratuitious arp is accepted to the "VLAN Interfaces Summary" table?

I think these knobs are so "minor" that we should exempt them from documentation. They will still show up in the config snippets, but not be in any tables. @carlbuchmann @titom73 agree?

**Comment by xaviramon** [comment]
I would like to have a molecule configuration generated with all 3 variables you are creating: arp_cache_dynamic_capacity, arp_gratuitous_accept and arp_monitor_mac_address, so we can monitor any change on any of them with molecule automatically.

**Comment by ccsnw** [comment]
added! @xaviramon 
also fixed a typo in one of the commands

**Comment by carlbuchmann** [comment]
> 

Yes I agree with @ClausHolbechArista, all the various minor knobs don't need to be in the documentation table. That is why we have the config snippets!

**Comment by xaviramon** [comment]
Just a last comment before approving. We render the configuration the same way EOS will do it. Please, change the order of configuration render to:
```
arp gratuitous accept
arp monitor mac-address
arp cache dynamic capacity <number>
```
Thank you!

**Comment by ccsnw** [comment]
order changed @xaviramon

**Review by xaviramon — APPROVED** [review]
LGTM!

**Review by carlbuchmann — APPROVED** [review]
LGTM!

**Pull request merged**
