### PR TITLE
eos_cli_config_gen(feature): router bgp - implement default originate for peer groups

### LINKED ISSUE #964: BGP: missing support for default-originate on peer_group neighbor
**Issue Type**

- [x] Template enhancement
- [x] Role enhancement
- [ ] Documentation enhancement (avd.sh)

**Is your feature request related to a problem? Please describe.**

It is not possible to configure a default-originate on peer group neighbors as it is for single neighbors

**Describe the solution you'd like**

Implement default-originate feature the same way for peer_group as for neighbor.

```yaml
  address_family_ipv4:
    networks:
      < prefix_ipv4 >:
        route_map: < route_map_name >
    peer_groups:
      < peer_group_name >:
        route_map_in: < route_map_name >
        route_map_out: < route_map_name >
        activate: < true | false >
      < peer_group_name >:
        activate: < true | false >
        default_originate:
          always: < true | false >
          route_map: < route_map_name >
        prefix_list_in: < prefix_list_name >
        prefix_list_out: < prefix_list_name >
    neighbors:
      < neighbor_ip_address>:
        route_map_in: < route_map_name >
        route_map_out: < route_map_name >
        activate: < true | false >
        prefix_list_in: < prefix_list_name >
        prefix_list_out: < prefix_list_name >
      < neighbor_ip_address>:
        activate: < true | false >
        default_originate:
          always: < true | false >
          route_map: < route_map_name >
```

**Describe alternatives you've considered**

At the moment I'm using per neighbor configuration. But updating multiple sessions that must have the same settings takes a long time and is error prone.

**Additional context**

### PR DESCRIPTION
**Pull request by SomaliRaven**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [x] Documentation content changes
- [ ] Other (please describe):

## Related Issue(s)

Fixes #964

## Component(s) name

`arista.avd.<role-name>`

## Proposed changes

Extend Yaml definition.
## Checklist:

- [ ] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contributing/) document.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly
- [ ] All new and existing tests passed ([`pre-commit`](https://www.avd.sh/docs/installation/development/#python-virtual-environment), `make linting` and `make sanity-lint`).

### CODE REVIEW

**Comment by ClausHolbechArista** [comment]
Please update readme file to reflect the supported data model.
Please add tests for these models to molecule for eos_cli_config_gen.

**Review by titom73 — DISMISSED** [review]
Thanks for contributing !

Template looks good, but could you also update 

- README file in eos_cli_config_gen to reflect this new option
- Update [molecule file](https://github.com/aristanetworks/ansible-avd/blob/devel/ansible_collections/arista/avd/molecule/eos_cli_config_gen/inventory/host_vars/router-bgp-base.yml) and run molecule as [described here](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule)

In case you are not familiar with Molecule, we will run it on your own and update PR once everything is ready.

**Comment by SomaliRaven** [comment]
@titom73, i updated the documentation. I am not familiar with Molecule and it would be great if you could update it.

**Comment by c-po** [comment]
The molecule system is actually very easy and good explained here: https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule

In this case only the following would be needed:
image

**Comment by carlbuchmann** [comment]
> The molecule system is actually very easy and good explained here: https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule
> 
> In this case only the following would be needed:
> image

Thanks @c-po !

**Review by carlbuchmann — APPROVED** [review]
@SomaliRaven Thanks for this PR, your updates to documentation and tests are good!

**Comment by carlbuchmann** [comment]
@SomaliRaven - I see your commits are signed with: `sebastian.lausch@controlware.de`, I would recommend linking this email to your GitHub profile!

**Pull request merged**
