### PR TITLE
Extend Ethernet Speed Changes options

### LINKED ISSUE #319: eos_cli_config_gen add support for interface "speed auto"
**Issue Type**
- Template enhancement

As of now it is not possible to change the advertised autonegotiation modes via ansible-avd. Given the following implementation: https://github.com/aristanetworks/ansible-avd/blob/devel/ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/eos/ethernet-interfaces.j2#L12-L14 one can either choose between a fully "fixed" configuration or "autoneg". There is some equipment out there which requires autoneg with a capability of 100 MBit fdx which can't be set at this time.

**Is your feature request related to a problem? Please describe.**
Networking gear which required 100 MBit autoneg fdx can't be configured

**Describe the solution you'd like**
Template extension to choose between forced and auto option form the EOS CLI

**Describe alternatives you've considered**
A configlet seems not to be the perfect fit here :(

We should discuss a change of the data model how this feature can be represented in a backwards compatible way. After the data-model is fixed I can submit a PR

## Proposed data-model
```
# Routed Interfaces
ethernet_interfaces:
  <Ethernet_interface_1 >:
    description: < description >
    shutdown: < true | false >
    speed: < forced_interface_speed >
      auto: < autoneg_offered_interface_speed >
```

Thus already existing YML definitions won't break. @aphillipps what you think?

### PR DESCRIPTION
**Pull request by carlbuchmann**
Change data model as described in https://github.com/aristanetworks/ansible-avd/issues/319
to support additional speed options per ethernet interface.

```
  speed:
    mode: < no-auto | forced | auto >
    speed: < interface_speed >
```

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [x] Documentation content changes
- [ ] Other (please describe):

## Related Issue(s)
resolves #319 

## Component(s) name
* eos_cli_config_gen

## Proposed changes
Change data model to support additional link-speed options.

## Checklist:

- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly
- [x] I have read the [**CONTRIBUTING**](https://www.avd.sh/docs/contributing/) document.
- [ ] All new and existing tests passed ([`pre-commit`](https://www.avd.sh/docs/installation/development/#python-virtual-environment), `make linting` and `make sanity-lint`).

## To Do
- [ ] Update eos_l3ls_evpn
- [ ] Add molecule test case

### CODE REVIEW

**Comment by carlbuchmann** [comment]
@c-po Since this is a breaking change, I will continue to work on this PR and update the eos_l3ls_evpn role accordingly.

**Comment by ClausHolbechArista** [comment]
@carlbuchmann  Isn't it simpler to just parse the string "forced 10000mbitfull" or "auto 100gbps" or whatever directly ? We could make it non-breaking by checking for forced or auto keywords.

**Comment by ClausHolbechArista** [comment]
Valid EOS CLI for `speed` under and interface is:
```
speed ( SPEED_NODE | SPEED_HIDDEN_NODE )
speed auto [ ( SPEEDAUTO_NODE | SPEEDAUTO_HIDDEN_NODE ) ]
speed forced ( SPEED_FORCE_NODE | SPEED_FORCE_HIDDEN_NODE )
speed sfp-1000baset auto 100full
```
so 1 2 or 3 arguments. Auto accept no speed set.
Instead of trying to map this into eos_cli_config_gen, we will allow flexible configurations by just passing through the `speed` string value untouched. We will change the hardcoded `speed forced <string> ` from the template to `speed <string>`.

**Comment by c-po** [comment]
So will this be a change in the EOS binary itself?

**Comment by ClausHolbechArista** [comment]
No much simpler. We will just enable that you can set `speed: forced 1000mbitfull` or `speed: auto` or `speed: auto 1000mbitfull` etc. So simply write the EOS cli string after `speed`.

**Comment by ClausHolbechArista** [comment]
@c-po see PR #594

**Pull request closed without merging**
