### PR TITLE
Molecule CI refactoring

### LINKED ISSUE #320: Refactor Molecule CI scenario
**Issue Type**

- CI & testing scenrio

Make CI more granular to easily extend CI for every PR and new features.

Currently, CI with MOlecule is in place but does not cover 100% of the feature set with complexity to extend.

The idea would be to refactor scenarios to make it easier to maintain and update by maintainers and also to increase coverage.

### LINKED ISSUE #331: Remove structured_configs file as requirement for eos_cli_config_gen
**Issue Type**

- Role enhancement

**Is your feature request related to a problem? Please describe.**

Today `eos_cli_config_gen` requires to load variables file from `'{{ root_dir }}/intended/structured_configs//{{ inventory_hostname }}.yml`.

But if `eos_l3ls_evpn` is not implemented, there is no reason for that file to exist as it is not a default ansible output and all variables should be read from default locations.

**Describe the solution you'd like**

Add a constraint to only load file if it is present. If not, we should consider variables to be part of `host_vars` and `group_vars` or any other ansible standard mechanism to load variables.

**Describe alternatives you've considered**

N/A

**Additional context**

Identified in CI context but should be used in any other context.

### PR DESCRIPTION
**Pull request by titom73**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes)
- [ ] Documentation content changes
- [x] Other (please describe): Continuous Integration

## Related Issue(s)

Fixes #320 
Fixes #331 

## Component(s) name

Continuous Integration process

### Step by step commands

```bash
# Go to test folder
$ cd ansible_collections/arista/avd

# Edit molecule scenario
$ vim <molecule-file>

# Run testing
$ molecule test --scenario-name < scenario-name >

# Review artifacts and commit changes
$ git commit --no-verify -m 'Update CI artifacts' .

# Optional
# Cleanup your environment
$ molecule cleanup --scenario-name < scenario-name >
```

### Using Make commands

```shell
# Go to test folder
$ cd ansible_collections/arista/avd/molecule

# Run a specific molecule scenario
$ make run MOLECULE=< scenario-name >
 
# Run & refresh all artifacts
$ make refresh-facts

# Review and commit changes
$ make commit-facts

# All in one command
$ make sync-facts
```

## Checklist:

- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly
- [x] I have read the [**CONTRIBUTING**](https://www.avd.sh/docs/contributing/) document.
- [x] All new and existing tests passed ([`pre-commit`](https://www.avd.sh/docs/installation/development/#python-virtual-environment), `make linting` and `make sanity-lint`).

### CODE REVIEW

**Comment by titom73** [comment]
Working on a way to monitor and report GIT changes after `eos_cli_config_gen`

**Comment by titom73** [comment]
Molecule for `eos_cli_config_gen` now monitor git status as a result. 

- If molecule changes configuration output --> Action fails
- if molecule does not change output --> Action succeeds

**Comment by titom73** [comment]
Todo:

- [x] Populate test use cases

**Comment by titom73** [comment]
Right before the merge process, we need to rebase to update tests & artifacts with the latest PRs:

- [ ] #307 
- [ ] #337 
- [ ] #353 
- [ ] #368

**Comment by titom73** [comment]
The branch has been rebased to resolve conflict.

**Comment by titom73** [comment]
Add Makefile to automate CI tests

```bash
# Go to test folder
$ cd ansible_collections/arista/avd/molecule

# Run a specific molecule scenario
$ make run MOLECULE=< scenario-name >
 
# Run & refresh all artifacts
$ make refresh-facts

# Review and commit changes
$ make commit-facts

# All in one command
$ make sync-facts
```

**Review by carlbuchmann — APPROVED** [review]
LGTM!

**Pull request merged**
