### PR TITLE
Fix(eos_cli_config_gen): Sort IPsec SA, IKE policies and profiles

### PR DESCRIPTION
**Pull request by gmuloc**
## Change Summary

Today these objects are not sorted and so not matching the EOS cli output

## Related Issue(s)

Found in field 

## Component(s) name

`arista.avd.eos_cli_config_gen`

## Proposed changes

Adding sort for doc and eos template

## How to test

molecule

### Repository Checklist

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [x] My change requires a change to the documentation and documentation have been updated accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

### CODE REVIEW

**Review by Vibhu-gslab — APPROVED** [review]
LGTM!

**Review by MaheshGSLAB — APPROVED** [review]
Tested on lab

**Review by ClausHolbechArista — CHANGES_REQUESTED** [review]
Postponing to AVD 5.0.0 since this seems to be changing between EOS versions.

**Comment by ClausHolbechArista** [comment]
Moving to draft until 4.10 has been released.

**Comment by ClausHolbechArista** [comment]
Please add to release-notes for 5.x.x that we have reordered config and mention the area. It will be a common section for everything we decide to reorder.

**Review by ClausHolbechArista — APPROVED** [review]

**Pull request merged**
