### PR TITLE
Feat(eos_cli_config_gen): Add BGP VRF prefix-list support (#1248)

### LINKED ISSUE #1248: BGP does not support prefix filters inside the VRF statement
### Enhancement summary

Add support for prefix filters inside a BGP VRF statement

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

We need prefix filtering support in a VRF.

### Describe the solution you would like

Same as for "regular" neighbors
```yaml
router_bgp:
  vrfs:
    < vrf_name_1 >:
      neighbors:
        < neighbor_ip_address >:
          remote_as: < asn >
          prefix_list_in: < prefix_list_name >
          prefix_list_out: < prefix_list_name >
```

### Describe alternatives you have considered

_No response_

### Additional context

_No response_

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by c-po**
## Change Summary

Extend BGP VRF to also support per neighbor prefix-filters

## Related Issue(s)

Fixes #1248

## Component(s) name

`arista.avd.eos_cli_config_gen`

## Proposed changes

```yaml
router_bgp:
  vrfs:
    < vrf_name_1 >:
      neighbors:
        < neighbor_ip_address >:
          remote_as: < asn >
          prefix_list_in: < prefix_list_name >
          prefix_list_out: < prefix_list_name >
```

## How to test

Buildin molecule tests

### User Checklist

- N/A

### Repository Checklist

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [x] My change requires a change to the documentation and documentation have been updated accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

### CODE REVIEW

**Comment by tgodaA** [comment]
LGTM!

Need to add this feature to release-notes.

**Review by emilarista — APPROVED** [review]
LGTM!

**Review by tgodaA — APPROVED** [review]
LGTM!

**Review by ClausHolbechArista — APPROVED** [review]
LGTM

**Pull request merged**
