### PR TITLE
Feat: Add Execution environment files for ansible-builder

### PR DESCRIPTION
**Pull request by ClausHolbechArista**
## Change Summary

Feat: Add Execution environment files for ansible-builder

## Component(s) name

`arista.avd`

## Proposed changes

- Add meta/execution-environment.yml file used by ansible-builder to detect requirements when then collection is a dependency for another collection / EE
- Add /execution-environment.yml to be used for creating EE for ansible-avd + dependencies

## How to test

Create EE image using cli:
```shell
cd ansible-avd
ansible-builder build --container-runtime=docker --tag=arista-avd-runner --verbosity 3 -c .
```

This cannot be tested until [ansible-cvp PR](https://github.com/aristanetworks/ansible-cvp/pull/466) has been merged.

I tested it by pointing the arista.avd requirements to the PR above. That worked and I tested successfully both on AWX and using CLI:
```shell
docker run --rm -e RUNNER_PLAYBOOK=build.yml -v $PWD:/runner arista-avd-runner:latest
```

### Repository Checklist

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [x] My change requires a change to the documentation and documentation have been updated accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

### CODE REVIEW

**Comment by ryanmerolle** [comment]
This is great!  I was just about to raise a ticket on this.  I tested the fix and it works!

Without this fix, ansible-builder fails if you included `arista.avd` in most cases.

`arista.cvp` also needs a similar fix.

I would approve this, since my test works.  I do not have the ability to approve.

**Review by carlbuchmann — APPROVED** [review]
LGTM - required PR for ansible-cvp has been reviewed and merged!
note that until new release of ansible-cvp to galaxy ansible-build will still fail.

**Comment by ClausHolbechArista** [comment]
Ready for test. The CVP fix got released Yesterday.

**Comment by ryanmerolle** [comment]
LGTM

**Comment by ryanmerolle** [comment]
It would be great to see this in the next minor release.

**Review by tgodaA — APPROVED** [review]
LGTM

Tested locally.

**Pull request merged**
