### PR TITLE
Fix readme typos, add lag_hardware command

### PR DESCRIPTION
**Pull request by onurgashi**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [x] Documentation content changes
- [ ] Other (please describe):

## Related Issue(s)

Adds lag_hardware and fixes some quotation marks and whitespaces.

## Component(s) name

`arista.avd.eos_l3ls_evpn`

## Checklist:

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://www.avd.sh/docs/contributing/) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly
- [ ] All new and existing tests passed ([`pre-commit`](https://www.avd.sh/docs/installation/development/#python-virtual-environment), `make linting` and `make sanity-lint`).

### CODE REVIEW

**Comment by onurgashi** [comment]
max_super_spines: 4  # maximum number of super-spines, changing this parameter affects address allocation

Inform that there is a default formula and this is optional.
`max_super_spines: 4`

**Review by titom73 — APPROVED** [review]
LGTM!

**Comment by onurgashi** [comment]
`# Defined in SPINE.yml file
type: spine`

SPINES.yml

**Comment by onurgashi** [comment]
Not required `mlag_dual_primary_detection: false`

**Review by ClausHolbechArista — APPROVED** [review]
LGTM

**Pull request merged**
