### PR TITLE
Feat( eos_designs, eos_cli_config_gen): Add "disabled" option to "local_users"

### LINKED ISSUE #2254: Disable username admin
### Enhancement summary

It is common to disable the admin username. In my case I create and use other default admin accounts.

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

Need to render the following command:

`no username admin `

### Describe the solution you would like

A way to do this in the users data model:

```yaml
local_users:
  < user_1 >:
    disabled: true
``` 

### Describe alternatives you have considered

I currently use the eos_cli key to do it and it gets rendered at the end of the config. For some reason CVP doesn't like it in some cases.

### Additional context

_No response_

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by gusmb**
## Change Summary

Add `disabled` key to `local_users` datamodel

## Related Issue(s)

Fixes #2254 

## Component(s) name

* `arista.avd.eos_designs`
* `arista.avd.eos_cli_config_gen`

## Proposed changes

Modified templates to include a `disabled` key. When `disabled=true`, the template renders:

```
no username <name>
```

Updated documentation to include a "Disabled" column to reflect the status of the user

## How to test

See molecule facts

### User Checklist

- N/A

### Repository Checklist

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [x] My change requires a change to the documentation and documentation have been updated accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

### CODE REVIEW

**Comment by gusmb** [comment]
@ClausHolbechArista I adjusted this PR bit some checks are failing on an unrelated issue I think...

**Comment by gusmb** [comment]
@ClausHolbechArista @tgodaA pls review, should be ready now.

**Review by ClausHolbechArista — APPROVED** [review]

**Comment by ClausHolbechArista** [comment]
Please update the schema fragment for local_users (see #2256) and then run molecule `build_schemas_and_docs`. Or if you prefer I can add it to your PR.

**Comment by gusmb** [comment]
Added updates to `eos_designs` python module `base.py` and molecule test included from #2256

**Review by ClausHolbechArista — APPROVED** [review]

**Review by gmuloc — APPROVED** [review]
LGTM

**Pull request merged**
