### PR TITLE
feat(eos_cli_config_gen): Add support for redistribution of bgp routes into ospf

### LINKED ISSUE #1081: OSPF: Missing support for redistribution of BGP routes
**Issue Type**

- [x] Template enhancement
- [x] Role enhancement
- [ ] Documentation enhancement (avd.sh)

**Is your feature request related to a problem? Please describe.**

It is not possible to configure redistribution of bgp routes into ospf.

**Describe the solution you'd like**

Implement redistribution of bgp routes into ospf the same way as with static and connected routes.

```yaml
router_ospf:
  process_ids:
    < process_id >:
      redistribute:
        static:
          route_map: < route_map_name >
        connected:
          route_map: < route_map_name >
        bgp:
          route_map: < route_map_name >

```

### PR DESCRIPTION
**Pull request by SomaliRaven**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [x] Documentation content changes
- [ ] Other (please describe):

## Related Issue(s)

Fixes #1081 

## Component(s) name

`arista.avd.<role-name>`

## Proposed changes
Extend Yaml definition to allow redistribution of bgp routes in ospf.
```yaml
router_ospf:
  process_ids:
    < process_id >:
      redistribute:
        static:
          route_map: < route_map_name >
        connected:
          route_map: < route_map_name >
        bgp:
          route_map: < route_map_name >

```

## Checklist:

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contributing/) document.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly
- [ ] All new and existing tests passed ([`pre-commit`](https://www.avd.sh/docs/installation/development/#python-virtual-environment), `make linting` and `make sanity-lint`).

### CODE REVIEW

**Review by ClausHolbechArista — COMMENTED** [review]
Looking good so far. We are missing updates to the documentation template.
The currently table for "Router OSPF Router Redistribution" has a column per knob. This will not scale well, so I suggest that we change the table to have columns like "Source Protocol" and "Route Map" and then add lines per protocol instead.
Let me know if you want me to add this directly to your branch.

**Review by onurgashi — COMMENTED** [review]
Would it make more sense to have a general redistribute command and not a specific bgp one, if in the future we would add other options?

Afaik in the end we have the route-map option for all of them?

**Comment by ClausHolbechArista** [comment]
> Would it make more sense to have a general redistribute command and not a specific bgp one, if in the future we would add other options?
> 
> Afaik in the end we have the route-map option for all of them?

Not a bad idea Onur, like we do on BGP. But for now, I think we can implement this one, and then submit an issue to create the more maintenance-free version.

**Comment by SomaliRaven** [comment]
> Looking good so far. We are missing updates to the documentation template.
> The currently table for "Router OSPF Router Redistribution" has a column per knob. This will not scale well, so I suggest that we change the table to have columns like "Source Protocol" and "Route Map" and then add lines per protocol instead.
> Let me know if you want me to add this directly to your branch.

I guess my last commit should fix this and add the proposed table for multiple source protocols.

**Review by onurgashi — APPROVED** [review]
LGTM!

**Comment by titom73** [comment]
Thanks for your PR @SomaliRaven. Please, could you fix conflicts, and then we will be happy to merge it.

**Comment by ClausHolbechArista** [comment]
Rebased and conflicts resolved.

**Review by ankudinov — APPROVED** [review]
LGTM
created #1126 to improve data model in future

**Pull request merged**
